
  CREATE OR REPLACE EDITIONABLE TRIGGER "CF_DOWNLOAD_FILE_TRG" 
BEFORE INSERT ON MCZBASE.CF_DOWNLOAD_FILE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CF_DOWNLOAD_FILE_ID IS NULL THEN
      SELECT CF_DOWNLOAD_FILE_SEQ.NEXTVAL INTO :NEW.CF_DOWNLOAD_FILE_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "CF_DOWNLOAD_FILE_TRG" ENABLE