
  CREATE OR REPLACE TRIGGER "CF_FORM_PERMISSIONS_R_KEY" 
BEFORE UPDATE OR INSERT ON MCZBASE.cf_form_permissions_r
FOR EACH ROW
BEGIN
	IF :new.key IS NULL THEN
		SELECT somerandomsequence.NEXTVAL INTO :new.KEY FROM dual;
	END IF;
END;
ALTER TRIGGER "CF_FORM_PERMISSIONS_R_KEY" ENABLE