
  CREATE OR REPLACE EDITIONABLE TRIGGER "CF_GRID_PROPERTIES_PK_TRG" 
BEFORE INSERT ON MCZBASE.CF_GRID_PROPERTIES 
FOR EACH ROW 
BEGIN
    IF INSERTING AND :NEW.CF_GRID_COLUMNS_VISIBILITY_ID IS NULL THEN
      SELECT MCZBASE.SEQ_CF_GRID_PROPERTIES_PK.NEXTVAL INTO :NEW.CF_GRID_COLUMNS_VISIBILITY_ID FROM DUAL;
    END IF;
END;

ALTER TRIGGER "CF_GRID_PROPERTIES_PK_TRG" ENABLE