
  CREATE OR REPLACE TRIGGER "CF_SPEC_SEARCH_COLS_TRG" 
BEFORE INSERT ON MCZBASE.CF_SPEC_SEARCH_COLS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT CF_SPEC_SEARCH_COLS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
ALTER TRIGGER "CF_SPEC_SEARCH_COLS_TRG" ENABLE