
  CREATE OR REPLACE TRIGGER "CF_TEMP_RELATIONS_ID" BEFORE INSERT ON CF_TEMP_RELATIONS
FOR EACH ROW
BEGIN
	SELECT sq_cf_temp_relations_id.NEXTVAL 
	into :new.cf_temp_relations_id FROM dual;
END;

ALTER TRIGGER "CF_TEMP_RELATIONS_ID" ENABLE