
  CREATE OR REPLACE EDITIONABLE TRIGGER "CF_TEMP_ID_KEY" 
BEFORE INSERT ON "MCZBASE"."CF_TEMP_ID"
FOR EACH ROW
BEGIN
        IF :NEW.key IS NULL THEN
                SELECT somerandomsequence.nextval INTO :new.key FROM DUAL;
        END IF;
END;




ALTER TRIGGER "CF_TEMP_ID_KEY" ENABLE