
  CREATE OR REPLACE TRIGGER "COLL_OBJ_DISP_VAL" 
BEFORE INSERT or UPDATE ON coll_obj_other_id_num
FOR EACH ROW
BEGIN
    :NEW.display_value := :NEW.OTHER_ID_PREFIX || :NEW.OTHER_ID_NUMBER || :NEW.OTHER_ID_SUFFIX;
END;

ALTER TRIGGER "COLL_OBJ_DISP_VAL" ENABLE