
  CREATE OR REPLACE EDITIONABLE TRIGGER "COLL_EVENT_NUMBER_TRG" 
BEFORE INSERT ON MCZBASE.COLL_EVENT_NUMBER 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COLL_EVENT_NUMBER_ID IS NULL THEN
      SELECT COLL_EVENT_NUMBER_SEQ.NEXTVAL INTO :NEW.COLL_EVENT_NUMBER_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "COLL_EVENT_NUMBER_TRG" ENABLE