
  CREATE OR REPLACE TRIGGER "COLL_EVENT_NUM_SERIES_TRG" 
BEFORE INSERT ON MCZBASE.COLL_EVENT_NUM_SERIES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.COLL_EVENT_NUM_SERIES_ID IS NULL THEN
      SELECT COLL_EVENT_NUM_SERIES_SEQ.NEXTVAL INTO :NEW.COLL_EVENT_NUM_SERIES_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
ALTER TRIGGER "COLL_EVENT_NUM_SERIES_TRG" ENABLE