
  CREATE OR REPLACE EDITIONABLE TRIGGER "GUID_OUR_THING_TRG" 
BEFORE INSERT ON MCZBASE.GUID_OUR_THING 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.GUID_OUR_THING_ID IS NULL THEN
      SELECT GUID_OUR_THING_SEQ.NEXTVAL INTO :NEW.GUID_OUR_THING_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
ALTER TRIGGER "GUID_OUR_THING_TRG" ENABLE