
  CREATE OR REPLACE EDITIONABLE TRIGGER "TR_ANNOTATIONS_HISTORY" 
AFTER INSERT OR UPDATE OR DELETE
ON MCZBASE.ANNOTATIONS
FOR EACH ROW
DECLARE
	v_changed_by_username VARCHAR2(255);
	v_changed_by_agent_id NUMBER;
	v_changed_date DATE;

	PROCEDURE set_actor_from_agent_id (
		p_agent_id IN NUMBER
	) IS
	BEGIN
		v_changed_by_agent_id := p_agent_id;

		IF p_agent_id IS NOT NULL THEN
			BEGIN
				SELECT MIN(an.agent_name)
				INTO v_changed_by_username
				FROM MCZBASE.AGENT_NAME an
				WHERE an.agent_id = p_agent_id
					AND an.agent_name_type = 'login';
			EXCEPTION
				WHEN NO_DATA_FOUND THEN
					NULL;
			END;
		END IF;
	END;

	PROCEDURE set_actor_from_username (
		p_username IN VARCHAR2
	) IS
	BEGIN
		IF p_username IS NOT NULL AND LENGTH(TRIM(p_username)) > 0 THEN
			v_changed_by_username := p_username;

			BEGIN
				SELECT MIN(an.agent_id)
				INTO v_changed_by_agent_id
				FROM MCZBASE.AGENT_NAME an
				WHERE an.agent_name_type = 'login'
					AND an.agent_name = p_username;
			EXCEPTION
				WHEN NO_DATA_FOUND THEN
					NULL;
			END;
		END IF;
	END;

	PROCEDURE initialize_actor_for_insert IS
	BEGIN
		v_changed_by_username := NULL;
		v_changed_by_agent_id := NULL;
		v_changed_date := NVL(:NEW.LAST_UPDATED_DATE, SYSDATE);

		IF :NEW.LAST_UPDATED_BY_AGENT_ID IS NOT NULL THEN
			set_actor_from_agent_id(:NEW.LAST_UPDATED_BY_AGENT_ID);
		ELSIF :NEW.ANNOTATOR_AGENT_ID IS NOT NULL THEN
			set_actor_from_agent_id(:NEW.ANNOTATOR_AGENT_ID);
		ELSIF :NEW.CF_USERNAME IS NOT NULL THEN
			set_actor_from_username(:NEW.CF_USERNAME);
		ELSE
			set_actor_from_username(SYS_CONTEXT('USERENV', 'SESSION_USER'));
		END IF;

		IF v_changed_by_username IS NULL AND :NEW.CF_USERNAME IS NOT NULL THEN
			v_changed_by_username := :NEW.CF_USERNAME;
		END IF;

		IF v_changed_by_username IS NULL THEN
			v_changed_by_username := SYS_CONTEXT('USERENV', 'SESSION_USER');
		END IF;
	END;

	PROCEDURE initialize_actor_for_update IS
	BEGIN
		v_changed_by_username := NULL;
		v_changed_by_agent_id := NULL;
		v_changed_date := NVL(:NEW.LAST_UPDATED_DATE, SYSDATE);

		IF :NEW.LAST_UPDATED_BY_AGENT_ID IS NOT NULL THEN
			set_actor_from_agent_id(:NEW.LAST_UPDATED_BY_AGENT_ID);
		ELSIF :OLD.LAST_UPDATED_BY_AGENT_ID IS NOT NULL THEN
			set_actor_from_agent_id(:OLD.LAST_UPDATED_BY_AGENT_ID);
		ELSE
			set_actor_from_username(SYS_CONTEXT('USERENV', 'SESSION_USER'));
		END IF;

		IF v_changed_by_username IS NULL THEN
			v_changed_by_username := SYS_CONTEXT('USERENV', 'SESSION_USER');
		END IF;
	END;

	PROCEDURE initialize_actor_for_delete IS
	BEGIN
		v_changed_by_username := NULL;
		v_changed_by_agent_id := NULL;
		v_changed_date := SYSDATE;

		IF :OLD.LAST_UPDATED_BY_AGENT_ID IS NOT NULL THEN
			set_actor_from_agent_id(:OLD.LAST_UPDATED_BY_AGENT_ID);
		ELSIF :OLD.ANNOTATOR_AGENT_ID IS NOT NULL THEN
			set_actor_from_agent_id(:OLD.ANNOTATOR_AGENT_ID);
		ELSIF :OLD.CF_USERNAME IS NOT NULL THEN
			set_actor_from_username(:OLD.CF_USERNAME);
		ELSE
			set_actor_from_username(SYS_CONTEXT('USERENV', 'SESSION_USER'));
		END IF;

		IF v_changed_by_username IS NULL AND :OLD.CF_USERNAME IS NOT NULL THEN
			v_changed_by_username := :OLD.CF_USERNAME;
		END IF;

		IF v_changed_by_username IS NULL THEN
			v_changed_by_username := SYS_CONTEXT('USERENV', 'SESSION_USER');
		END IF;
	END;

	PROCEDURE log_history (
		p_annotation_id      IN NUMBER,
		p_event_type         IN VARCHAR2,
		p_changed_table      IN VARCHAR2,
		p_changed_field      IN VARCHAR2,
		p_old_value          IN VARCHAR2,
		p_new_value          IN VARCHAR2
	) IS
	BEGIN
		INSERT INTO MCZBASE.ANNOTATION_HISTORY (
			ANNOTATION_HISTORY_ID,
			ANNOTATION_ID,
			EVENT_TYPE,
			CHANGED_TABLE,
			CHANGED_FIELD,
			OLD_VALUE,
			NEW_VALUE,
			CHANGED_BY_USERNAME,
			CHANGED_BY_AGENT_ID,
			CHANGED_DATE
		) VALUES (
			MCZBASE.SQ_ANNOTATION_HISTORY_ID.NEXTVAL,
			p_annotation_id,
			p_event_type,
			p_changed_table,
			p_changed_field,
			p_old_value,
			p_new_value,
			v_changed_by_username,
			v_changed_by_agent_id,
			v_changed_date
		);
	END;
BEGIN
	IF INSERTING THEN
		initialize_actor_for_insert();

		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'ANNOTATION_ID', NULL, TO_CHAR(:NEW.ANNOTATION_ID));
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'TARGET_TABLE', NULL, :NEW.TARGET_TABLE);
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'TARGET_PRIMARY_KEY', NULL, TO_CHAR(:NEW.TARGET_PRIMARY_KEY));
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'MOTIVATION', NULL, :NEW.MOTIVATION);
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'STATE', NULL, :NEW.STATE);
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'RESOLUTION', NULL, :NEW.RESOLUTION);
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'REVIEWED_FG', NULL, TO_CHAR(:NEW.REVIEWED_FG));
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'MASK_ANNOTATION_FG', NULL, TO_CHAR(:NEW.MASK_ANNOTATION_FG));
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'CF_USERNAME', NULL, :NEW.CF_USERNAME);
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'ANNOTATOR_AGENT_ID', NULL, TO_CHAR(:NEW.ANNOTATOR_AGENT_ID));
		log_history(:NEW.ANNOTATION_ID, 'CREATE', 'ANNOTATIONS', 'REVIEWER_AGENT_ID', NULL, TO_CHAR(:NEW.REVIEWER_AGENT_ID));

	ELSIF UPDATING THEN
		initialize_actor_for_update();

		IF NVL(:OLD.TARGET_TABLE, '{NULL}') <> NVL(:NEW.TARGET_TABLE, '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'TARGET_TABLE', :OLD.TARGET_TABLE, :NEW.TARGET_TABLE);
		END IF;

		IF NVL(TO_CHAR(:OLD.TARGET_PRIMARY_KEY), '{NULL}') <> NVL(TO_CHAR(:NEW.TARGET_PRIMARY_KEY), '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'TARGET_PRIMARY_KEY', TO_CHAR(:OLD.TARGET_PRIMARY_KEY), TO_CHAR(:NEW.TARGET_PRIMARY_KEY));
		END IF;

		IF NVL(:OLD.MOTIVATION, '{NULL}') <> NVL(:NEW.MOTIVATION, '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'MOTIVATION', :OLD.MOTIVATION, :NEW.MOTIVATION);
		END IF;

		IF NVL(:OLD.STATE, '{NULL}') <> NVL(:NEW.STATE, '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'STATE', :OLD.STATE, :NEW.STATE);
		END IF;

		IF NVL(:OLD.RESOLUTION, '{NULL}') <> NVL(:NEW.RESOLUTION, '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'RESOLUTION', :OLD.RESOLUTION, :NEW.RESOLUTION);
		END IF;

		IF NVL(TO_CHAR(:OLD.REVIEWED_FG), '{NULL}') <> NVL(TO_CHAR(:NEW.REVIEWED_FG), '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'REVIEWED_FG', TO_CHAR(:OLD.REVIEWED_FG), TO_CHAR(:NEW.REVIEWED_FG));
		END IF;

		IF NVL(TO_CHAR(:OLD.MASK_ANNOTATION_FG), '{NULL}') <> NVL(TO_CHAR(:NEW.MASK_ANNOTATION_FG), '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'MASK_ANNOTATION_FG', TO_CHAR(:OLD.MASK_ANNOTATION_FG), TO_CHAR(:NEW.MASK_ANNOTATION_FG));
		END IF;

		IF NVL(:OLD.CF_USERNAME, '{NULL}') <> NVL(:NEW.CF_USERNAME, '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'CF_USERNAME', :OLD.CF_USERNAME, :NEW.CF_USERNAME);
		END IF;

		IF NVL(TO_CHAR(:OLD.ANNOTATOR_AGENT_ID), '{NULL}') <> NVL(TO_CHAR(:NEW.ANNOTATOR_AGENT_ID), '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'ANNOTATOR_AGENT_ID', TO_CHAR(:OLD.ANNOTATOR_AGENT_ID), TO_CHAR(:NEW.ANNOTATOR_AGENT_ID));
		END IF;

		IF NVL(TO_CHAR(:OLD.REVIEWER_AGENT_ID), '{NULL}') <> NVL(TO_CHAR(:NEW.REVIEWER_AGENT_ID), '{NULL}') THEN
			log_history(:NEW.ANNOTATION_ID, 'UPDATE', 'ANNOTATIONS', 'REVIEWER_AGENT_ID', TO_CHAR(:OLD.REVIEWER_AGENT_ID), TO_CHAR(:NEW.REVIEWER_AGENT_ID));
		END IF;

	ELSIF DELETING THEN
		initialize_actor_for_delete();
		log_history(:OLD.ANNOTATION_ID, 'DELETE', 'ANNOTATIONS', 'ANNOTATION_ID', TO_CHAR(:OLD.ANNOTATION_ID), NULL);
	END IF;
END;

ALTER TRIGGER "TR_ANNOTATIONS_HISTORY" ENABLE