
  CREATE OR REPLACE EDITIONABLE TRIGGER "TR_ANNOTATIONS_SET_LAST_UPDATED_DATE" 
BEFORE INSERT OR UPDATE
ON MCZBASE.ANNOTATIONS
FOR EACH ROW
BEGIN
	IF INSERTING THEN
		IF :NEW.LAST_UPDATED_DATE IS NULL THEN
			:NEW.LAST_UPDATED_DATE := SYSDATE;
		END IF;
	ELSIF UPDATING THEN
		:NEW.LAST_UPDATED_DATE := SYSDATE;
	END IF;
END;

ALTER TRIGGER "TR_ANNOTATIONS_SET_LAST_UPDATED_DATE" ENABLE