
  CREATE OR REPLACE TRIGGER "TR_BIOL_INDIV_RELATIONS_ID_SQ" BEFORE INSERT ON BIOL_INDIV_RELATIONS
FOR EACH ROW
BEGIN
    IF :NEW.BIOL_INDIV_RELATIONS_ID IS NULL THEN
        SELECT sq_BIOL_INDIV_RELATIONS_ID.nextval
        INTO :new.BIOL_INDIV_RELATIONS_ID FROM dual;
    END IF;
END;
ALTER TRIGGER "TR_BIOL_INDIV_RELATIONS_ID_SQ" ENABLE