
  CREATE OR REPLACE TRIGGER "TR_COLLECTION_AU_FLAT" 
AFTER UPDATE ON collection
FOR EACH ROW
BEGIN
UPDATE flat
SET stale_flag = 1
    WHERE collection_id = :OLD.collection_id;
END;

ALTER TRIGGER "TR_COLLECTION_AU_FLAT" ENABLE