
  CREATE OR REPLACE EDITIONABLE TRIGGER "TR_ELECTRONIC_ADDRESS_PK" 
before insert on MCZBASE.ELECTRONIC_ADDRESS 
for each row 
begin  
   select MCZBASE.SQ_ELECTRONIC_ADDRESS_ID.nextval into :NEW.ELECTRONIC_ADDRESS_ID from dual; 
end;

ALTER TRIGGER "TR_ELECTRONIC_ADDRESS_PK" ENABLE