
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRANS_AGENT_ROLE_RESTRICTIONS" 
BEFORE INSERT ON MCZBASE.TRANS_AGENT_ROLE_ALLOWED 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TRANS_AGENT_ROLE_ALLOWED_ID IS NULL THEN
      SELECT TRANS_AGENT_ROLE_RESTRICTIONS.NEXTVAL INTO :NEW.TRANS_AGENT_ROLE_ALLOWED_ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

ALTER TRIGGER "TRANS_AGENT_ROLE_RESTRICTIONS" ENABLE