
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ACTIVITY_ID" 
BEFORE INSERT OR UPDATE ON CF_DATABASE_ACTIVITY
FOR EACH ROW
DECLARE
    iCounter CF_DATABASE_ACTIVITY.ACTIVITY_ID%TYPE;
    cannot_change_counter EXCEPTION;
BEGIN
    IF INSERTING THEN
        SELECT SEQ_ACTIVITY_ID.NEXTVAL INTO iCounter FROM Dual;
        :NEW.ACTIVITY_ID := iCounter;
    END IF;
    IF UPDATING THEN
        IF NOT (:NEW.ACTIVITY_ID = :OLD.ACTIVITY_ID) THEN
            RAISE cannot_change_counter;
        END IF;
    END IF;
EXCEPTION
     WHEN cannot_change_counter THEN
         RAISE_APPLICATION_ERROR(-20000, 'Cannot Change Counter Value');
END;




ALTER TRIGGER "TRG_ACTIVITY_ID" ENABLE