
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_KEY_ANNOTATION_TEXTUALBODY" 
	BEFORE INSERT OR UPDATE ON "MCZBASE"."ANNOTATION_TEXTUALBODY"
	FOR EACH ROW
BEGIN
	IF :NEW."ANNOTATION_TEXTUALBODY_ID" IS NULL THEN
		SELECT "MCZBASE"."SQ_ANNOTATION_TEXTUALBODY_ID".NEXTVAL
		INTO :NEW."ANNOTATION_TEXTUALBODY_ID"
		FROM DUAL;
	END IF;
END;

ALTER TRIGGER "TRG_KEY_ANNOTATION_TEXTUALBODY" ENABLE