
  CREATE OR REPLACE TRIGGER "TRG_UNDERSCORE_COLLECTION" 
BEFORE INSERT ON MCZBASE.UNDERSCORE_COLLECTION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.UNDERSCORE_COLLECTION_ID IS NULL THEN
      SELECT SQ_UNDERSCORE_COLLECTION.NEXTVAL INTO :NEW.UNDERSCORE_COLLECTION_ID FROM SYS.DUAL;
          END IF;
  END COLUMN_SEQUENCES;
END;
ALTER TRIGGER "TRG_UNDERSCORE_COLLECTION" ENABLE