
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_TAXON_AUTHOR_BI" 
BEFORE INSERT ON MCZBASE.TAXON_AUTHOR
FOR EACH ROW
BEGIN
  IF :NEW.TAXON_AUTHOR_ID IS NULL THEN
    SELECT MCZBASE.TAXON_AUTHOR_SEQ.NEXTVAL INTO :NEW.TAXON_AUTHOR_ID FROM dual;
  END IF;
END;

ALTER TRIGGER "TRG_TAXON_AUTHOR_BI" ENABLE