
  CREATE OR REPLACE EDITIONABLE TRIGGER "TRG_ANN_SET_ANNOTATOR_AGENT" 
	BEFORE INSERT ON "MCZBASE"."ANNOTATIONS"
	FOR EACH ROW
DECLARE
	l_agent_id "MCZBASE"."AGENT"."AGENT_ID"%TYPE;
BEGIN
	IF :NEW."ANNOTATOR_AGENT_ID" IS NULL
		AND :NEW."CF_USERNAME" IS NOT NULL
		AND LENGTH(TRIM(:NEW."CF_USERNAME")) > 0
	THEN
		BEGIN
			SELECT MIN(an."AGENT_ID")
			INTO l_agent_id
			FROM "MCZBASE"."AGENT_NAME" an
			WHERE an."AGENT_NAME_TYPE" = 'login'
				AND an."AGENT_NAME" = :NEW."CF_USERNAME";

			:NEW."ANNOTATOR_AGENT_ID" := l_agent_id;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN
				NULL; -- leave :NEW.ANNOTATOR_AGENT_ID as null
			WHEN TOO_MANY_ROWS THEN
				-- MIN() prevents this, but keep defensive behavior.
				NULL;
		END;
	END IF;
END;

ALTER TRIGGER "TRG_ANN_SET_ANNOTATOR_AGENT" ENABLE