
  CREATE OR REPLACE TRIGGER "TRG_UNDERSCORE_COLL_CITATION" 
BEFORE INSERT ON MCZBASE.UNDERSCORE_COLLECTION_CITATION
FOR EACH ROW 
declare 
agentID agent.agent_id%type;
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.UNDERSCORE_COLL_CITATION_ID IS NULL THEN
      SELECT SQ_UNDERSCORE_COLL_CITATION_ID.NEXTVAL INTO :NEW.UNDERSCORE_COLL_CITATION_ID FROM SYS.DUAL;
      select agent_id into agentID from agent_name where upper(agent_name) = SYS_CONTEXT('USERENV','SESSION_USER') and agent_name_type = 'login';
      :NEW.CREATED_BY_AGENT_ID := agentID;
    END IF;
  END COLUMN_SEQUENCES;
END;
ALTER TRIGGER "TRG_UNDERSCORE_COLL_CITATION" ENABLE