
  CREATE OR REPLACE EDITIONABLE TRIGGER "UNDERSCORE_RELATION_TRG" 
BEFORE INSERT ON MCZBASE.UNDERSCORE_RELATION 
FOR EACH ROW 
BEGIN
      if :NEW.UNDERSCORE_RELATION_ID is null then
         select MCZBASE.UNDERSCORE_RELATIONS_SEQ.nextval into :new.UNDERSCORE_RELATION_ID from dual;
      end if;
END;

ALTER TRIGGER "UNDERSCORE_RELATION_TRG" ENABLE