
  CREATE TABLE "ACCN" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"ACCN_TYPE" VARCHAR2(35 CHAR) NOT NULL ENABLE, 
	"ACCN_NUM_PREFIX" VARCHAR2(10 CHAR), 
	"ACCN_NUM" NUMBER, 
	"ACCN_NUM_SUFFIX" VARCHAR2(4 CHAR), 
	"RECEIVED_DATE_TEXT" VARCHAR2(25 CHAR), 
	"ACCN_STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ESTIMATED_COUNT" NUMBER(22,0), 
	"RECEIVED_DATE" DATE, 
	"ACCN_NUMBER" VARCHAR2(60 CHAR) DEFAULT 'X' NOT NULL ENABLE, 
	 CONSTRAINT "PK_ACCN" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTACCN_STATUS" FOREIGN KEY ("ACCN_STATUS")
	  REFERENCES "CTACCN_STATUS" ("ACCN_STATUS") ENABLE, 
	 CONSTRAINT "FK_CTACCN_TYPE" FOREIGN KEY ("ACCN_TYPE")
	  REFERENCES "CTACCN_TYPE" ("ACCN_TYPE") ENABLE, 
	 CONSTRAINT "FK_ACCN_TRANS" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE
   ) 