
  CREATE TABLE "ACCN" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"ACCN_TYPE" VARCHAR2(35 CHAR) NOT NULL ENABLE, 
	"ACCN_NUM_PREFIX" VARCHAR2(10 CHAR), 
	"ACCN_NUM" NUMBER, 
	"ACCN_NUM_SUFFIX" VARCHAR2(4 CHAR), 
	"RECEIVED_DATE_TEXT" VARCHAR2(25 CHAR), 
	"ACCN_STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ESTIMATED_COUNT" NUMBER(22,0), 
	"RECEIVED_DATE" DATE, 
	"ACCN_NUMBER" VARCHAR2(60 CHAR) DEFAULT 'X' NOT NULL ENABLE, 
	 CONSTRAINT "FK_CTACCN_STATUS" FOREIGN KEY ("ACCN_STATUS")
	  REFERENCES "CTACCN_STATUS" ("ACCN_STATUS") ENABLE, 
	 CONSTRAINT "FK_CTACCN_TYPE" FOREIGN KEY ("ACCN_TYPE")
	  REFERENCES "CTACCN_TYPE" ("ACCN_TYPE") ENABLE, 
	 CONSTRAINT "FK_ACCN_TRANS" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_ACCN_TRANS_ID" ON "ACCN" ("TRANSACTION_ID") 
  
ALTER TABLE "ACCN" ADD CONSTRAINT "PK_ACCN" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX "PK_ACCN_TRANS_ID"  ENABLE;
COMMENT ON TABLE "ACCN" IS 'Subtype of Transaction (TRANS) in which the institution takes legal legal ownership or stewardship of material.';
COMMENT ON COLUMN "ACCN"."TRANSACTION_ID" IS 'Dependent key.';
COMMENT ON COLUMN "ACCN"."ACCN_TYPE" IS 'The type of the accession';
COMMENT ON COLUMN "ACCN"."ACCN_NUM_PREFIX" IS 'Deprecated';
COMMENT ON COLUMN "ACCN"."ACCN_NUM" IS 'Deprecated, use accn_number';
COMMENT ON COLUMN "ACCN"."ACCN_NUM_SUFFIX" IS 'Deprecated';
COMMENT ON COLUMN "ACCN"."RECEIVED_DATE_TEXT" IS 'The date on which this accession was recieved as text.';
COMMENT ON COLUMN "ACCN"."ACCN_STATUS" IS 'The status of this accession.';
COMMENT ON COLUMN "ACCN"."ESTIMATED_COUNT" IS 'An estimate of the number of collection objects in this accession.  Domain: integers';
COMMENT ON COLUMN "ACCN"."RECEIVED_DATE" IS 'The date on which the material in this accession was received.';
COMMENT ON COLUMN "ACCN"."ACCN_NUMBER" IS 'The accession number.  Domain: integers';
