
  CREATE TABLE "ADDR" 
   (	"ADDR_ID" NUMBER NOT NULL ENABLE, 
	"STREET_ADDR1" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"STREET_ADDR2" VARCHAR2(255 CHAR), 
	"CITY" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"STATE" VARCHAR2(50), 
	"ZIP" VARCHAR2(20 CHAR), 
	"COUNTRY_CDE" VARCHAR2(50 CHAR), 
	"MAIL_STOP" VARCHAR2(20 CHAR), 
	"FORMATTED_ADDR" VARCHAR2(510 CHAR), 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"ADDR_TYPE" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"JOB_TITLE" VARCHAR2(60 CHAR), 
	"VALID_ADDR_FG" NUMBER NOT NULL ENABLE, 
	"ADDR_REMARKS" VARCHAR2(255 CHAR), 
	"INSTITUTION" VARCHAR2(255 CHAR), 
	"DEPARTMENT" VARCHAR2(255 CHAR), 
	 CONSTRAINT "FK_CTADDR_TYPE" FOREIGN KEY ("ADDR_TYPE")
	  REFERENCES "CTADDR_TYPE" ("ADDR_TYPE") ENABLE, 
	 CONSTRAINT "FK_ADDR_AGENT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_ADDR" ON "ADDR" ("ADDR_ID") 
  
ALTER TABLE "ADDR" ADD CONSTRAINT "PK_ADDR" PRIMARY KEY ("ADDR_ID")
  USING INDEX "PKEY_ADDR"  ENABLE