
  CREATE TABLE "AGENT_RANK" 
   (	"AGENT_RANK_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_RANK" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"RANKED_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"REMARK" VARCHAR2(255 CHAR), 
	"TRANSACTION_TYPE" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"RANK_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "FK_AR_TRANSTYPE" FOREIGN KEY ("TRANSACTION_TYPE")
	  REFERENCES "CTTRANSACTION_TYPE" ("TRANSACTION_TYPE") ENABLE, 
	 CONSTRAINT "FK_AGENT_RANK_AGENT_ID" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_AR_RANKED_BY" FOREIGN KEY ("RANKED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 