
  CREATE TABLE "AGENT_NAME" 
   (	"AGENT_NAME_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_NAME_TYPE" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"DONOR_CARD_PRESENT_FG" NUMBER, 
	"AGENT_NAME" VARCHAR2(184 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_AGENT_NAME" PRIMARY KEY ("AGENT_NAME_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTAGENT_NAME_TYPE" FOREIGN KEY ("AGENT_NAME_TYPE")
	  REFERENCES "CTAGENT_NAME_TYPE" ("AGENT_NAME_TYPE") ENABLE, 
	 CONSTRAINT "FK_AGENTNAME_AGENT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 