
  CREATE TABLE "AGENT_RANK" 
   (	"AGENT_RANK_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_RANK" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"RANKED_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"REMARK" VARCHAR2(255 CHAR), 
	"TRANSACTION_TYPE" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"RANK_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "FK_AR_TRANSTYPE" FOREIGN KEY ("TRANSACTION_TYPE")
	  REFERENCES "CTTRANSACTION_TYPE" ("TRANSACTION_TYPE") ENABLE
   ) 