
  CREATE TABLE "AGENT_NAME_PENDING_DELETE" 
   (	"AGENT_NAME_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_NAME_TYPE" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"AGENT_NAME" VARCHAR2(184 CHAR) NOT NULL ENABLE
   ) ;
