
  CREATE TABLE "AGENT_RELATIONS" 
   (	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"RELATED_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_RELATIONSHIP" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"DATE_TO_MERGE" DATE, 
	"ON_HOLD" VARCHAR2(1 CHAR), 
	"HELD_BY" VARCHAR2(4000 CHAR), 
	"AGENT_REMARKS" VARCHAR2(250 CHAR), 
	"CREATED_BY" VARCHAR2(50), 
	 CONSTRAINT "PK_AGENT_RELATIONS" PRIMARY KEY ("AGENT_ID", "RELATED_AGENT_ID", "AGENT_RELATIONSHIP")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTAGENT_RELATIONSHIP" FOREIGN KEY ("AGENT_RELATIONSHIP")
	  REFERENCES "CTAGENT_RELATIONSHIP" ("AGENT_RELATIONSHIP") ENABLE
   ) 