
  CREATE TABLE "AGENT_NAME" 
   (	"AGENT_NAME_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_NAME_TYPE" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"DONOR_CARD_PRESENT_FG" NUMBER, 
	"AGENT_NAME" VARCHAR2(184 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "FK_CTAGENT_NAME_TYPE" FOREIGN KEY ("AGENT_NAME_TYPE")
	  REFERENCES "CTAGENT_NAME_TYPE" ("AGENT_NAME_TYPE") ENABLE, 
	 CONSTRAINT "FK_AGENTNAME_AGENT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_AGENT_NAME_ID" ON "AGENT_NAME" ("AGENT_NAME_ID") 
  
ALTER TABLE "AGENT_NAME" ADD CONSTRAINT "PK_AGENT_NAME" PRIMARY KEY ("AGENT_NAME_ID")
  USING INDEX "PK_AGENT_NAME_ID"  ENABLE;
COMMENT ON TABLE "AGENT_NAME" IS 'A name, in a specified form, of an agent.';
COMMENT ON COLUMN "AGENT_NAME"."AGENT_NAME_ID" IS 'Surrogate numeric primary key';
COMMENT ON COLUMN "AGENT_NAME"."AGENT_ID" IS 'FK for agent to which this name belongs.
';
COMMENT ON COLUMN "AGENT_NAME"."AGENT_NAME_TYPE" IS 'The type of name';
COMMENT ON COLUMN "AGENT_NAME"."DONOR_CARD_PRESENT_FG" IS 'Deprecated.  If 0, likely indicates creation of agent name through coldfusion code.';
COMMENT ON COLUMN "AGENT_NAME"."AGENT_NAME" IS 'The value of the name';
