
  CREATE TABLE "ANNOTATIONS" 
   (	"ANNOTATION_ID" NUMBER NOT NULL ENABLE, 
	"ANNOTATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CF_USERNAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"TAXON_NAME_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"PUBLICATION_ID" NUMBER, 
	"ANNOTATION" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"REVIEWER_AGENT_ID" NUMBER, 
	"REVIEWED_FG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"REVIEWER_COMMENT" VARCHAR2(4000 CHAR), 
	"TARGET_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"TARGET_PRIMARY_KEY" NUMBER NOT NULL ENABLE, 
	"STATE" VARCHAR2(50) DEFAULT 'New' NOT NULL ENABLE, 
	"RESOLUTION" VARCHAR2(50), 
	"MOTIVATION" VARCHAR2(20) DEFAULT 'commenting', 
	"TARGET_IRI" VARCHAR2(4000), 
	"ANNOTATOR_AGENT_ID" NUMBER, 
	"MASK_ANNOTATION_FG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"LAST_UPDATED_BY_AGENT_ID" NUMBER, 
	"LAST_UPDATED_DATE" DATE, 
	 CONSTRAINT "ANNOTATIONS_PK" PRIMARY KEY ("ANNOTATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ANNOTATIONS_FK1" FOREIGN KEY ("MOTIVATION")
	  REFERENCES "CTMOTIVATION" ("MOTIVATION") ENABLE, 
	 CONSTRAINT "FK_ANNOTATIONS_REVEWER_AGENT" FOREIGN KEY ("REVIEWER_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_ANNOTATIONS_ANNOTATOR_AGENT" FOREIGN KEY ("ANNOTATOR_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "ANNOTATIONS_FK2" FOREIGN KEY ("TARGET_TABLE")
	  REFERENCES "CTANNOTATION_TARGET_TABLE" ("ANNOTATION_TARGET_TABLE") ENABLE, 
	 CONSTRAINT "FK_ANNOTATIONS_LAST_UPDATED_BY_AGENT" FOREIGN KEY ("LAST_UPDATED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) ;
COMMENT ON TABLE "ANNOTATIONS" IS 'Annotations on MCZbase data objects.  Needs alignment with W3C annotation data model, and helios bug tracker ontology.';
COMMENT ON COLUMN "ANNOTATIONS"."TARGET_IRI" IS 'Resolvable IRI for the entity to which the annotation applies (W3C Web Annotation target/source).';
COMMENT ON COLUMN "ANNOTATIONS"."ANNOTATOR_AGENT_ID" IS 'Annotator as MCZBASE.AGENT.AGENT_ID (creator of the annotation), complementary to CF_USERNAME for users that have an agent record; may be set by trigger from CF_USERNAME.';
COMMENT ON COLUMN "ANNOTATIONS"."MASK_ANNOTATION_FG" IS 'Visibility of the annotation record.  0=public, 1=hidden. Flag to suppress display of annotation content from public users; parallels media masking semantics.';
COMMENT ON COLUMN "ANNOTATIONS"."LAST_UPDATED_BY_AGENT_ID" IS 'Agent responsible for the most recent application-level update to this annotation row, provided by the application.';
COMMENT ON COLUMN "ANNOTATIONS"."LAST_UPDATED_DATE" IS 'Date/time of the most recent update to this annotation row.';
COMMENT ON COLUMN "ANNOTATIONS"."ANNOTATION_ID" IS 'Surrogate numeric primary key';
COMMENT ON COLUMN "ANNOTATIONS"."ANNOTATE_DATE" IS 'Date the annotation was created.';
COMMENT ON COLUMN "ANNOTATIONS"."CF_USERNAME" IS 'user who created the annotation';
COMMENT ON COLUMN "ANNOTATIONS"."COLLECTION_OBJECT_ID" IS 'Deprecated';
COMMENT ON COLUMN "ANNOTATIONS"."TAXON_NAME_ID" IS 'Deprecated';
COMMENT ON COLUMN "ANNOTATIONS"."PROJECT_ID" IS 'Deprecated';
COMMENT ON COLUMN "ANNOTATIONS"."PUBLICATION_ID" IS 'Deprecated';
COMMENT ON COLUMN "ANNOTATIONS"."REVIEWER_COMMENT" IS 'Deprecated, split into response annotations.';
COMMENT ON COLUMN "ANNOTATIONS"."TARGET_TABLE" IS 'Entity to which the annotation applies.';
COMMENT ON COLUMN "ANNOTATIONS"."TARGET_PRIMARY_KEY" IS 'primary key value in the target table for the record to which the annotation applies.';
COMMENT ON COLUMN "ANNOTATIONS"."STATE" IS 'oslc_cm::State of the annotation';
COMMENT ON COLUMN "ANNOTATIONS"."RESOLUTION" IS 'bom:Resolution of the annotation';
COMMENT ON COLUMN "ANNOTATIONS"."MOTIVATION" IS 'anno:Motivation instance';
