
  CREATE TABLE "ANNOTATION_TEXTUALBODY" 
   (	"ANNOTATION_TEXTUALBODY_ID" NUMBER NOT NULL ENABLE, 
	"ANNOTATION_ID" NUMBER NOT NULL ENABLE, 
	"BODY_VALUE" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"BODY_FORMAT" VARCHAR2(255) DEFAULT 'text/plain' NOT NULL ENABLE, 
	"BODY_LANGUAGE" VARCHAR2(35), 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY_AGENT_ID" NUMBER, 
	"LAST_UPDATED_DATE" DATE, 
	 CONSTRAINT "PK_ANNOTATION_TEXTUALBODY" PRIMARY KEY ("ANNOTATION_TEXTUALBODY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_ATB_ANNOTATION" FOREIGN KEY ("ANNOTATION_ID")
	  REFERENCES "ANNOTATIONS" ("ANNOTATION_ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FK_ANNOT_TEXTBODY_LAST_UPDATED_BY_AGENT" FOREIGN KEY ("LAST_UPDATED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) ;
COMMENT ON TABLE "ANNOTATION_TEXTUALBODY" IS 'W3C Web Annotation embedded TextualBody resources associated with MCZBASE.ANNOTATIONS.';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."LAST_UPDATED_BY_AGENT_ID" IS 'Agent responsible for the most recent application-level update to this annotation textual body row, provided by the application.';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."LAST_UPDATED_DATE" IS 'Date/time of the most recent update to this annotation textual body row.';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."ANNOTATION_TEXTUALBODY_ID" IS 'Surrogate primary key for the embedded textual body.  Automatic, from sequence by trigger.';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."ANNOTATION_ID" IS 'FK to MCZBASE.ANNOTATIONS.ANNOTATION_ID for the parent annotation.';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."BODY_VALUE" IS 'Text content of the embedded body (WA: value).';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."BODY_FORMAT" IS 'Media type of the body content (WA: format), e.g., text/plain or text/html.';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."BODY_LANGUAGE" IS 'Language tag for the body content (WA: language), e.g., en, fr, pt-BR.';
COMMENT ON COLUMN "ANNOTATION_TEXTUALBODY"."CREATED_DATE" IS 'Date the body row was created.';
