
  CREATE TABLE "ANNOTATIONS" 
   (	"ANNOTATION_ID" NUMBER NOT NULL ENABLE, 
	"ANNOTATE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CF_USERNAME" VARCHAR2(255 CHAR), 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"TAXON_NAME_ID" NUMBER, 
	"PROJECT_ID" NUMBER, 
	"PUBLICATION_ID" NUMBER, 
	"ANNOTATION" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"REVIEWER_AGENT_ID" NUMBER, 
	"REVIEWED_FG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"REVIEWER_COMMENT" VARCHAR2(4000 CHAR), 
	"TARGET_TABLE" VARCHAR2(255), 
	"TARGET_PRIMARY_KEY" NUMBER, 
	"STATE" VARCHAR2(50) DEFAULT 'New' NOT NULL ENABLE, 
	"RESOLUTION" VARCHAR2(50), 
	"MOTIVATION" VARCHAR2(20) DEFAULT 'commenting', 
	 CONSTRAINT "ANNOTATIONS_PK" PRIMARY KEY ("ANNOTATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ANNOTATIONS_FK1" FOREIGN KEY ("MOTIVATION")
	  REFERENCES "CTMOTIVATION" ("MOTIVATION") ENABLE, 
	 CONSTRAINT "FK_ANNOTATIONS_REVEWER_AGENT" FOREIGN KEY ("REVIEWER_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 