
  CREATE TABLE "ATTRIBUTES" 
   (	"ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"DETERMINED_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"ATTRIBUTE_TYPE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"ATTRIBUTE_VALUE" VARCHAR2(4000) NOT NULL ENABLE, 
	"ATTRIBUTE_UNITS" VARCHAR2(60 CHAR), 
	"ATTRIBUTE_REMARK" VARCHAR2(255 CHAR), 
	"DETERMINED_DATE" DATE, 
	"DETERMINATION_METHOD" VARCHAR2(255 CHAR), 
	"NOS_MODIFIER" VARCHAR2(20), 
	"NOS_VALUE" NUMBER, 
	"NOS_INCLUDE_FG" NUMBER, 
	 CONSTRAINT "PK_ATTRIBUTES" PRIMARY KEY ("ATTRIBUTE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_ATTRIBUTES_CATITEM" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_ATTRIBUTES_AGENT" FOREIGN KEY ("DETERMINED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   )  ENABLE ROW MOVEMENT 