
  CREATE TABLE "BAD_TAXONOMY" 
   (	"TAXON_NAME_ID" NUMBER, 
	"SCIENTIFIC_NAME" VARCHAR2(110), 
	"ERROR_TEXT" VARCHAR2(100), 
	"FIXED" VARCHAR2(1), 
	"ERROR_TYPE" VARCHAR2(30), 
	"HERP" VARCHAR2(2), 
	"MAMM" VARCHAR2(2), 
	"MALA" VARCHAR2(2), 
	"FISH" VARCHAR2(2), 
	"BIRD" VARCHAR2(2), 
	"VP" VARCHAR2(2), 
	"IP" VARCHAR2(2), 
	"IZ" VARCHAR2(2), 
	"ENT" VARCHAR2(2), 
	"SC" VARCHAR2(2)
   ) 