
  CREATE TABLE "BIOL_INDIV_RELATIONS" 
   (	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"RELATED_COLL_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"BIOL_INDIV_RELATIONSHIP" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"BIOL_INDIV_RELATION_REMARKS" VARCHAR2(4000), 
	"CREATED_BY" VARCHAR2(50), 
	"BIOL_INDIV_RELATIONS_ID" NUMBER, 
	 CONSTRAINT "PK_BIOL_INDIV_RELATIONS" PRIMARY KEY ("COLLECTION_OBJECT_ID", "RELATED_COLL_OBJECT_ID", "BIOL_INDIV_RELATIONSHIP")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTBIOL_RELATIONS" FOREIGN KEY ("BIOL_INDIV_RELATIONSHIP")
	  REFERENCES "CTBIOL_RELATIONS" ("BIOL_INDIV_RELATIONSHIP") ENABLE, 
	 CONSTRAINT "FK_BIOLINDIVRELN_CATITEM_COID" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_BIOLINDIVRELN_CATITEM_RCOID" FOREIGN KEY ("RELATED_COLL_OBJECT_ID")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE
   ) 