
  CREATE TABLE "BORROW" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"LENDERS_TRANS_NUM_CDE" VARCHAR2(20 CHAR), 
	"LENDERS_INVOICE_RETURNED_FG" NUMBER NOT NULL ENABLE, 
	"RECEIVED_DATE" DATE, 
	"DUE_DATE" DATE, 
	"LENDERS_LOAN_DATE" DATE, 
	"BORROW_STATUS" VARCHAR2(20 CHAR), 
	"LENDERS_INSTRUCTIONS" VARCHAR2(255 CHAR), 
	"LENDER_LOAN_TYPE" VARCHAR2(60 CHAR), 
	"BORROW_NUMBER" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"NO_OF_SPECIMENS" VARCHAR2(20 CHAR), 
	"DESCRIPTION_OF_BORROW" VARCHAR2(2000 CHAR), 
	"RETURN_ACKNOWLEDGED_DATE" DATE, 
	"RET_ACKNOWLEDGED_BY" VARCHAR2(50 CHAR), 
	 CONSTRAINT "PK_BORROW" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTBORROW_STATUS" FOREIGN KEY ("BORROW_STATUS")
	  REFERENCES "CTBORROW_STATUS" ("BORROW_STATUS") ENABLE
   ) 