
  CREATE TABLE "BORROW_ITEM" 
   (	"TRANSACTION_ID" NUMBER NOT NULL DISABLE, 
	"CATALOG_NUMBER" VARCHAR2(255 CHAR), 
	"SCI_NAME" VARCHAR2(255 CHAR), 
	"NO_OF_SPEC" VARCHAR2(20 CHAR), 
	"SPEC_PREP" VARCHAR2(100 CHAR), 
	"TYPE_STATUS" VARCHAR2(100 CHAR), 
	"COUNTRY_OF_ORIGIN" VARCHAR2(255 CHAR), 
	"OBJECT_REMARKS" VARCHAR2(2000 CHAR), 
	"BORROW_ITEM_ID" NUMBER
   ) 