
  CREATE TABLE "BULKLOADER_LEPIDOPTERA_MAP" 
   (	"SPECIMENID" NUMBER, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"COLLECTING_EVENT_ID" NUMBER, 
	"LOCALITY_ID" NUMBER, 
	"IMAGESLOADED" NUMBER DEFAULT 0, 
	"DETERLOADED" NUMBER DEFAULT 0, 
	"ERROR" VARCHAR2(1000 CHAR)
   ) 