
  CREATE TABLE "BULKLOADER_FIELD_ORDER" 
   (	"BULKLOADER_FIELD_ORDER_ID" NUMBER NOT NULL ENABLE, 
	"COLUMN_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER, 
	"SHOW" NUMBER DEFAULT 1, 
	"DEPARTMENT" VARCHAR2(20) DEFAULT 'All' NOT NULL ENABLE, 
	 CONSTRAINT "BULKLOADERFIELDORDER_PK" PRIMARY KEY ("BULKLOADER_FIELD_ORDER_ID")
  USING INDEX  ENABLE
   ) 