
  CREATE TABLE "BULKLOADER_KEYS" 
   (	"K_COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTING_EVENT_ID" NUMBER NOT NULL ENABLE, 
	"CATCOLLID" NUMBER NOT NULL ENABLE, 
	"ENTERED_PERSON_ID" NUMBER NOT NULL ENABLE, 
	"ACCN_ID" NUMBER NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"TAXA_FORMULA" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"ID_MADE_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"K_CAT_NUM" NUMBER NOT NULL ENABLE, 
	"COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"K_LOCALITY_ID" NUMBER NOT NULL ENABLE
   ) ;
