
  CREATE TABLE "CF_BUGS" 
   (	"BUG_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER, 
	"REPORTED_NAME" VARCHAR2(255 CHAR), 
	"FORM_NAME" VARCHAR2(4000), 
	"COMPLAINT" VARCHAR2(4000 CHAR), 
	"SUGGESTED_SOLUTION" VARCHAR2(4000 CHAR), 
	"ADMIN_SOLUTION" VARCHAR2(4000 CHAR), 
	"USER_PRIORITY" NUMBER, 
	"ADMIN_PRIORITY" NUMBER, 
	"USER_REMARKS" VARCHAR2(4000 CHAR), 
	"ADMIN_REMARKS" VARCHAR2(4000 CHAR), 
	"SOLVED_FG" NUMBER(1,0), 
	"USER_EMAIL" VARCHAR2(255 CHAR), 
	"SUBMISSION_DATE" DATE
   ) ;
