
  CREATE TABLE "CF_CANNED_SEARCH" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"SEARCH_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"URL" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"CANNED_ID" NUMBER NOT NULL ENABLE, 
	"EXECUTE" NUMBER DEFAULT 0
   ) 
  CREATE UNIQUE INDEX "PKEY_CF_CANNED_SEARCH" ON "CF_CANNED_SEARCH" ("CANNED_ID") 
  
ALTER TABLE "CF_CANNED_SEARCH" ADD CONSTRAINT "CF_CANNED_SEARCH_PK" PRIMARY KEY ("CANNED_ID")
  USING INDEX "PKEY_CF_CANNED_SEARCH"  ENABLE