
  CREATE TABLE "CF_COLLECTION" 
   (	"CF_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_ID" NUMBER, 
	"DBUSERNAME" VARCHAR2(34 CHAR), 
	"DBPWD" VARCHAR2(47 CHAR), 
	"HEADER_COLOR" VARCHAR2(20 CHAR), 
	"HEADER_IMAGE" VARCHAR2(255 CHAR), 
	"COLLECTION_URL" VARCHAR2(255 CHAR), 
	"COLLECTION_LINK_TEXT" VARCHAR2(255 CHAR), 
	"INSTITUTION_URL" VARCHAR2(255 CHAR), 
	"INSTITUTION_LINK_TEXT" VARCHAR2(60 CHAR), 
	"META_DESCRIPTION" VARCHAR2(255 CHAR), 
	"META_KEYWORDS" VARCHAR2(255 CHAR), 
	"STYLESHEET" VARCHAR2(60 CHAR), 
	"HEADER_CREDIT" CHAR(1 CHAR), 
	"PORTAL_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"COLLECTION" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"PUBLIC_PORTAL_FG" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "PK_CF_COLLECTION_ID" PRIMARY KEY ("CF_COLLECTION_ID")
  USING INDEX  ENABLE
   ) 