
  CREATE TABLE "CF_COLLECTION_APPEARANCE" 
   (	"COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"HEADER_COLOR" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"HEADER_IMAGE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLLECTION_URL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLLECTION_LINK_TEXT" VARCHAR2(150 CHAR) NOT NULL ENABLE, 
	"INSTITUTION_URL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"INSTITUTION_LINK_TEXT" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"META_DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"META_KEYWORDS" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"STYLESHEET" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"HEADER_CREDIT" VARCHAR2(255 CHAR), 
	 CONSTRAINT "FK_CFCOLLAPPEARANCE_COLLECTION" FOREIGN KEY ("COLLECTION_ID")
	  REFERENCES "COLLECTION" ("COLLECTION_ID") ENABLE
   ) ;
