
  CREATE TABLE "CF_DOWNLOAD" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"DOWNLOAD_PURPOSE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DOWNLOAD_DATE" DATE NOT NULL ENABLE, 
	"NUM_RECORDS" NUMBER NOT NULL ENABLE, 
	"AGREE_TO_TERMS" VARCHAR2(3 CHAR) NOT NULL ENABLE
   ) 