
  CREATE TABLE "CF_DOWNLOAD_FILE" 
   (	"CF_DOWNLOAD_FILE_ID" NUMBER NOT NULL ENABLE, 
	"TOKEN" VARCHAR2(50) NOT NULL ENABLE, 
	"RESULT_ID" VARCHAR2(50), 
	"USERNAME" VARCHAR2(30), 
	"STATUS" VARCHAR2(255), 
	"DOWNLOAD_PROFILE_ID" NUMBER, 
	"FILENAME" VARCHAR2(1000), 
	"TIME_CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"MESSAGE" VARCHAR2(4000), 
	 CONSTRAINT "CF_DOWNLOAD_FILE_PK" PRIMARY KEY ("CF_DOWNLOAD_FILE_ID")
  USING INDEX  ENABLE
   ) 