
  CREATE TABLE "CF_DATABASE_ACTIVITY" 
   (	"ACTIVITY_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"DATE_STAMP" DATE NOT NULL ENABLE, 
	"SQL_STATEMENT" VARCHAR2(4000 CHAR)
   ) ;
