
  CREATE TABLE "CF_GLOBAL_SETTINGS" 
   (	"GMAP_API_KEY" VARCHAR2(900 CHAR), 
	"GOOGLE_SITE_KEY" VARCHAR2(900 CHAR), 
	"GOOGLE_UACCT" VARCHAR2(900 CHAR), 
	"BUGZILLA_TO_EMAIL" VARCHAR2(255), 
	"BUGZILLA_FROM_EMAIL" VARCHAR2(255), 
	"GENBANK_PASSWORD" VARCHAR2(255), 
	"ALLOWED_PROFILE" VARCHAR2(50), 
	"ALLOWED_TABLESPACE" VARCHAR2(50), 
	"BUGZILLA_API_KEY" VARCHAR2(900), 
	"BUGZILLA_SERVER" VARCHAR2(255)
   ) 