
  CREATE TABLE "CF_GENBANK_CRAWL" 
   (	"GBCID" NUMBER NOT NULL ENABLE, 
	"OWNER" VARCHAR2(60 CHAR), 
	"LINK_URL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"FOUND_COUNT" NUMBER, 
	"QUERY_TYPE" VARCHAR2(30 CHAR), 
	"RUN_DATE" DATE DEFAULT sysdate
   ) 