
  CREATE TABLE "CF_GENBANK_INFO" 
   (	"GBI_ID" NUMBER NOT NULL ENABLE, 
	"CITATION" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"PUBINARCTOS" VARCHAR2(20 CHAR), 
	"CITATIONSINGENBANK" VARCHAR2(20 CHAR), 
	"CITATIONINPUBLICATION" VARCHAR2(20 CHAR), 
	"CITATIONSINARCTOS" VARCHAR2(20 CHAR), 
	"ARCTICLEATURL" VARCHAR2(4000 CHAR), 
	"COMMENTS" VARCHAR2(4000 CHAR), 
	"STATUS" VARCHAR2(20 CHAR)
   ) 