
  CREATE TABLE "CF_GEOG_CAT_ITEM_COUNTS" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"TARGET_TABLE" VARCHAR2(13) NOT NULL ENABLE, 
	"COLL_OBJ_COUNT" NUMBER, 
	"CONTINENT_OCEAN" VARCHAR2(70 CHAR), 
	"OCEAN_REGION" VARCHAR2(50 CHAR), 
	"COUNTRY" VARCHAR2(70 CHAR), 
	"ISLAND_GROUP" VARCHAR2(50 CHAR), 
	"ISLAND" VARCHAR2(50 CHAR), 
	 CONSTRAINT "CF_GEOG_CAT_ITEM_COUNTS_PK" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE
   ) ;
