
  CREATE TABLE "CF_GRID_PROPERTIES" 
   (	"CF_GRID_COLUMNS_VISIBILITY_ID" NUMBER NOT NULL ENABLE, 
	"PAGE_FILE_PATH" VARCHAR2(255) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
	"LABEL" VARCHAR2(20) DEFAULT 'Default' NOT NULL ENABLE, 
	"COLUMNHIDDENSETTINGS" CLOB DEFAULT '{}' NOT NULL ENABLE, 
	 CONSTRAINT "CF_GRID_PROPERTIES_PK" PRIMARY KEY ("CF_GRID_COLUMNS_VISIBILITY_ID")
  USING INDEX  ENABLE
   ) 