
  CREATE TABLE "CF_LOG" 
   (	"LOG_ID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(255 CHAR), 
	"TEMPLATE" VARCHAR2(255 CHAR), 
	"ACCESS_DATE" DATE, 
	"QUERY_STRING" VARCHAR2(4000 CHAR), 
	"REPORTED_COUNT" NUMBER, 
	"REFERRING_URL" VARCHAR2(4000 CHAR)
   ) 