
  CREATE TABLE "CF_LOAN" 
   (	"LOAN_ID" NUMBER NOT NULL ENABLE, 
	"TRANS_ID" NUMBER NOT NULL ENABLE, 
	"LOAN_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LOAN_DESCRIPTION" VARCHAR2(4000 CHAR), 
	"INSTRUCTIONS" VARCHAR2(4000 CHAR), 
	"TRANSACTION_ID" NUMBER
   ) ;
