
  CREATE TABLE "CF_LOAN_ITEM" 
   (	"USER_LOAN_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"REMARK" VARCHAR2(255 CHAR), 
	"USE_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"APPROVAL_STATUS" VARCHAR2(60 CHAR), 
	"ADMIN_REMARK" VARCHAR2(255 CHAR)
   ) 