
  CREATE TABLE "CF_LABEL" 
   (	"PART_ID" NUMBER NOT NULL ENABLE, 
	"CONTAINER_TYPE" VARCHAR2(60 CHAR), 
	"CAT_NUM" NUMBER NOT NULL ENABLE, 
	"COLLECTOR" VARCHAR2(255 CHAR), 
	"VERBATIM_DATE" VARCHAR2(60 CHAR), 
	"ORIGINAL_FIELD_NUMBER" VARCHAR2(255 CHAR), 
	"AF_NUMBER" VARCHAR2(15 CHAR), 
	"LAT_LONG" VARCHAR2(255 CHAR), 
	"SEX" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"MEAS" VARCHAR2(255 CHAR), 
	"LOCALITY" VARCHAR2(255 CHAR), 
	"SCIENTIFIC_NAME" VARCHAR2(255 CHAR), 
	"PART_NAME" VARCHAR2(60 CHAR), 
	"BARCODE" VARCHAR2(60 CHAR)
   ) 