
  CREATE TABLE "CF_PROJECT" 
   (	"TRANS_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PROJ_TITLE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PROJ_DESC" VARCHAR2(4000 CHAR), 
	"REMARKS" VARCHAR2(4000 CHAR), 
	"PROJECT_ID" NUMBER
   ) ;
