
  CREATE TABLE "CF_PUB_TYPE_ATTRIBUTE" 
   (	"CF_PUB_TYPE_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
	"PUBLICATION_TYPE" VARCHAR2(21) NOT NULL ENABLE, 
	"PUBLICATION_ATTRIBUTE" VARCHAR2(60) NOT NULL ENABLE, 
	"ORDINAL" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "CF_PUB_TYPE_ATTRIBUTE_PK" PRIMARY KEY ("CF_PUB_TYPE_ATTRIBUTE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CF_PUB_TYPE_ATTRIBUTE_FK1" FOREIGN KEY ("PUBLICATION_TYPE")
	  REFERENCES "CTPUBLICATION_TYPE" ("PUBLICATION_TYPE") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "CF_PUB_TYPE_ATTRIBUTE_FK2" FOREIGN KEY ("PUBLICATION_ATTRIBUTE")
	  REFERENCES "CTPUBLICATION_ATTRIBUTE" ("PUBLICATION_ATTRIBUTE") ON DELETE CASCADE ENABLE
   ) 
  CREATE INDEX "CF_PUB_TYPE_ATTRIBUTE_INDEX1" ON "CF_PUB_TYPE_ATTRIBUTE" ("PUBLICATION_TYPE", "PUBLICATION_ATTRIBUTE", "ORDINAL") 
  
ALTER TABLE "CF_PUB_TYPE_ATTRIBUTE" ADD CONSTRAINT "CF_PUB_TYPE_ATTRIBUTE_UK1" UNIQUE ("PUBLICATION_TYPE", "PUBLICATION_ATTRIBUTE")
  USING INDEX "CF_PUB_TYPE_ATTRIBUTE_INDEX1"  ENABLE;
COMMENT ON TABLE "CF_PUB_TYPE_ATTRIBUTE" IS 'Table to determine which publication attributes are shown on an edit publication form for a specified publication type.';
COMMENT ON COLUMN "CF_PUB_TYPE_ATTRIBUTE"."CF_PUB_TYPE_ATTRIBUTE_ID" IS 'Surrogate Numeric Primary Key';
COMMENT ON COLUMN "CF_PUB_TYPE_ATTRIBUTE"."PUBLICATION_TYPE" IS 'publication type that attribute applies to ';
COMMENT ON COLUMN "CF_PUB_TYPE_ATTRIBUTE"."PUBLICATION_ATTRIBUTE" IS 'attribute to be used with publication type';
COMMENT ON COLUMN "CF_PUB_TYPE_ATTRIBUTE"."ORDINAL" IS 'sort order for attributes on publication of type.';
