
  CREATE TABLE "CF_SEARCH_TERMS" 
   (	"TERM" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CODE_TABLE" VARCHAR2(60 CHAR), 
	"DEFINITION" VARCHAR2(255 CHAR)
   ) ;
