
  CREATE TABLE "CF_SPEC_RES_COLS" 
   (	"COLUMN_NAME" VARCHAR2(38 CHAR), 
	"SQL_ELEMENT" VARCHAR2(255 CHAR), 
	"CATEGORY" VARCHAR2(255 CHAR), 
	"CF_SPEC_RES_COLS_ID" NUMBER NOT NULL ENABLE, 
	"DISP_ORDER" NUMBER NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_CF_SPEC_RES_COLS" ON "CF_SPEC_RES_COLS" ("CF_SPEC_RES_COLS_ID") 
  
ALTER TABLE "CF_SPEC_RES_COLS" ADD CONSTRAINT "PK_CF_SPEC_RES_COLS" PRIMARY KEY ("CF_SPEC_RES_COLS_ID")
  USING INDEX "PK_CF_SPEC_RES_COLS"  ENABLE