
  CREATE TABLE "CF_SPEC_RES_COLS_R" 
   (	"COLUMN_NAME" VARCHAR2(38 CHAR) NOT NULL ENABLE, 
	"SQL_ELEMENT" VARCHAR2(255 CHAR), 
	"CATEGORY" VARCHAR2(255 CHAR), 
	"CF_SPEC_RES_COLS_ID" NUMBER NOT NULL ENABLE, 
	"DISP_ORDER" NUMBER NOT NULL ENABLE, 
	"LABEL" VARCHAR2(50), 
	"ACCESS_ROLE" VARCHAR2(20) DEFAULT 'PUBLIC', 
	"HIDEABLE" VARCHAR2(10) DEFAULT 'true', 
	"HIDDEN" VARCHAR2(10) DEFAULT 'true', 
	"CELLSRENDERER" VARCHAR2(255), 
	"WIDTH" NUMBER DEFAULT 100, 
	"DATA_TYPE" VARCHAR2(20) DEFAULT 'VARCHAR2', 
	"MINIMAL_FG" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "CF_SPEC_RES_COLS_R_PK" PRIMARY KEY ("CF_SPEC_RES_COLS_ID")
  USING INDEX  ENABLE
   ) 