
  CREATE TABLE "CF_TEMP_COLLECTING_EVENT" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"LOCALITY_ID" VARCHAR2(20), 
	"VERBATIM_DATE" VARCHAR2(60 CHAR), 
	"VERBATIM_LOCALITY" VARCHAR2(2000 CHAR), 
	"COLL_EVENT_REMARKS" VARCHAR2(4000 CHAR), 
	"VALID_DISTRIBUTION_FG" VARCHAR2(50 CHAR), 
	"COLLECTING_SOURCE" VARCHAR2(30 CHAR), 
	"COLLECTING_METHOD" VARCHAR2(255), 
	"HABITAT_DESC" VARCHAR2(500 CHAR), 
	"DATE_DETERMINED_BY_AGENT" VARCHAR2(255), 
	"DATE_DETERMINED_BY_AGENT_ID" NUMBER, 
	"FISH_FIELD_NUMBER" VARCHAR2(50 CHAR), 
	"BEGAN_DATE" VARCHAR2(22 CHAR), 
	"ENDED_DATE" VARCHAR2(22 CHAR), 
	"COLLECTING_TIME" VARCHAR2(50), 
	"VERBATIMCOORDINATES" VARCHAR2(100 CHAR), 
	"VERBATIMLATITUDE" VARCHAR2(50 CHAR), 
	"VERBATIMLONGITUDE" VARCHAR2(50 CHAR), 
	"VERBATIMCOORDINATESYSTEM" VARCHAR2(50 CHAR), 
	"VERBATIMSRS" VARCHAR2(50 CHAR), 
	"STARTDAYOFYEAR" VARCHAR2(50 CHAR), 
	"ENDDAYOFYEAR" VARCHAR2(50 CHAR), 
	"VERBATIMELEVATION" VARCHAR2(500), 
	"VERBATIMDEPTH" VARCHAR2(500), 
	"VERBATIM_COLLECTORS" VARCHAR2(2000), 
	"VERBATIM_FIELD_NUMBERS" VARCHAR2(500), 
	"VERBATIM_HABITAT" VARCHAR2(2000), 
	"USERNAME" VARCHAR2(1020) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(4000), 
	"SPEC_LOCALITY" VARCHAR2(400 CHAR)
   )   NO INMEMORY 
  CREATE UNIQUE INDEX "CF_TEMP_COLL_EVENT_PK" ON "CF_TEMP_COLLECTING_EVENT" ("KEY") 
  
ALTER TABLE "CF_TEMP_COLLECTING_EVENT" ADD CONSTRAINT "PK_CF_TEMP_COLLECTING_EVENT" PRIMARY KEY ("KEY")
  USING INDEX "CF_TEMP_COLL_EVENT_PK"  ENABLE