
  CREATE TABLE "CF_TEMP_LOAN" 
   (	"COLLECTION" VARCHAR2(50), 
	"LOAN_NUMBER" VARCHAR2(50), 
	"LOAN_TYPE" VARCHAR2(50), 
	"LOAN_STATUS" VARCHAR2(50), 
	"IN_HOUSE_AUTHORIZED_BY" VARCHAR2(255), 
	"RECIEVED_BY" VARCHAR2(255), 
	"IN_HOUSE_CONTACT" VARCHAR2(255), 
	"RECIPIENT_INSTITUTION" VARCHAR2(255), 
	"FOR_USE_BY" VARCHAR2(50), 
	"ADDITIONAL_OUTSIDE_CONTACT" VARCHAR2(50), 
	"TRANSACTION_DATE" VARCHAR2(50), 
	"RETURN_DUE_DATE" VARCHAR2(50), 
	"DATE_CLOSED" VARCHAR2(50), 
	"NATURE_OF_MATERIAL" VARCHAR2(4000), 
	"DESCRIPTION" VARCHAR2(4000), 
	"LOAN_INSTRUCTIONS" VARCHAR2(4000), 
	"INTERNAL_REMARKS" VARCHAR2(4000), 
	"MOVED" VARCHAR2(1), 
	"ID" NUMBER, 
	"ERROR" VARCHAR2(500), 
	"TRANSACTION_ID" NUMBER
   ) ;
