
  CREATE TABLE "CF_TEMP_MINOT" 
   (	"KEY" NUMBER, 
	"MEDIA_URI" VARCHAR2(255 CHAR), 
	"MIME_TYPE" VARCHAR2(255 CHAR), 
	"MEDIA_TYPE" VARCHAR2(255 CHAR), 
	"PREVIEW_URI" VARCHAR2(255 CHAR), 
	"MEDIA_RELATIONSHIPS" VARCHAR2(4000), 
	"MEDIA_LABELS" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(4000 CHAR), 
	"MEDIA_LICENSE_ID" NUMBER(22,0), 
	"MASK_MEDIA" NUMBER(1,0), 
	"CAT_NUM" VARCHAR2(50), 
	"HEC_NUM" VARCHAR2(50)
   ) ;
