
  CREATE TABLE "CF_TEMP_ID" 
   (	"KEY" NUMBER, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"COLLECTION_CDE" VARCHAR2(10), 
	"INSTITUTION_ACRONYM" VARCHAR2(6 CHAR), 
	"OTHER_ID_TYPE" VARCHAR2(60 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"SCIENTIFIC_NAME" VARCHAR2(255 CHAR), 
	"MADE_DATE" VARCHAR2(22 CHAR), 
	"NATURE_OF_ID" VARCHAR2(30 CHAR), 
	"ACCEPTED_FG" NUMBER(1,0), 
	"IDENTIFICATION_REMARKS" VARCHAR2(255 CHAR), 
	"AGENT_1" VARCHAR2(60 CHAR), 
	"AGENT_2" VARCHAR2(60 CHAR), 
	"STATUS" VARCHAR2(1000), 
	"TAXON_NAME_ID" NUMBER, 
	"TAXA_FORMULA" VARCHAR2(25), 
	"AGENT_1_ID" NUMBER, 
	"AGENT_2_ID" NUMBER, 
	"STORED_AS_FG" NUMBER(1,0)
   ) 