
  CREATE TABLE "CF_TEMP_BARCODE_PARTS" 
   (	"OTHER_ID_TYPE" VARCHAR2(255 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10), 
	"INSTITUTION_ACRONYM" VARCHAR2(20 CHAR), 
	"PART_NAME" VARCHAR2(255 CHAR), 
	"PART_COLLECTION_OBJECT_ID" NUMBER, 
	"PRESERVE_METHOD" VARCHAR2(50 CHAR), 
	"STATUS" VARCHAR2(4000), 
	"PARENT_CONTAINER_ID" NUMBER, 
	"PART_CONTAINER_ID" NUMBER, 
	"USERNAME" VARCHAR2(1020), 
	"KEY" NUMBER NOT NULL ENABLE, 
	"CURRENT_REMARKS" VARCHAR2(2000), 
	"CURRENT_PARENT_CONTAINER_ID" NUMBER, 
	"NEW_PARENT_CONTAINER_ID" NUMBER, 
	"CONTAINER_BARCODE" VARCHAR2(255 CHAR), 
	"NEW_CONTAINER_BARCODE" VARCHAR2(100), 
	"COLLECTION_OBJECT_ID" VARCHAR2(20)
   ) ;
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."INSTITUTION_ACRONYM" IS 'Should be "MCZ".  Required if part_collection_object_id is not provided.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."PART_NAME" IS 'Required. Name of the part to change the container for.  ';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."PART_COLLECTION_OBJECT_ID" IS 'Internal numeric identifier for the part, present in downloaded CSV from Manage-> Part/Report Download.  Preferred means of identifying part to move.  If not provided, will be looked up from from collection_cde, other_id _type, and other_id_number, part_name, preserve_method, and current_remarks.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."PRESERVE_METHOD" IS 'Required. Preservation method of the part to change the container for.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."STATUS" IS 'Result of validation checks.  Error message will show in this field.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."PARENT_CONTAINER_ID" IS 'Autogenerated. Internal key for the container that contains the desired container; looked up during validation.  Shows that container exists. ';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."PART_CONTAINER_ID" IS 'Autogenerated Intermal key for the part container.  Field used to coordinate container_unique_id and parent container.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."USERNAME" IS 'The user who created these temporary rows.  Allows multiple users to use the bulkloader at the same time.  A user is limited to one bulkload into this table at a time.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."KEY" IS 'Surrogate numeric primary  key';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."CURRENT_REMARKS" IS 'Part Remarks for the part to change the container for.  Required if part_collection_object_id is not provided, and part remarks are non-empty.  Must be an exact match to the part remarks.  Needed to differentiate between two parts on a specimen record that have the same part name and preserve method.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."CURRENT_PARENT_CONTAINER_ID" IS 'Autogenerated. CONTAINER_ID that matches the current container for the collection object.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."NEW_PARENT_CONTAINER_ID" IS 'Autogenerated. CONTAINER_ID that matches the NEW_CONTAINER_BARCODE.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."CONTAINER_BARCODE" IS 'Required.  The uniuqe identifer for the container the part is currently in.  May be the top level container "The Museum of Comparative Zoology."';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."NEW_CONTAINER_BARCODE" IS 'Required.  The unique identifer for the container the part is to be moved into. It must already exist in MCZbase.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."COLLECTION_OBJECT_ID" IS 'Autogenerated.  Looked up from institution:collection code:catalog number, the collection_object_id for the cataloged item used to link to specimen search on successfull load.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."OTHER_ID_TYPE" IS 'Required.  Only "catalog number" is supported.';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."OTHER_ID_NUMBER" IS 'Required.  The catalog number of the cataloged item for the part. ';
COMMENT ON COLUMN "CF_TEMP_BARCODE_PARTS"."COLLECTION_CDE" IS 'Required. Collection or department abbreviation for the cataloged item for the part.';
