
  CREATE TABLE "CF_TEMP_LOAN_ITEM" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"INSTITUTION_ACRONYM" VARCHAR2(5 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	"OTHER_ID_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"OTHER_ID_NUMBER" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"PART_NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"SUBSAMPLE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"ITEM_DESCRIPTION" VARCHAR2(255 CHAR), 
	"ITEM_REMARKS" VARCHAR2(255 CHAR), 
	"LOAN_NUMBER" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"PARTID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"STATUS" VARCHAR2(255 CHAR), 
	"BARCODE" VARCHAR2(50 CHAR)
   ) 