
  CREATE TABLE "CF_TACC_TRANSFER" 
   (	"MEDIA_ID" NUMBER, 
	"SDATE" DATE, 
	"LOCAL_URI" VARCHAR2(4000 CHAR), 
	"REMOTE_URI" VARCHAR2(4000 CHAR), 
	"LOCAL_HASH" VARCHAR2(255 CHAR), 
	"REMOTE_HASH" VARCHAR2(255 CHAR), 
	"LOCAL_TN" VARCHAR2(4000 CHAR), 
	"REMOTE_TN" VARCHAR2(4000 CHAR), 
	"LOCAL_TN_HASH" VARCHAR2(255 CHAR), 
	"REMOTE_TN_HASH" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"REMOTEDIRECTORY" VARCHAR2(30 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CF_TACC_TRANSFER" ON "CF_TACC_TRANSFER" ("MEDIA_ID") 
  
ALTER TABLE "CF_TACC_TRANSFER" ADD CONSTRAINT "PK_CF_TACC_TRANSFER" PRIMARY KEY ("MEDIA_ID")
  USING INDEX "PK_CF_TACC_TRANSFER"  ENABLE