
  CREATE TABLE "CF_TEMP_ATTRIBUTES" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"OTHER_ID_TYPE" VARCHAR2(60 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"ATTRIBUTE" VARCHAR2(60 CHAR), 
	"ATTRIBUTE_VALUE" VARCHAR2(4000), 
	"ATTRIBUTE_UNITS" VARCHAR2(60 CHAR), 
	"ATTRIBUTE_DATE" VARCHAR2(60 CHAR), 
	"ATTRIBUTE_METH" VARCHAR2(255 CHAR), 
	"DETERMINER" VARCHAR2(60 CHAR), 
	"REMARKS" VARCHAR2(255 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10), 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"INSTITUTION_ACRONYM" VARCHAR2(20 CHAR), 
	"DETERMINED_BY_AGENT_ID" NUMBER, 
	"STATUS" VARCHAR2(255)
   ) 