
  CREATE TABLE "CF_TEMP_SCANS" 
   (	"KEY" NUMBER, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"PART_NAME" VARCHAR2(60 CHAR), 
	"BARCODE" VARCHAR2(60 CHAR), 
	"PARENT_BARCODE" VARCHAR2(60 CHAR), 
	"PRINT_FLAG" NUMBER, 
	"PROBLEM" VARCHAR2(4000 CHAR)
   ) ;
