
  CREATE TABLE "CF_TEMP_DATA_LOAN_ITEM" 
   (	"KEY" NUMBER, 
	"INSTITUTION_ACRONYM" VARCHAR2(5 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10), 
	"OTHER_ID_TYPE" VARCHAR2(30 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(30 CHAR), 
	"LOAN_NUMBER" VARCHAR2(30 CHAR), 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"ITEM_DESCRIPTION" VARCHAR2(60 CHAR), 
	"STATUS" VARCHAR2(255 CHAR)
   ) ;
