
  CREATE TABLE "CF_TEMP_SLIDESCANS" 
   (	"MEDIA_URI" VARCHAR2(200), 
	"MIME_TYPE" VARCHAR2(9), 
	"MEDIA_TYPE" VARCHAR2(5), 
	"PREVIEW_URI" VARCHAR2(200), 
	"MEDIA_RELATIONSHIPS" VARCHAR2(4000), 
	"MEDIA_LABELS" VARCHAR2(255), 
	"HEC_NUMBER" VARCHAR2(10), 
	"SLIDE_LETTER" VARCHAR2(10)
   ) 