
  CREATE TABLE "CF_TEMP_BL_RELATIONS" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"INSTITUTION_ACRONYM" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	"OTHER_ID_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"OTHER_ID_VALUE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RELATIONSHIP" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RELATED_INSTITUTION_ACRONYM" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"RELATED_COLLECTION_CDE" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	"RELATED_OTHER_ID_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"RELATED_OTHER_ID_VALUE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"RELATED_COLLECTION_OBJECT_ID" NUMBER, 
	"STATUS" VARCHAR2(4000 CHAR), 
	"USERNAME" VARCHAR2(1020), 
	"BIOL_INDIV_RELATION_REMARKS" VARCHAR2(4000)
   ) 