
  CREATE TABLE "CF_TEMP_CONT_EDIT" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"CONTAINER_UNIQUE_ID" VARCHAR2(60 CHAR), 
	"PARENT_UNIQUE_ID" VARCHAR2(60 CHAR), 
	"CONTAINER_TYPE" VARCHAR2(60 CHAR), 
	"CONTAINER_NAME" VARCHAR2(60 CHAR), 
	"DESCRIPTION" VARCHAR2(60 CHAR), 
	"REMARKS" VARCHAR2(60 CHAR), 
	"WIDTH" NUMBER, 
	"HEIGHT" NUMBER, 
	"LENGTH" NUMBER, 
	"NUMBER_POSITIONS" NUMBER, 
	"CONTAINER_ID" NUMBER, 
	"PARENT_CONTAINER_ID" NUMBER, 
	"STATUS" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255), 
	 CONSTRAINT "CF_TEMP_CONT_EDIT_PK" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE
   ) 