
  CREATE TABLE "CF_TEMP_LOAN_ITEM" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"INSTITUTION_ACRONYM" VARCHAR2(5 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10 CHAR), 
	"OTHER_ID_TYPE" VARCHAR2(30 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(30 CHAR), 
	"PART_NAME" VARCHAR2(50), 
	"SUBSAMPLE" VARCHAR2(5 CHAR), 
	"ITEM_DESCRIPTION" VARCHAR2(2000 CHAR), 
	"ITEM_REMARKS" VARCHAR2(255 CHAR), 
	"LOAN_NUMBER" VARCHAR2(30 CHAR), 
	"PART_COLLECTION_OBJECT_ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"STATUS" VARCHAR2(255 CHAR), 
	"CONTAINER_BARCODE" VARCHAR2(200 CHAR), 
	"ITEM_INSTRUCTIONS" VARCHAR2(2000 CHAR), 
	"USERNAME" VARCHAR2(200), 
	"PART_REMARKS" VARCHAR2(2000), 
	"CONDITION" VARCHAR2(200), 
	"COLL_OBJ_DISPOSITION" VARCHAR2(200), 
	"PRESERVE_METHOD" VARCHAR2(200)
   ) 