
  CREATE TABLE "CF_TEMP_BARCODE_PARTS" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"OTHER_ID_TYPE" VARCHAR2(255 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10), 
	"INSTITUTION_ACRONYM" VARCHAR2(20 CHAR), 
	"PART_NAME" VARCHAR2(255 CHAR), 
	"CONTAINER_UNIQUE_ID" VARCHAR2(255 CHAR), 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"CONTAINER_ID" NUMBER, 
	"PRINT_FG" VARCHAR2(10 CHAR), 
	"PRESERVE_METHOD" VARCHAR2(50 CHAR), 
	"STATUS" VARCHAR2(500), 
	"PARENT_CONTAINER_ID" NUMBER, 
	"PART_CONTAINER_ID" NUMBER
   ) 