
  CREATE TABLE "CF_TEMP_MEDIA" 
   (	"KEY" NUMBER, 
	"MEDIA_URI" VARCHAR2(255 CHAR), 
	"MIME_TYPE" VARCHAR2(255 CHAR), 
	"MEDIA_TYPE" VARCHAR2(255 CHAR), 
	"PREVIEW_URI" VARCHAR2(255 CHAR), 
	"MEDIA_RELATIONSHIPS" VARCHAR2(4000), 
	"MEDIA_LABELS" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(4000 CHAR)
   ) 