
  CREATE TABLE "CF_TEMP_LOAN_ITEM" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"INSTITUTION_ACRONYM" VARCHAR2(5 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10 CHAR), 
	"OTHER_ID_TYPE" VARCHAR2(30 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(30 CHAR), 
	"PART_NAME" VARCHAR2(50), 
	"SUBSAMPLE" VARCHAR2(5 CHAR), 
	"ITEM_DESCRIPTION" VARCHAR2(2000 CHAR), 
	"ITEM_REMARKS" VARCHAR2(255 CHAR), 
	"LOAN_NUMBER" VARCHAR2(30 CHAR), 
	"PART_COLLECTION_OBJECT_ID" NUMBER, 
	"TRANSACTION_ID" NUMBER, 
	"STATUS" VARCHAR2(255 CHAR), 
	"CONTAINER_BARCODE" VARCHAR2(200 CHAR), 
	"ITEM_INSTRUCTIONS" VARCHAR2(2000 CHAR), 
	"USERNAME" VARCHAR2(200), 
	"PART_REMARKS" VARCHAR2(2000), 
	"CONDITION" VARCHAR2(200), 
	"COLL_OBJ_DISPOSITION" VARCHAR2(200), 
	"PRESERVE_METHOD" VARCHAR2(200)
   ) ;
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."ITEM_INSTRUCTIONS" IS 'Instructions about handling the part on loan. These instructions show when "review items" button is clicked on the loan.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."USERNAME" IS 'The person who entered these rows.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."PART_REMARKS" IS 'Remarks about the part that also help to distinguish similar part rows.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."CONDITION" IS 'Required: Part condition';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."COLL_OBJ_DISPOSITION" IS 'Required: Disposition of the part in the collection (e.g., in collection, unknown, being processed, not applicable). It cannot be "on loan".';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."PRESERVE_METHOD" IS 'Required: Preserve method for the specimen. Controlled vocabulary per collecton. ';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."KEY" IS 'surrogate numeric primary key';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."INSTITUTION_ACRONYM" IS 'Required: Should be "MCZ" for Institution_acronym';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."COLLECTION_CDE" IS 'Required: Controlled vocabulary.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."OTHER_ID_TYPE" IS 'Required: Could be "catalog number" or controlled vocabulary for other_id_type.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."OTHER_ID_NUMBER" IS 'Required: Catalog number or value that goes with other_id_type';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."PART_NAME" IS 'Required: Part name uses controlled vocabulary related to collection';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."SUBSAMPLE" IS 'Required: Enter "yes" or "no". A "yes" will create a new part row (or subsample) connected to the sample (or primary part), and will place the newly created subsample in the loan.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."ITEM_DESCRIPTION" IS 'This entry of "collection_cde,other_id_number, partname(preserve_method)" is created by MCZbase.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."ITEM_REMARKS" IS 'Item remarks about the part. These show when "review items" button is clicked on the loan.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."LOAN_NUMBER" IS 'Required: loan number is an alpha numberic combination. Loan must already be in MCZbase.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."PART_COLLECTION_OBJECT_ID" IS 'Required: Part COLLECTION_OBJECT_ID (from part download) is autogenerated and is based on the cataloged item and collection_cde. A new part is made when subsample = "yes"';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."TRANSACTION_ID" IS 'Transaction ID is autogenerated and is based on the loan number.';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."STATUS" IS 'Error messages appear in this column';
COMMENT ON COLUMN "CF_TEMP_LOAN_ITEM"."CONTAINER_BARCODE" IS 'Required: referred to as container_unique_id or barcode. It represents the location of the specimen part at the MCZ.';
