
  CREATE TABLE "CF_TEMP_AGENT_ROLE_SUMMARY" 
   (	"TABLE_NAME" VARCHAR2(128 CHAR), 
	"AGENT_ID" NUMBER, 
	"COUNT" NUMBER, 
	"COLUMN_NAME" VARCHAR2(128 CHAR), 
	"AGENT_NAME" VARCHAR2(128 CHAR), 
	"LABEL" VARCHAR2(200 CHAR)
   ) 