
  CREATE TABLE "CF_TEMP_CITATION" 
   (	"KEY" NUMBER, 
	"PUBLICATION_TITLE" VARCHAR2(4000 CHAR), 
	"PUBLICATION_ID" NUMBER, 
	"INSTITUTION_ACRONYM" VARCHAR2(6 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10), 
	"OTHER_ID_TYPE" VARCHAR2(60 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"CITED_SCIENTIFIC_NAME" VARCHAR2(60 CHAR), 
	"CITED_TAXON_NAME_ID" NUMBER, 
	"OCCURS_PAGE_NUMBER" NUMBER, 
	"TYPE_STATUS" VARCHAR2(60 CHAR), 
	"CITATION_REMARKS" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000), 
	"CITATION_PAGE_URI" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255)
   ) 