
  CREATE TABLE "CF_TEMP_RELATIONS" 
   (	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"RELATIONSHIP" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"RELATED_TO_NUMBER" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"RELATED_TO_NUM_TYPE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"LASTTRYDATE" DATE, 
	"FAIL_REASON" VARCHAR2(255 CHAR), 
	"RELATED_COLLECTION_OBJECT_ID" NUMBER, 
	"INSERT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CF_TEMP_RELATIONS_ID" NUMBER NOT NULL ENABLE, 
	"BIOL_INDIV_RELATION_REMARKS" VARCHAR2(4000)
   ) 