
  CREATE TABLE "CF_TEMP_OIDS" 
   (	"KEY" NUMBER, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"COLLECTION_CDE" VARCHAR2(10), 
	"INSTITUTION_ACRONYM" VARCHAR2(6 CHAR), 
	"EXISTING_OTHER_ID_TYPE" VARCHAR2(60 CHAR), 
	"EXISTING_OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"NEW_OTHER_ID_TYPE" VARCHAR2(60 CHAR), 
	"NEW_OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"STATUS" VARCHAR2(4000), 
	"USERNAME" VARCHAR2(1020)
   ) 