
  CREATE TABLE "CF_TEMP_BARCODE_PARTS" 
   (	"OTHER_ID_TYPE" VARCHAR2(255 CHAR), 
	"OTHER_ID_NUMBER" VARCHAR2(60 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10), 
	"INSTITUTION_ACRONYM" VARCHAR2(20 CHAR), 
	"PART_NAME" VARCHAR2(255 CHAR), 
	"PART_COLLECTION_OBJECT_ID" NUMBER, 
	"PRESERVE_METHOD" VARCHAR2(50 CHAR), 
	"STATUS" VARCHAR2(4000), 
	"PARENT_CONTAINER_ID" NUMBER, 
	"PART_CONTAINER_ID" NUMBER, 
	"USERNAME" VARCHAR2(1020), 
	"KEY" NUMBER NOT NULL ENABLE, 
	"CURRENT_REMARKS" VARCHAR2(2000), 
	"CURRENT_PARENT_CONTAINER_ID" NUMBER, 
	"NEW_PARENT_CONTAINER_ID" NUMBER, 
	"CONTAINER_BARCODE" VARCHAR2(255 CHAR), 
	"NEW_CONTAINER_BARCODE" VARCHAR2(100), 
	"COLLECTION_OBJECT_ID" VARCHAR2(20)
   ) 