
  CREATE TABLE "CF_TEMP_AGENTS" 
   (	"KEY" NUMBER NOT NULL ENABLE, 
	"AGENT_TYPE" VARCHAR2(255 CHAR), 
	"PREFERRED_NAME" VARCHAR2(255 CHAR), 
	"FIRST_NAME" VARCHAR2(255 CHAR), 
	"MIDDLE_NAME" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"BIRTH_DATE" DATE, 
	"DEATH_DATE" DATE, 
	"AGENT_REMARK" VARCHAR2(255 CHAR), 
	"PREFIX" VARCHAR2(255 CHAR), 
	"SUFFIX" VARCHAR2(255 CHAR), 
	"OTHER_NAME_TYPE" VARCHAR2(255 CHAR), 
	"OTHER_NAME" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"OTHER_NAME_TYPE_2" VARCHAR2(255 CHAR), 
	"OTHER_NAME_2" VARCHAR2(255 CHAR), 
	"OTHER_NAME_TYPE_3" VARCHAR2(255 CHAR), 
	"OTHER_NAME_3" VARCHAR2(255 CHAR)
   ) 