
  CREATE TABLE "CF_USER_DATA" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"MIDDLE_NAME" VARCHAR2(60 CHAR), 
	"LAST_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"AFFILIATION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(255 CHAR)
   ) ;
