
  CREATE TABLE "CF_USER_LOG" 
   (	"IP" VARCHAR2(30 CHAR), 
	"HOST" VARCHAR2(255 CHAR), 
	"FORM" VARCHAR2(255 CHAR), 
	"DATESTAMP" DATE, 
	"USERNAME" VARCHAR2(60 CHAR), 
	"COLLECTIONS" VARCHAR2(100 CHAR), 
	"NUMRECORDS" NUMBER
   ) 