
  CREATE TABLE "CF_USER_LOAN" 
   (	"USER_LOAN_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"IS_ACTIVE" NUMBER NOT NULL ENABLE, 
	"PROJECT_TITLE" VARCHAR2(255 CHAR), 
	"PROJECT_DESCRIPTION" VARCHAR2(4000)
   ) 