
  CREATE TABLE "CITATION_BACKUP" 
   (	"PUBLICATION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"CITED_TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"CIT_CURRENT_FG" NUMBER NOT NULL ENABLE, 
	"OCCURS_PAGE_NUMBER" NUMBER, 
	"TYPE_STATUS" VARCHAR2(60), 
	"CITATION_REMARKS" VARCHAR2(500 CHAR), 
	"CITATION_TEXT" VARCHAR2(255 CHAR), 
	"REP_PUBLISHED_YEAR" NUMBER, 
	"CITATION_PAGE_URI" VARCHAR2(255 CHAR)
   ) 