
  CREATE TABLE "CITATION" 
   (	"PUBLICATION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"CITED_TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"CIT_CURRENT_FG" NUMBER NOT NULL ENABLE, 
	"OCCURS_PAGE_NUMBER" NUMBER, 
	"TYPE_STATUS" VARCHAR2(60), 
	"CITATION_REMARKS" VARCHAR2(4000), 
	"CITATION_TEXT" VARCHAR2(255 CHAR), 
	"REP_PUBLISHED_YEAR" NUMBER, 
	"CITATION_PAGE_URI" VARCHAR2(255 CHAR), 
	 CONSTRAINT "PK_CITATION" PRIMARY KEY ("COLLECTION_OBJECT_ID", "PUBLICATION_ID", "CITED_TAXON_NAME_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CITATION_CATITEM" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_CITATION_PUBLICATION" FOREIGN KEY ("PUBLICATION_ID")
	  REFERENCES "PUBLICATION" ("PUBLICATION_ID") ENABLE, 
	 CONSTRAINT "FK_CITATION_TAXONOMY" FOREIGN KEY ("CITED_TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE
   ) 