
  CREATE TABLE "COLLECTING_EVENT" 
   (	"COLLECTING_EVENT_ID" NUMBER NOT NULL ENABLE, 
	"LOCALITY_ID" NUMBER NOT NULL ENABLE, 
	"DATE_BEGAN_DATE" DATE, 
	"DATE_ENDED_DATE" DATE, 
	"VERBATIM_DATE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"VERBATIM_LOCALITY" VARCHAR2(2000 CHAR), 
	"COLL_EVENT_REMARKS" VARCHAR2(4000 CHAR), 
	"VALID_DISTRIBUTION_FG" NUMBER, 
	"COLLECTING_SOURCE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"COLLECTING_METHOD" VARCHAR2(255), 
	"HABITAT_DESC" VARCHAR2(500 CHAR), 
	"DATE_DETERMINED_BY_AGENT_ID" NUMBER, 
	"FISH_FIELD_NUMBER" VARCHAR2(50 CHAR), 
	"BEGAN_DATE" VARCHAR2(22 CHAR), 
	"ENDED_DATE" VARCHAR2(22 CHAR), 
	"COLLECTING_TIME" VARCHAR2(50), 
	"VERBATIMCOORDINATES" VARCHAR2(100 CHAR), 
	"VERBATIMLATITUDE" VARCHAR2(50 CHAR), 
	"VERBATIMLONGITUDE" VARCHAR2(50 CHAR), 
	"VERBATIMCOORDINATESYSTEM" VARCHAR2(50 CHAR), 
	"VERBATIMSRS" VARCHAR2(50 CHAR), 
	"STARTDAYOFYEAR" NUMBER(3,0), 
	"ENDDAYOFYEAR" NUMBER(3,0), 
	"VERBATIMELEVATION" VARCHAR2(500), 
	"VERBATIMDEPTH" VARCHAR2(500), 
	"VERBATIM_COLLECTORS" VARCHAR2(2000), 
	"VERBATIM_FIELD_NUMBERS" VARCHAR2(500), 
	"VERBATIM_HABITAT" VARCHAR2(2000), 
	 CONSTRAINT "CK_BEGAN_BEFORE_END" CHECK (began_date <= ended_date) ENABLE, 
	 CONSTRAINT "FK_CTCOLLECTING_SOURCE" FOREIGN KEY ("COLLECTING_SOURCE")
	  REFERENCES "CTCOLLECTING_SOURCE" ("COLLECTING_SOURCE") ENABLE, 
	 CONSTRAINT "FK_COLLEVENT_LOCALITY" FOREIGN KEY ("LOCALITY_ID")
	  REFERENCES "LOCALITY" ("LOCALITY_ID") ENABLE, 
	 CONSTRAINT "FK_COLLEVENT_DATDET_AGENT" FOREIGN KEY ("DATE_DETERMINED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   )  ENABLE ROW MOVEMENT 
  CREATE UNIQUE INDEX "PK_COLL_EVENT_ID" ON "COLLECTING_EVENT" ("COLLECTING_EVENT_ID") 
  
ALTER TABLE "COLLECTING_EVENT" ADD CONSTRAINT "PK_COLLECTING_EVENT" PRIMARY KEY ("COLLECTING_EVENT_ID")
  USING INDEX "PK_COLL_EVENT_ID"  ENABLE