
  CREATE TABLE "COLLECTOR" 
   (	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTOR_ROLE" CHAR(1 CHAR) NOT NULL ENABLE, 
	"COLL_NUM_PREFIX" VARCHAR2(20 CHAR), 
	"COLL_NUM" NUMBER(15,0), 
	"COLL_NUM_SUFFIX" VARCHAR2(9 CHAR), 
	"COLL_ORDER" NUMBER NOT NULL ENABLE, 
	"COLLECTOR_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "COLL_ROLE_CHECK" CHECK (COLLECTOR_ROLE IN ('c','p')) ENABLE, 
	 CONSTRAINT "COLLECTOR_PK" PRIMARY KEY ("COLLECTOR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_COLLECTOR_CATITEM" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_CTCOLLECTOR_ROLE" FOREIGN KEY ("COLLECTOR_ROLE")
	  REFERENCES "CTCOLLECTOR_ROLE" ("COLLECTOR_ROLE") ENABLE, 
	 CONSTRAINT "FK_COLLECTOR_AGENT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 