
  CREATE TABLE "COLL_EVENT_NUMBER" 
   (	"COLL_EVENT_NUMBER_ID" NUMBER NOT NULL ENABLE, 
	"COLL_EVENT_NUMBER" VARCHAR2(255) NOT NULL ENABLE, 
	"COLLECTING_EVENT_ID" NUMBER NOT NULL ENABLE, 
	"COLL_EVENT_NUM_SERIES_ID" NUMBER, 
	 CONSTRAINT "COLL_EVENT_NUMBER_PK" PRIMARY KEY ("COLL_EVENT_NUMBER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "COLL_EVENT_NUMBER_FK1" FOREIGN KEY ("COLL_EVENT_NUM_SERIES_ID")
	  REFERENCES "COLL_EVENT_NUM_SERIES" ("COLL_EVENT_NUM_SERIES_ID") ENABLE, 
	 CONSTRAINT "COLL_EVENT_NUMBER_FK2" FOREIGN KEY ("COLLECTING_EVENT_ID")
	  REFERENCES "COLLECTING_EVENT" ("COLLECTING_EVENT_ID") ON DELETE CASCADE ENABLE
   ) 