
  CREATE TABLE "COLLECTION_CONTACTS" 
   (	"COLLECTION_CONTACT_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"CONTACT_ROLE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CONTACT_AGENT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_COLLCONTACTS_CTCOLLCONTROLE" FOREIGN KEY ("CONTACT_ROLE")
	  REFERENCES "CTCOLL_CONTACT_ROLE" ("CONTACT_ROLE") ENABLE, 
	 CONSTRAINT "FK_COLLCONTACTS_COLLECTION" FOREIGN KEY ("COLLECTION_ID")
	  REFERENCES "COLLECTION" ("COLLECTION_ID") ENABLE, 
	 CONSTRAINT "FK_COLLCONTACTS_AGENT" FOREIGN KEY ("CONTACT_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "IDX_COLLECTION_CONTACTS_PK" ON "COLLECTION_CONTACTS" ("COLLECTION_CONTACT_ID") 
  
ALTER TABLE "COLLECTION_CONTACTS" ADD CONSTRAINT "COLLECTION_CONTACTS_PK" PRIMARY KEY ("COLLECTION_CONTACT_ID")
  USING INDEX "IDX_COLLECTION_CONTACTS_PK"  ENABLE;
COMMENT ON COLUMN "COLLECTION_CONTACTS"."COLLECTION_CONTACT_ID" IS 'Surrogate Numeric primary key';
COMMENT ON COLUMN "COLLECTION_CONTACTS"."COLLECTION_ID" IS 'Collection for which this is a contact';
COMMENT ON COLUMN "COLLECTION_CONTACTS"."CONTACT_ROLE" IS 'Role of the contact';
COMMENT ON COLUMN "COLLECTION_CONTACTS"."CONTACT_AGENT_ID" IS 'Agent which is the contact in this role for this collection.';
