
  CREATE TABLE "COLL_EVENT_NUMBER" 
   (	"COLL_EVENT_NUMBER_ID" NUMBER NOT NULL ENABLE, 
	"COLL_EVENT_NUMBER" VARCHAR2(255) NOT NULL ENABLE, 
	"COLLECTING_EVENT_ID" NUMBER NOT NULL ENABLE, 
	"COLL_EVENT_NUM_SERIES_ID" NUMBER, 
	 CONSTRAINT "COLL_EVENT_NUMBER_PK" PRIMARY KEY ("COLL_EVENT_NUMBER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "COLL_EVENT_NUMBER_FK1" FOREIGN KEY ("COLL_EVENT_NUM_SERIES_ID")
	  REFERENCES "COLL_EVENT_NUM_SERIES" ("COLL_EVENT_NUM_SERIES_ID") ENABLE, 
	 CONSTRAINT "COLL_EVENT_NUMBER_FK2" FOREIGN KEY ("COLLECTING_EVENT_ID")
	  REFERENCES "COLLECTING_EVENT" ("COLLECTING_EVENT_ID") ON DELETE CASCADE ENABLE
   ) ;
COMMENT ON COLUMN "COLL_EVENT_NUMBER"."COLL_EVENT_NUMBER_ID" IS 'surrogate numeric primary key';
COMMENT ON COLUMN "COLL_EVENT_NUMBER"."COLL_EVENT_NUMBER" IS 'the value of the collecting event number';
COMMENT ON COLUMN "COLL_EVENT_NUMBER"."COLLECTING_EVENT_ID" IS 'the collecting event to which this number applies';
COMMENT ON COLUMN "COLL_EVENT_NUMBER"."COLL_EVENT_NUM_SERIES_ID" IS 'number series from which this number comes';
