
  CREATE TABLE "COLLECTION_CONTACTS" 
   (	"COLLECTION_CONTACT_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"CONTACT_ROLE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"CONTACT_AGENT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_COLLCONTACTS_CTCOLLCONTROLE" FOREIGN KEY ("CONTACT_ROLE")
	  REFERENCES "CTCOLL_CONTACT_ROLE" ("CONTACT_ROLE") ENABLE, 
	 CONSTRAINT "FK_COLLCONTACTS_COLLECTION" FOREIGN KEY ("COLLECTION_ID")
	  REFERENCES "COLLECTION" ("COLLECTION_ID") ENABLE
   ) 