
  CREATE TABLE "COLL_OBJ_OTHER_ID_NUM" 
   (	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"OTHER_ID_TYPE" VARCHAR2(75 CHAR) NOT NULL ENABLE, 
	"OTHER_ID_PREFIX" VARCHAR2(100 CHAR), 
	"OTHER_ID_NUMBER" NUMBER, 
	"OTHER_ID_SUFFIX" VARCHAR2(60 CHAR), 
	"DISPLAY_VALUE" VARCHAR2(255 CHAR), 
	"COLL_OBJ_OTHER_ID_NUM_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "FK_COLLOBJOTHERIDNUM_CATITEM" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_CTCOLL_OTHER_ID_TYPE" FOREIGN KEY ("OTHER_ID_TYPE")
	  REFERENCES "CTCOLL_OTHER_ID_TYPE" ("OTHER_ID_TYPE") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_COLL_OBJ_OTHER_ID_NUM_ID" ON "COLL_OBJ_OTHER_ID_NUM" ("COLL_OBJ_OTHER_ID_NUM_ID") 
  
ALTER TABLE "COLL_OBJ_OTHER_ID_NUM" ADD CONSTRAINT "PK_COLL_OBJ_OTHER_ID_NUM_ID" PRIMARY KEY ("COLL_OBJ_OTHER_ID_NUM_ID")
  USING INDEX "PK_COLL_OBJ_OTHER_ID_NUM_ID"  ENABLE