
  CREATE TABLE "COLL_OBJ_CONT_HIST" 
   (	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	"INSTALLED_DATE" DATE NOT NULL ENABLE, 
	"CURRENT_CONTAINER_FG" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_COLLOBJCONTHIST_CONTAINER" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CONTAINER" ("CONTAINER_ID") ENABLE
   ) 