
  CREATE TABLE "COLL_EVENT_NUM_SERIES" 
   (	"COLL_EVENT_NUM_SERIES_ID" NUMBER NOT NULL ENABLE, 
	"NUMBER_SERIES" VARCHAR2(255) NOT NULL ENABLE, 
	"PATTERN" VARCHAR2(100), 
	"REMARKS" VARCHAR2(900), 
	"COLLECTOR_AGENT_ID" NUMBER, 
	 CONSTRAINT "COLL_EVENT_NUM_SERIES_PK" PRIMARY KEY ("COLL_EVENT_NUM_SERIES_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "COLL_EVENT_NUM_SERIES_FK1" FOREIGN KEY ("COLLECTOR_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 