
  CREATE TABLE "COLL_OBJECT_ENCUMBRANCE" 
   (	"ENCUMBRANCE_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_COLLOBJENC_ENCUMBRANCE" FOREIGN KEY ("ENCUMBRANCE_ID")
	  REFERENCES "ENCUMBRANCE" ("ENCUMBRANCE_ID") ENABLE, 
	 CONSTRAINT "FK_COLLOBJENC_COLLOBJECT" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE
   )  ENABLE ROW MOVEMENT ;
