
  CREATE TABLE "COLL_OBJECT_REMARK" 
   (	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"DISPOSITION_REMARKS" VARCHAR2(4000 CHAR), 
	"COLL_OBJECT_REMARKS" VARCHAR2(4000 CHAR), 
	"HABITAT" VARCHAR2(4000 CHAR), 
	"ASSOCIATED_SPECIES" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "FK_COLLOBJREM_COLLOBJECT" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE
   ) 