
  CREATE TABLE "COLLECTING_EVENT" 
   (	"COLLECTING_EVENT_ID" NUMBER NOT NULL ENABLE, 
	"LOCALITY_ID" NUMBER NOT NULL ENABLE, 
	"DATE_BEGAN_DATE" DATE, 
	"DATE_ENDED_DATE" DATE, 
	"VERBATIM_DATE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"VERBATIM_LOCALITY" VARCHAR2(400 CHAR), 
	"COLL_EVENT_REMARKS" VARCHAR2(500 CHAR), 
	"VALID_DISTRIBUTION_FG" NUMBER, 
	"COLLECTING_SOURCE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"COLLECTING_METHOD" VARCHAR2(255), 
	"HABITAT_DESC" VARCHAR2(500 CHAR), 
	"DATE_DETERMINED_BY_AGENT_ID" NUMBER, 
	"FISH_FIELD_NUMBER" VARCHAR2(50 CHAR), 
	"BEGAN_DATE" VARCHAR2(22 CHAR), 
	"ENDED_DATE" VARCHAR2(22 CHAR), 
	"COLLECTING_TIME" VARCHAR2(50), 
	"VERBATIMCOORDINATES" VARCHAR2(100 CHAR), 
	"VERBATIMLATITUDE" VARCHAR2(50 CHAR), 
	"VERBATIMLONGITUDE" VARCHAR2(50 CHAR), 
	"VERBATIMCOORDINATESYSTEM" VARCHAR2(50 CHAR), 
	"VERBATIMSRS" VARCHAR2(50 CHAR), 
	"STARTDAYOFYEAR" NUMBER(3,0), 
	"ENDDAYOFYEAR" NUMBER(3,0), 
	 CONSTRAINT "CK_BEGAN_BEFORE_END" CHECK (began_date <= ended_date) ENABLE, 
	 CONSTRAINT "PK_COLLECTING_EVENT" PRIMARY KEY ("COLLECTING_EVENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTCOLLECTING_SOURCE" FOREIGN KEY ("COLLECTING_SOURCE")
	  REFERENCES "CTCOLLECTING_SOURCE" ("COLLECTING_SOURCE") ENABLE, 
	 CONSTRAINT "FK_COLLEVENT_LOCALITY" FOREIGN KEY ("LOCALITY_ID")
	  REFERENCES "LOCALITY" ("LOCALITY_ID") ENABLE
   )  ENABLE ROW MOVEMENT 