
  CREATE TABLE "COMMON_NAME" 
   (	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"COMMON_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"LANGUAGE_TAG" VARCHAR2(8), 
	"COMMON_NAME_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "COMMON_NAME_PK" PRIMARY KEY ("COMMON_NAME_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_COMMONNAME_TAXONOMY" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE
   ) 