
  CREATE TABLE "COMMON_NAME" 
   (	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"COMMON_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "FK_COMMONNAME_TAXONOMY" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE
   ) 