
  CREATE TABLE "CONTAINER_HISTORY" 
   (	"CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	"PARENT_CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	"INSTALL_DATE" DATE, 
	 CONSTRAINT "FK_CONTAINERHISTORY_CONTAINER" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CONTAINER" ("CONTAINER_ID") ON DELETE CASCADE ENABLE
   ) ;
