
  CREATE TABLE "CONTAINER_CHECK" 
   (	"CONTAINER_CHECK_ID" NUMBER NOT NULL ENABLE, 
	"CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	"CHECK_DATE" DATE NOT NULL ENABLE, 
	"CHECKED_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"CHECK_REMARK" VARCHAR2(255 CHAR), 
	 CONSTRAINT "PK_CONTAINER_CHECK" PRIMARY KEY ("CONTAINER_CHECK_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CONTAINERCHECK_CONTAINER" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CONTAINER" ("CONTAINER_ID") ENABLE, 
	 CONSTRAINT "FK_CONTAINERCHECK_AGENT" FOREIGN KEY ("CHECKED_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 