
  CREATE TABLE "CTACCN_STATUS" 
   (	"ACCN_STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTACCN_STATUS" ON "CTACCN_STATUS" ("ACCN_STATUS") 
  
ALTER TABLE "CTACCN_STATUS" ADD CONSTRAINT "PKEY_CTACCN_STATUS" PRIMARY KEY ("ACCN_STATUS")
  USING INDEX "PKEY_CTACCN_STATUS"  ENABLE;
