
  CREATE TABLE "CTACCN_TYPE" 
   (	"ACCN_TYPE" VARCHAR2(35 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTACCN_TYPE" ON "CTACCN_TYPE" ("ACCN_TYPE") 
  
ALTER TABLE "CTACCN_TYPE" ADD CONSTRAINT "PKEY_CTACCN_TYPE" PRIMARY KEY ("ACCN_TYPE")
  USING INDEX "PKEY_CTACCN_TYPE"  ENABLE