
  CREATE TABLE "CTADDR_USE" 
   (	"ADDR_USE" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTADDR_USE" ON "CTADDR_USE" ("ADDR_USE") 
  
ALTER TABLE "CTADDR_USE" ADD CONSTRAINT "PKEY_CTADDR_USE" PRIMARY KEY ("ADDR_USE")
  USING INDEX "PKEY_CTADDR_USE"  ENABLE;
