
  CREATE TABLE "CTADDR_TYPE" 
   (	"ADDR_TYPE" VARCHAR2(20) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_CTADDR_TYPE" ON "CTADDR_TYPE" ("ADDR_TYPE") 
  
ALTER TABLE "CTADDR_TYPE" ADD CONSTRAINT "PK_CTADDR_TYPE" PRIMARY KEY ("ADDR_TYPE")
  USING INDEX "PK_CTADDR_TYPE"  ENABLE;
