
  CREATE TABLE "CTAGENT_NAME_TYPE" 
   (	"AGENT_NAME_TYPE" VARCHAR2(40 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTAGENT_NAME_TYPE" ON "CTAGENT_NAME_TYPE" ("AGENT_NAME_TYPE") 
  
ALTER TABLE "CTAGENT_NAME_TYPE" ADD CONSTRAINT "PKEY_CTAGENT_NAME_TYPE" PRIMARY KEY ("AGENT_NAME_TYPE")
  USING INDEX "PKEY_CTAGENT_NAME_TYPE"  ENABLE;
