
  CREATE TABLE "CTAGENT_RANK" 
   (	"AGENT_RANK" VARCHAR2(50 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CTAGENT_RANK" ON "CTAGENT_RANK" ("AGENT_RANK") 
  
ALTER TABLE "CTAGENT_RANK" ADD CONSTRAINT "PK_CTAGENT_RANK" PRIMARY KEY ("AGENT_RANK")
  USING INDEX "PK_CTAGENT_RANK"  ENABLE