
  CREATE TABLE "CTAGENT_RELATIONSHIP" 
   (	"AGENT_RELATIONSHIP" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTAGENT_RELATIONSHIP" PRIMARY KEY ("AGENT_RELATIONSHIP")
  USING INDEX  ENABLE
   ) 