
  CREATE TABLE "CTAGENT_ADDR_JOB_TITLE" 
   (	"JOB_TITLE" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTAGENT_ADDR_JOB_TITLE" ON "CTAGENT_ADDR_JOB_TITLE" ("JOB_TITLE") 
  
ALTER TABLE "CTAGENT_ADDR_JOB_TITLE" ADD CONSTRAINT "PKEY_CTAGENT_ADDR_JOB_TITLE" PRIMARY KEY ("JOB_TITLE")
  USING INDEX "PKEY_CTAGENT_ADDR_JOB_TITLE"  ENABLE;
