
  CREATE TABLE "CTAGENT_RELATIONSHIP" 
   (	"AGENT_RELATIONSHIP" VARCHAR2(18 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTAGENT_RELATIONSHIP" ON "CTAGENT_RELATIONSHIP" ("AGENT_RELATIONSHIP") 
  
ALTER TABLE "CTAGENT_RELATIONSHIP" ADD CONSTRAINT "PKEY_CTAGENT_RELATIONSHIP" PRIMARY KEY ("AGENT_RELATIONSHIP")
  USING INDEX "PKEY_CTAGENT_RELATIONSHIP"  ENABLE;
