
  CREATE TABLE "CTAGENT_ROLE" 
   (	"AGENT_ROLE" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTAGENT_ROLE" ON "CTAGENT_ROLE" ("AGENT_ROLE") 
  
ALTER TABLE "CTAGENT_ROLE" ADD CONSTRAINT "PKEY_CTAGENT_ROLE" PRIMARY KEY ("AGENT_ROLE")
  USING INDEX "PKEY_CTAGENT_ROLE"  ENABLE