
  CREATE TABLE "CTAGENT_TYPE" 
   (	"AGENT_TYPE" VARCHAR2(30) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTAGENT_TYPE" ON "CTAGENT_TYPE" ("AGENT_TYPE") 
  
ALTER TABLE "CTAGENT_TYPE" ADD CONSTRAINT "PKEY_CTAGENT_TYPE" PRIMARY KEY ("AGENT_TYPE")
  USING INDEX "PKEY_CTAGENT_TYPE"  ENABLE;
