
  CREATE TABLE "CTAGE_DET_METHOD" 
   (	"AGE_DET_METH" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	 PRIMARY KEY ("AGE_DET_METH", "COLLECTION_CDE")
  USING INDEX  ENABLE
   ) 