
  CREATE TABLE "CTANNOTATION_TARGET_TABLE" 
   (	"ANNOTATION_TARGET_TABLE" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"PRIMARY_KEY_COLUMN" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CTANNOTATION_TARGET_TABLE" PRIMARY KEY ("ANNOTATION_TARGET_TABLE")
  USING INDEX  ENABLE
   ) ;
COMMENT ON TABLE "CTANNOTATION_TARGET_TABLE" IS 'Tables that can be targets for annotations.';
COMMENT ON COLUMN "CTANNOTATION_TARGET_TABLE"."PRIMARY_KEY_COLUMN" IS 'Name of the single-column primary key field in the target table used to validate ANNOTATIONS.TARGET_PRIMARY_KEY.';
COMMENT ON COLUMN "CTANNOTATION_TARGET_TABLE"."ANNOTATION_TARGET_TABLE" IS 'Table in the MCZbase schema that can be the target for an annotation record in annotations.  All upper case, e.g. TAXONOMY';
