
  CREATE TABLE "CTAREA_UNITS" 
   (	"AREA_UNITS" VARCHAR2(15) NOT NULL ENABLE, 
	 CONSTRAINT "CTAREA_UNITS_PK" PRIMARY KEY ("AREA_UNITS")
  USING INDEX  ENABLE
   ) ;
COMMENT ON TABLE "CTAREA_UNITS" IS 'Code table for units of area (length squared).';
