
  CREATE TABLE "CTATTRIBUTE_CODE_TABLES" 
   (	"ATTRIBUTE_TYPE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"VALUE_CODE_TABLE" VARCHAR2(60 CHAR), 
	"UNITS_CODE_TABLE" VARCHAR2(60 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CTATTRIBUTE_CODE_TABLES" ON "CTATTRIBUTE_CODE_TABLES" ("ATTRIBUTE_TYPE") 
  
ALTER TABLE "CTATTRIBUTE_CODE_TABLES" ADD CONSTRAINT "PK_CTATTRIBUTE_CODE_TABLES" PRIMARY KEY ("ATTRIBUTE_TYPE")
  USING INDEX "PK_CTATTRIBUTE_CODE_TABLES"  ENABLE