
  CREATE TABLE "CTATTRIBUTE_TYPE" 
   (	"ATTRIBUTE_TYPE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PK_CTATTRIBUTE_TYPE" PRIMARY KEY ("ATTRIBUTE_TYPE", "COLLECTION_CDE")
  USING INDEX  ENABLE
   ) 