
  CREATE TABLE "CTATTRIBUTE_CODE_TABLES" 
   (	"ATTRIBUTE_TYPE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"VALUE_CODE_TABLE" VARCHAR2(60 CHAR), 
	"UNITS_CODE_TABLE" VARCHAR2(60 CHAR), 
	 CONSTRAINT "PK_CTATTRIBUTE_CODE_TABLES" PRIMARY KEY ("ATTRIBUTE_TYPE")
  USING INDEX  ENABLE
   ) 