
  CREATE TABLE "CTATTRIBUTE_TYPE" 
   (	"ATTRIBUTE_TYPE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "CTATTRIBUTE_TYPE_FK1" FOREIGN KEY ("COLLECTION_CDE")
	  REFERENCES "COLLECTION" ("COLLECTION_CDE") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_CTATTRIBUTE_TYPE" ON "CTATTRIBUTE_TYPE" ("ATTRIBUTE_TYPE", "COLLECTION_CDE") 
  
ALTER TABLE "CTATTRIBUTE_TYPE" ADD CONSTRAINT "PK_CTATTRIBUTE_TYPE" PRIMARY KEY ("ATTRIBUTE_TYPE", "COLLECTION_CDE")
  USING INDEX "PK_CTATTRIBUTE_TYPE"  ENABLE