
  CREATE TABLE "CTAUTHOR_ROLE" 
   (	"AUTHOR_ROLE" VARCHAR2(60 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CTAUTHOR_ROLE" ON "CTAUTHOR_ROLE" ("AUTHOR_ROLE") 
  
ALTER TABLE "CTAUTHOR_ROLE" ADD CONSTRAINT "PK_CTAUTHOR_ROLE" PRIMARY KEY ("AUTHOR_ROLE")
  USING INDEX "PK_CTAUTHOR_ROLE"  ENABLE;
