
  CREATE TABLE "CTAUTHORSHIP_ROLE" 
   (	"AUTHORSHIP_ROLE" VARCHAR2(30) NOT NULL ENABLE, 
	"ORDINAL" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"NOMENCLATURAL_CODE" VARCHAR2(20), 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "CTATHORSHIP_ROLE_PK" PRIMARY KEY ("AUTHORSHIP_ROLE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CTAUTHORSHIP_ROLE_FK1" FOREIGN KEY ("NOMENCLATURAL_CODE")
	  REFERENCES "CTNOMENCLATURAL_CODE" ("NOMENCLATURAL_CODE") ENABLE
   ) 