
  CREATE TABLE "CTBORROW_STATUS" 
   (	"BORROW_STATUS" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTBORROW_STATUS" ON "CTBORROW_STATUS" ("BORROW_STATUS") 
  
ALTER TABLE "CTBORROW_STATUS" ADD CONSTRAINT "PKEY_CTBORROW_STATUS" PRIMARY KEY ("BORROW_STATUS")
  USING INDEX "PKEY_CTBORROW_STATUS"  ENABLE