
  CREATE TABLE "CTCASTE" 
   (	"COLLECTION_CDE" VARCHAR2(10), 
	"CASTE" VARCHAR2(60 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CTCASTE" ON "CTCASTE" ("COLLECTION_CDE", "CASTE") 
  
ALTER TABLE "CTCASTE" ADD CONSTRAINT "PK_CTCASTE" PRIMARY KEY ("COLLECTION_CDE", "CASTE")
  USING INDEX "PK_CTCASTE"  ENABLE