
  CREATE TABLE "CTCATALOG_NUMBER_PREFIX" 
   (	"CAT_NUM_PREFIX" VARCHAR2(10)
   ) 
  CREATE UNIQUE INDEX "PK_CAT_NUM_PREFIX" ON "CTCATALOG_NUMBER_PREFIX" ("CAT_NUM_PREFIX") 
  
ALTER TABLE "CTCATALOG_NUMBER_PREFIX" ADD CONSTRAINT "PK_CAT_NUM_PREFIX" PRIMARY KEY ("CAT_NUM_PREFIX")
  USING INDEX "PK_CAT_NUM_PREFIX"  ENABLE;
