
  CREATE TABLE "CTCATALOGED_ITEM_TYPE" 
   (	"CATALOGED_ITEM_TYPE" CHAR(2 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PK_CTCATALOGED_ITEM_TYPE" PRIMARY KEY ("CATALOGED_ITEM_TYPE")
  USING INDEX  ENABLE
   ) 