
  CREATE TABLE "CTCATALOGED_ITEM_TYPE" 
   (	"CATALOGED_ITEM_TYPE" CHAR(2 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CTCATALOGED_ITEM_TYPE" ON "CTCATALOGED_ITEM_TYPE" ("CATALOGED_ITEM_TYPE") 
  
ALTER TABLE "CTCATALOGED_ITEM_TYPE" ADD CONSTRAINT "PK_CTCATALOGED_ITEM_TYPE" PRIMARY KEY ("CATALOGED_ITEM_TYPE")
  USING INDEX "PK_CTCATALOGED_ITEM_TYPE"  ENABLE