
  CREATE TABLE "CTCF_LOAN_USE_TYPE" 
   (	"USE_TYPE" VARCHAR2(30) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_CTCF_LOAN_USE_TYPE" ON "CTCF_LOAN_USE_TYPE" ("USE_TYPE") 
  
ALTER TABLE "CTCF_LOAN_USE_TYPE" ADD CONSTRAINT "PK_CTCF_LOAN_USE_TYPE" PRIMARY KEY ("USE_TYPE")
  USING INDEX "PK_CTCF_LOAN_USE_TYPE"  ENABLE