
  CREATE TABLE "CTCITATION_TYPE_STATUS" 
   (	"TYPE_STATUS" VARCHAR2(60) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"CATEGORY" VARCHAR2(20) DEFAULT 'Voucher' NOT NULL ENABLE, 
	"ORDINAL" NUMBER(*,0) DEFAULT 3 NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCITATION_TYPE_STATUS" ON "CTCITATION_TYPE_STATUS" ("TYPE_STATUS") 
  
ALTER TABLE "CTCITATION_TYPE_STATUS" ADD CONSTRAINT "PKEY_CTCITATION_TYPE_STATUS" PRIMARY KEY ("TYPE_STATUS")
  USING INDEX "PKEY_CTCITATION_TYPE_STATUS"  ENABLE