
  CREATE TABLE "CTCLASS" 
   (	"PHYLCLASS" VARCHAR2(20 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCLASS" ON "CTCLASS" ("PHYLCLASS") 
  
ALTER TABLE "CTCLASS" ADD CONSTRAINT "PKEY_CTCLASS" PRIMARY KEY ("PHYLCLASS")
  USING INDEX "PKEY_CTCLASS"  ENABLE;
