
  CREATE TABLE "CTCOLLECTION_CDE" 
   (	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_CTCOLLECTION_CDE" ON "CTCOLLECTION_CDE" ("COLLECTION_CDE") 
  
ALTER TABLE "CTCOLLECTION_CDE" ADD CONSTRAINT "PK_CTCOLLECTION_CDE" PRIMARY KEY ("COLLECTION_CDE")
  USING INDEX "PK_CTCOLLECTION_CDE"  ENABLE;
