
  CREATE TABLE "CTCOLL_CONTACT_ROLE" 
   (	"CONTACT_ROLE" VARCHAR2(60 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_CTCOLL_CONTACT_ROLE" ON "CTCOLL_CONTACT_ROLE" ("CONTACT_ROLE") 
  
ALTER TABLE "CTCOLL_CONTACT_ROLE" ADD CONSTRAINT "PK_CTCOLL_CONTACT_ROLE" PRIMARY KEY ("CONTACT_ROLE")
  USING INDEX "PK_CTCOLL_CONTACT_ROLE"  ENABLE