
  CREATE TABLE "CTCOLLECTOR_ROLE" 
   (	"COLLECTOR_ROLE" CHAR(1 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCOLLECTOR_ROLE" ON "CTCOLLECTOR_ROLE" ("COLLECTOR_ROLE") 
  
ALTER TABLE "CTCOLLECTOR_ROLE" ADD CONSTRAINT "PKEY_CTCOLLECTOR_ROLE" PRIMARY KEY ("COLLECTOR_ROLE")
  USING INDEX "PKEY_CTCOLLECTOR_ROLE"  ENABLE