
  CREATE TABLE "CTCOLL_OBJ_DISP" 
   (	"COLL_OBJ_DISPOSITION" VARCHAR2(40 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCOLL_OBJ_DISP" ON "CTCOLL_OBJ_DISP" ("COLL_OBJ_DISPOSITION") 
  
ALTER TABLE "CTCOLL_OBJ_DISP" ADD CONSTRAINT "PKEY_CTCOLL_OBJ_DISP" PRIMARY KEY ("COLL_OBJ_DISPOSITION")
  USING INDEX "PKEY_CTCOLL_OBJ_DISP"  ENABLE;
