
  CREATE TABLE "CTCOUNTRY_CODE" 
   (	"CODE" VARCHAR2(3 CHAR) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(255) NOT NULL ENABLE, 
	 CONSTRAINT "CTCOUNTRY_CODE_PK" PRIMARY KEY ("COUNTRY")
  USING INDEX  ENABLE
   ) 