
  CREATE TABLE "CTCOLLECTING_SOURCE" 
   (	"COLLECTING_SOURCE" VARCHAR2(30 CHAR)
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCOLLECTING_SOURCE" ON "CTCOLLECTING_SOURCE" ("COLLECTING_SOURCE") 
  
ALTER TABLE "CTCOLLECTING_SOURCE" ADD CONSTRAINT "PKEY_CTCOLLECTING_SOURCE" PRIMARY KEY ("COLLECTING_SOURCE")
  USING INDEX "PKEY_CTCOLLECTING_SOURCE"  ENABLE