
  CREATE TABLE "CTCONTAINER_TYPE" 
   (	"CONTAINER_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCONTAINER_TYPE" ON "CTCONTAINER_TYPE" ("CONTAINER_TYPE") 
  
ALTER TABLE "CTCONTAINER_TYPE" ADD CONSTRAINT "PKEY_CTCONTAINER_TYPE" PRIMARY KEY ("CONTAINER_TYPE")
  USING INDEX "PKEY_CTCONTAINER_TYPE"  ENABLE