
  CREATE TABLE "CTCOLL_OTHER_ID_TYPE" 
   (	"OTHER_ID_TYPE" VARCHAR2(75 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"BASE_URL" VARCHAR2(4000 CHAR), 
	"ENCUMBER_AS_FIELD_NUM" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "PK_CTCOLL_OTHER_ID_TYPE" PRIMARY KEY ("OTHER_ID_TYPE")
  USING INDEX  ENABLE
   ) 