
  CREATE TABLE "CTCOLL_OBJECT_TYPE" 
   (	"COLL_OBJECT_TYPE" CHAR(2 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCOLL_OBJECT_TYPE" ON "CTCOLL_OBJECT_TYPE" ("COLL_OBJECT_TYPE") 
  
ALTER TABLE "CTCOLL_OBJECT_TYPE" ADD CONSTRAINT "PKEY_CTCOLL_OBJECT_TYPE" PRIMARY KEY ("COLL_OBJECT_TYPE")
  USING INDEX "PKEY_CTCOLL_OBJECT_TYPE"  ENABLE