
  CREATE TABLE "CTCORRESP_TYPE" 
   (	"CORRESP_TYPE" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCORRESP_TYPE" ON "CTCORRESP_TYPE" ("CORRESP_TYPE") 
  
ALTER TABLE "CTCORRESP_TYPE" ADD CONSTRAINT "PKEY_CTCORRESP_TYPE" PRIMARY KEY ("CORRESP_TYPE")
  USING INDEX "PKEY_CTCORRESP_TYPE"  ENABLE