
  CREATE TABLE "CTCOLL_OTHER_ID_TYPE" 
   (	"OTHER_ID_TYPE" VARCHAR2(75 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"BASE_URL" VARCHAR2(4000 CHAR), 
	"ENCUMBER_AS_FIELD_NUM" NUMBER DEFAULT 0 NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "IX_CTOTHER_ID_TYPE" ON "CTCOLL_OTHER_ID_TYPE" ("OTHER_ID_TYPE") 
  
ALTER TABLE "CTCOLL_OTHER_ID_TYPE" ADD CONSTRAINT "PK_CTCOLL_OTHER_ID_TYPE" PRIMARY KEY ("OTHER_ID_TYPE")
  USING INDEX "IX_CTOTHER_ID_TYPE"  ENABLE;
COMMENT ON COLUMN "CTCOLL_OTHER_ID_TYPE"."ENCUMBER_AS_FIELD_NUM" IS 'Mask from display if encumbrance mask original field number is applied.';
