
  CREATE TABLE "CTCONTAINER_TYPE_SIZE" 
   (	"CONTAINER_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"CONTAINER_SIZE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_CTCONTAINER_TYPE_SIZE" PRIMARY KEY ("CONTAINER_TYPE", "CONTAINER_SIZE")
  USING INDEX  ENABLE
   ) 