
  CREATE TABLE "CTCONTINENT" 
   (	"CONTINENT_OCEAN" VARCHAR2(45 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTCONTINENT" ON "CTCONTINENT" ("CONTINENT_OCEAN") 
  
ALTER TABLE "CTCONTINENT" ADD CONSTRAINT "PKEY_CTCONTINENT" PRIMARY KEY ("CONTINENT_OCEAN")
  USING INDEX "PKEY_CTCONTINENT"  ENABLE;
