
  CREATE TABLE "CTDEACC_TYPE" 
   (	"DEACC_TYPE" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTDEACCN_TYPE" ON "CTDEACC_TYPE" ("DEACC_TYPE") 
  
ALTER TABLE "CTDEACC_TYPE" ADD CONSTRAINT "PKEY_CTDEACCN_TYPE" PRIMARY KEY ("DEACC_TYPE")
  USING INDEX "PKEY_CTDEACCN_TYPE"  ENABLE;
