
  CREATE TABLE "CTDEACC_STATUS" 
   (	"DEACC_STATUS" VARCHAR2(25 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PK_DEACC_STATUS" PRIMARY KEY ("DEACC_STATUS")
  USING INDEX  ENABLE
   ) ;
COMMENT ON COLUMN "CTDEACC_STATUS"."DESCRIPTION" IS 'Definition of the deaccession status.';
COMMENT ON COLUMN "CTDEACC_STATUS"."DEACC_STATUS" IS 'Controlled vocabulary for status of a deaccession.';
