
  CREATE TABLE "CTEGG_NEST_COMBO" 
   (	"EGG_NEST_COMBO" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTEGG_NEST_COMBO" ON "CTEGG_NEST_COMBO" ("EGG_NEST_COMBO") 
  
ALTER TABLE "CTEGG_NEST_COMBO" ADD CONSTRAINT "PKEY_CTEGG_NEST_COMBO" PRIMARY KEY ("EGG_NEST_COMBO")
  USING INDEX "PKEY_CTEGG_NEST_COMBO"  ENABLE