
  CREATE TABLE "CTELECTRONIC_ADDR_TYPE" 
   (	"ADDRESS_TYPE" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTELECTRONIC_ADDR_TYPE" ON "CTELECTRONIC_ADDR_TYPE" ("ADDRESS_TYPE") 
  
ALTER TABLE "CTELECTRONIC_ADDR_TYPE" ADD CONSTRAINT "PKEY_CTELECTRONIC_ADDR_TYPE" PRIMARY KEY ("ADDRESS_TYPE")
  USING INDEX "PKEY_CTELECTRONIC_ADDR_TYPE"  ENABLE