
  CREATE TABLE "CTEW" 
   (	"E_OR_W" CHAR(1) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTEW" ON "CTEW" ("E_OR_W") 
  
ALTER TABLE "CTEW" ADD CONSTRAINT "PKEY_CTEW" PRIMARY KEY ("E_OR_W")
  USING INDEX "PKEY_CTEW"  ENABLE;
