
  CREATE TABLE "CTFLAG_YES_NO_UNKNOWN" 
   (	"STOREDVALUE" NUMBER(10,0) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTFLAG_YES_NO_UNKNOWN" ON "CTFLAG_YES_NO_UNKNOWN" ("STOREDVALUE") 
  
ALTER TABLE "CTFLAG_YES_NO_UNKNOWN" ADD CONSTRAINT "PKEY_CTFLAG_YES_NO_UNKNOWN" PRIMARY KEY ("STOREDVALUE")
  USING INDEX "PKEY_CTFLAG_YES_NO_UNKNOWN"  ENABLE