
  CREATE TABLE "CTFLAG_YES_NO" 
   (	"STOREDVALUE" NUMBER(10,0) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTFLAG_YES_NO" ON "CTFLAG_YES_NO" ("STOREDVALUE") 
  
ALTER TABLE "CTFLAG_YES_NO" ADD CONSTRAINT "PKEY_CTFLAG_YES_NO" PRIMARY KEY ("STOREDVALUE")
  USING INDEX "PKEY_CTFLAG_YES_NO"  ENABLE;
