
  CREATE TABLE "CTFOSSILIZATION_TYPE" 
   (	"FOSSILIZATION_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000)
   ) ;
COMMENT ON COLUMN "CTFOSSILIZATION_TYPE"."FOSSILIZATION_TYPE" IS 'A term describing the manner in which a specimen is fossilized.';
COMMENT ON COLUMN "CTFOSSILIZATION_TYPE"."DESCRIPTION" IS 'A definition for the term.';
