
  CREATE TABLE "CTGEOG_SOURCE_AUTHORITY" 
   (	"SOURCE_AUTHORITY" VARCHAR2(45 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTGEOG_SOURCE_AUTHORITY" ON "CTGEOG_SOURCE_AUTHORITY" ("SOURCE_AUTHORITY") 
  
ALTER TABLE "CTGEOG_SOURCE_AUTHORITY" ADD CONSTRAINT "PK_CTGEOG_SOURCE_AUTHORITY" PRIMARY KEY ("SOURCE_AUTHORITY")
  USING INDEX "PKEY_CTGEOG_SOURCE_AUTHORITY"  ENABLE;
