
  CREATE TABLE "CTGEOLOGY_ATTRIBUTES" 
   (	"GEOLOGY_ATTRIBUTE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(50) DEFAULT 'chronostratigraphic' NOT NULL ENABLE, 
	"ORDINAL" NUMBER DEFAULT 50 NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "CTGEOLOGY_ATTRIBUTE_NEW_PK" PRIMARY KEY ("GEOLOGY_ATTRIBUTE")
  USING INDEX  ENABLE
   ) 