
  CREATE TABLE "CTGEOG_SOURCE_AUTHORITY" 
   (	"SOURCE_AUTHORITY" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CTGEOG_SOURCE_AUTHORITY" PRIMARY KEY ("SOURCE_AUTHORITY")
  USING INDEX  ENABLE
   ) 