
  CREATE TABLE "CTHISTO_SECTION_ORIENT" 
   (	"SECTION_ORIENTATION" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	 PRIMARY KEY ("SECTION_ORIENTATION", "COLLECTION_CDE")
  USING INDEX  ENABLE
   ) ;
