
  CREATE TABLE "CTHISTO_STAIN_PROC" 
   (	"HISTO_STAIN_PROC" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	 PRIMARY KEY ("HISTO_STAIN_PROC", "COLLECTION_CDE")
  USING INDEX  ENABLE
   ) 