
  CREATE TABLE "CTID_MODIFIER" 
   (	"IDENTIFICATION_MODIFIER" VARCHAR2(15 CHAR)
   ) 
  CREATE UNIQUE INDEX "PKEY_CTID_MODIFIER" ON "CTID_MODIFIER" ("IDENTIFICATION_MODIFIER") 
  
ALTER TABLE "CTID_MODIFIER" ADD CONSTRAINT "PKEY_CTID_MODIFIER" PRIMARY KEY ("IDENTIFICATION_MODIFIER")
  USING INDEX "PKEY_CTID_MODIFIER"  ENABLE;
