
  CREATE TABLE "CTIMAGE_CONTENT_TYPE" 
   (	"IMAGE_CONTENT_TYPE" VARCHAR2(16 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTIMAGE_CONTENT_TYPE" ON "CTIMAGE_CONTENT_TYPE" ("IMAGE_CONTENT_TYPE") 
  
ALTER TABLE "CTIMAGE_CONTENT_TYPE" ADD CONSTRAINT "PKEY_CTIMAGE_CONTENT_TYPE" PRIMARY KEY ("IMAGE_CONTENT_TYPE")
  USING INDEX "PKEY_CTIMAGE_CONTENT_TYPE"  ENABLE