
  CREATE TABLE "CTIMAGE_OBJECT_TYPE" 
   (	"IMAGE_TYPE" VARCHAR2(11 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTIMAGE_OBJECT_TYPE" ON "CTIMAGE_OBJECT_TYPE" ("IMAGE_TYPE") 
  
ALTER TABLE "CTIMAGE_OBJECT_TYPE" ADD CONSTRAINT "PKEY_CTIMAGE_OBJECT_TYPE" PRIMARY KEY ("IMAGE_TYPE")
  USING INDEX "PKEY_CTIMAGE_OBJECT_TYPE"  ENABLE;
