
  CREATE TABLE "CTIMAGE_CONTENT_TYPE" 
   (	"IMAGE_CONTENT_TYPE" VARCHAR2(16 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTIMAGE_CONTENT_TYPE" PRIMARY KEY ("IMAGE_CONTENT_TYPE")
  USING INDEX  ENABLE
   ) 