
  CREATE TABLE "CTISLAND_GROUP" 
   (	"ISLAND_GROUP" VARCHAR2(50 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTISLAND_GROUP" ON "CTISLAND_GROUP" ("ISLAND_GROUP") 
  
ALTER TABLE "CTISLAND_GROUP" ADD CONSTRAINT "PKEY_CTISLAND_GROUP" PRIMARY KEY ("ISLAND_GROUP")
  USING INDEX "PKEY_CTISLAND_GROUP"  ENABLE