
  CREATE TABLE "CTJOURNAL_NAME" 
   (	"JOURNAL_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"SHORT_NAME" VARCHAR2(255), 
	"ISSN" VARCHAR2(255), 
	"START_YEAR" NUMBER, 
	"END_YEAR" NUMBER, 
	"REMARKS" VARCHAR2(2000)
   ) 
  CREATE UNIQUE INDEX "PK_CTJOURNAL_NAME" ON "CTJOURNAL_NAME" ("JOURNAL_NAME") 
  
ALTER TABLE "CTJOURNAL_NAME" ADD CONSTRAINT "PK_CTJOURNAL_NAME" PRIMARY KEY ("JOURNAL_NAME")
  USING INDEX "PK_CTJOURNAL_NAME"  ENABLE;
COMMENT ON COLUMN "CTJOURNAL_NAME"."JOURNAL_NAME" IS 'The full name of a journal.';
COMMENT ON COLUMN "CTJOURNAL_NAME"."SHORT_NAME" IS 'A short name or typical abbreviation for the journal.';
COMMENT ON COLUMN "CTJOURNAL_NAME"."ISSN" IS 'The ISSN for the journal';
COMMENT ON COLUMN "CTJOURNAL_NAME"."START_YEAR" IS 'Start Year Published.';
COMMENT ON COLUMN "CTJOURNAL_NAME"."END_YEAR" IS 'End year published.';
COMMENT ON COLUMN "CTJOURNAL_NAME"."REMARKS" IS 'Free text remarks about the journal.';
