
  CREATE TABLE "CTKARYO_STAIN_PROC" 
   (	"KARYO_STAIN_PROC" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTKARYO_STAIN_PROC" ON "CTKARYO_STAIN_PROC" ("KARYO_STAIN_PROC") 
  
ALTER TABLE "CTKARYO_STAIN_PROC" ADD CONSTRAINT "PKEY_CTKARYO_STAIN_PROC" PRIMARY KEY ("KARYO_STAIN_PROC")
  USING INDEX "PKEY_CTKARYO_STAIN_PROC"  ENABLE;
