
  CREATE TABLE "CTLAT_LONG_REF_SOURCE" 
   (	"LAT_LONG_REF_SOURCE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTLAT_LONG_REF_SOURCE" PRIMARY KEY ("LAT_LONG_REF_SOURCE")
  USING INDEX  ENABLE
   ) 