
  CREATE TABLE "CTLAT_LONG_REF_SOURCE" 
   (	"LAT_LONG_REF_SOURCE" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLAT_LONG_REF_SOURCE" ON "CTLAT_LONG_REF_SOURCE" ("LAT_LONG_REF_SOURCE") 
  
ALTER TABLE "CTLAT_LONG_REF_SOURCE" ADD CONSTRAINT "PKEY_CTLAT_LONG_REF_SOURCE" PRIMARY KEY ("LAT_LONG_REF_SOURCE")
  USING INDEX "PKEY_CTLAT_LONG_REF_SOURCE"  ENABLE;
