
  CREATE TABLE "CTLAT_LONG_ERROR_UNITS" 
   (	"LAT_LONG_ERROR_UNITS" VARCHAR2(2 CHAR)
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLAT_LONG_ERROR_UNITS" ON "CTLAT_LONG_ERROR_UNITS" ("LAT_LONG_ERROR_UNITS") 
  
ALTER TABLE "CTLAT_LONG_ERROR_UNITS" ADD CONSTRAINT "PKEY_CTLAT_LONG_ERROR_UNITS" PRIMARY KEY ("LAT_LONG_ERROR_UNITS")
  USING INDEX "PKEY_CTLAT_LONG_ERROR_UNITS"  ENABLE