
  CREATE TABLE "CTLAT_LONG_UNITS" 
   (	"ORIG_LAT_LONG_UNITS" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLAT_LONG_UNITS" ON "CTLAT_LONG_UNITS" ("ORIG_LAT_LONG_UNITS") 
  
ALTER TABLE "CTLAT_LONG_UNITS" ADD CONSTRAINT "PKEY_CTLAT_LONG_UNITS" PRIMARY KEY ("ORIG_LAT_LONG_UNITS")
  USING INDEX "PKEY_CTLAT_LONG_UNITS"  ENABLE;
