
  CREATE TABLE "CTLENGTH_UNITS" 
   (	"LENGTH_UNITS" VARCHAR2(2 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLENGTH_UNITS" ON "CTLENGTH_UNITS" ("LENGTH_UNITS") 
  
ALTER TABLE "CTLENGTH_UNITS" ADD CONSTRAINT "PKEY_CTLENGTH_UNITS" PRIMARY KEY ("LENGTH_UNITS")
  USING INDEX "PKEY_CTLENGTH_UNITS"  ENABLE;
