
  CREATE TABLE "CTLEXICAL_RELATIONSHIP" 
   (	"LEXICAL_RELATIONSHIP" VARCHAR2(30 CHAR)
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLEXICAL_RELATIONSHIP" ON "CTLEXICAL_RELATIONSHIP" ("LEXICAL_RELATIONSHIP") 
  
ALTER TABLE "CTLEXICAL_RELATIONSHIP" ADD CONSTRAINT "PKEY_CTLEXICAL_RELATIONSHIP" PRIMARY KEY ("LEXICAL_RELATIONSHIP")
  USING INDEX "PKEY_CTLEXICAL_RELATIONSHIP"  ENABLE