
  CREATE TABLE "CTLOAN_ITEM_STATE" 
   (	"LOAN_ITEM_STATE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	 CONSTRAINT "CTLOAN_ITEM_STATE_PK" PRIMARY KEY ("LOAN_ITEM_STATE")
  USING INDEX  ENABLE
   ) ;
COMMENT ON COLUMN "CTLOAN_ITEM_STATE"."LOAN_ITEM_STATE" IS 'Controlled vocabulary for the state of loan items.';
COMMENT ON COLUMN "CTLOAN_ITEM_STATE"."DESCRIPTION" IS 'Free text definition of the vocabulary term.';
