
  CREATE TABLE "CTLOCALITY_SECTION_PART" 
   (	"SECTION_PART" VARCHAR2(11 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLOCALITY_SECTION_PART" ON "CTLOCALITY_SECTION_PART" ("SECTION_PART") 
  
ALTER TABLE "CTLOCALITY_SECTION_PART" ADD CONSTRAINT "PKEY_CTLOCALITY_SECTION_PART" PRIMARY KEY ("SECTION_PART")
  USING INDEX "PKEY_CTLOCALITY_SECTION_PART"  ENABLE;
