
  CREATE TABLE "CTLOAN_STATUS" 
   (	"LOAN_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLOAN_STATUS" ON "CTLOAN_STATUS" ("LOAN_STATUS") 
  
ALTER TABLE "CTLOAN_STATUS" ADD CONSTRAINT "PKEY_CTLOAN_STATUS" PRIMARY KEY ("LOAN_STATUS")
  USING INDEX "PKEY_CTLOAN_STATUS"  ENABLE;
