
  CREATE TABLE "CTLOAN_ITEM_STATUS" 
   (	"LOAN_ITEM_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTLOAN_ITEM_STATUS" ON "CTLOAN_ITEM_STATUS" ("LOAN_ITEM_STATUS") 
  
ALTER TABLE "CTLOAN_ITEM_STATUS" ADD CONSTRAINT "PKEY_CTLOAN_ITEM_STATUS" PRIMARY KEY ("LOAN_ITEM_STATUS")
  USING INDEX "PKEY_CTLOAN_ITEM_STATUS"  ENABLE;
