
  CREATE TABLE "CTMCZP_PUBLICATION" 
   (	"PUBLICATION" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "CTMCZP_PUBLICATION_PK" ON "CTMCZP_PUBLICATION" ("PUBLICATION") 
  
ALTER TABLE "CTMCZP_PUBLICATION" ADD CONSTRAINT "CTMCZP_PUBLICATION_PK" PRIMARY KEY ("PUBLICATION")
  USING INDEX "CTMCZP_PUBLICATION_PK"  ENABLE