
  CREATE TABLE "CTMCZP_OTHERSUBJECT" 
   (	"OTHERSUBJECT" VARCHAR2(60) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "CTMCZP_OTHERSUBJECT_PK" ON "CTMCZP_OTHERSUBJECT" ("OTHERSUBJECT") 
  
ALTER TABLE "CTMCZP_OTHERSUBJECT" ADD CONSTRAINT "CTMCZP_OTHERSUBJECT_PK" PRIMARY KEY ("OTHERSUBJECT")
  USING INDEX "CTMCZP_OTHERSUBJECT_PK"  ENABLE