
  CREATE TABLE "CTMEDIA_TYPE" 
   (	"MEDIA_TYPE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) 
  CREATE UNIQUE INDEX "U_CTCTMEDIA_TYPE" ON "CTMEDIA_TYPE" ("MEDIA_TYPE") 
  
ALTER TABLE "CTMEDIA_TYPE" ADD CONSTRAINT "PK_CTMEDIA_TYPE" PRIMARY KEY ("MEDIA_TYPE")
  USING INDEX "U_CTCTMEDIA_TYPE"  ENABLE;
