
  CREATE TABLE "CTMEDIA_TYPE" 
   (	"MEDIA_TYPE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PK_CTMEDIA_TYPE" PRIMARY KEY ("MEDIA_TYPE")
  USING INDEX  ENABLE
   ) 