
  CREATE TABLE "CTMEDIA_RELATIONSHIP" 
   (	"MEDIA_RELATIONSHIP" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"LABEL" VARCHAR2(255), 
	"AUTO_TABLE" VARCHAR2(40)
   ) 
  CREATE UNIQUE INDEX "PK_CTMEDIA_RELATIONSHIP" ON "CTMEDIA_RELATIONSHIP" ("MEDIA_RELATIONSHIP") 
  
ALTER TABLE "CTMEDIA_RELATIONSHIP" ADD CONSTRAINT "PK_CTMEDIA_RELATIONSHIP" PRIMARY KEY ("MEDIA_RELATIONSHIP")
  USING INDEX "PK_CTMEDIA_RELATIONSHIP"  ENABLE