
  CREATE TABLE "CTMEDIA_LABEL" 
   (	"MEDIA_LABEL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000)
   ) 
  CREATE UNIQUE INDEX "U_MEDIA_LABEL" ON "CTMEDIA_LABEL" ("MEDIA_LABEL") 
  
ALTER TABLE "CTMEDIA_LABEL" ADD CONSTRAINT "PK_MEDIA_LABEL" PRIMARY KEY ("MEDIA_LABEL")
  USING INDEX "U_MEDIA_LABEL"  ENABLE