
  CREATE TABLE "CTMEDIA_LICENSE" 
   (	"MEDIA_LICENSE_ID" NUMBER NOT NULL ENABLE, 
	"DISPLAY" VARCHAR2(68 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"URI" VARCHAR2(255 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_MEDIA_LICENSE_ID" ON "CTMEDIA_LICENSE" ("MEDIA_LICENSE_ID") 
  
ALTER TABLE "CTMEDIA_LICENSE" ADD CONSTRAINT "PK_CTMEDIA_LICENSE" PRIMARY KEY ("MEDIA_LICENSE_ID")
  USING INDEX "PK_MEDIA_LICENSE_ID"  ENABLE