
  CREATE TABLE "CTMEDIA_RELATIONSHIP" 
   (	"MEDIA_RELATIONSHIP" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"LABEL" VARCHAR2(255), 
	"AUTO_TABLE" VARCHAR2(40), 
	 CONSTRAINT "PK_CTMEDIA_RELATIONSHIP" PRIMARY KEY ("MEDIA_RELATIONSHIP")
  USING INDEX  ENABLE
   ) 