
  CREATE TABLE "CTMEDIA_RELATIONSHIP" 
   (	"MEDIA_RELATIONSHIP" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CTMEDIA_RELATIONSHIP" PRIMARY KEY ("MEDIA_RELATIONSHIP")
  USING INDEX  ENABLE
   ) 