
  CREATE TABLE "CTMEDIA_LABEL" 
   (	"MEDIA_LABEL" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "PK_MEDIA_LABEL" PRIMARY KEY ("MEDIA_LABEL")
  USING INDEX  ENABLE
   ) 