
  CREATE TABLE "CTMIME_TYPE" 
   (	"MIME_TYPE" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_CTMIME_TYPE" ON "CTMIME_TYPE" ("MIME_TYPE") 
  
ALTER TABLE "CTMIME_TYPE" ADD CONSTRAINT "PK_CTMIME_TYPE" PRIMARY KEY ("MIME_TYPE")
  USING INDEX "PK_CTMIME_TYPE"  ENABLE;
