
  CREATE TABLE "CTMOTIVATION" 
   (	"MOTIVATION" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	 CONSTRAINT "CTMOTIVATION_PK" PRIMARY KEY ("MOTIVATION")
  USING INDEX  ENABLE
   ) ;
COMMENT ON COLUMN "CTMOTIVATION"."MOTIVATION" IS 'anno:Motivation instance';
COMMENT ON COLUMN "CTMOTIVATION"."DESCRIPTION" IS 'Description from W3C web annotation data model';
