
  CREATE TABLE "CTNATURE_OF_ID" 
   (	"NATURE_OF_ID" VARCHAR2(35 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PKEY_CTNATURE_OF_ID" PRIMARY KEY ("NATURE_OF_ID")
  USING INDEX  ENABLE
   ) 