
  CREATE TABLE "CTNOMENCLATURAL_CODE" 
   (	"NOMENCLATURAL_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	 CONSTRAINT "PK_CTNOMENCLATURAL_CODE" PRIMARY KEY ("NOMENCLATURAL_CODE")
  USING INDEX  ENABLE
   ) 