
  CREATE TABLE "CTNOMENCLATURAL_CODE" 
   (	"NOMENCLATURAL_CODE" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255), 
	"SORT_ORDER" NUMBER
   ) 
  CREATE UNIQUE INDEX "PK_CTNOMENCLATURAL_CODE" ON "CTNOMENCLATURAL_CODE" ("NOMENCLATURAL_CODE") 
  
ALTER TABLE "CTNOMENCLATURAL_CODE" ADD CONSTRAINT "PK_CTNOMENCLATURAL_CODE" PRIMARY KEY ("NOMENCLATURAL_CODE")
  USING INDEX "PK_CTNOMENCLATURAL_CODE"  ENABLE