
  CREATE TABLE "CTNS" 
   (	"N_OR_S" CHAR(1 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTNS" ON "CTNS" ("N_OR_S") 
  
ALTER TABLE "CTNS" ADD CONSTRAINT "PKEY_CTNS" PRIMARY KEY ("N_OR_S")
  USING INDEX "PKEY_CTNS"  ENABLE