
  CREATE TABLE "CTNUMERIC_AGE_UNITS" 
   (	"NUMERIC_AGE_UNITS" VARCHAR2(6 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTNUMERIC_AGE_UNITS" PRIMARY KEY ("NUMERIC_AGE_UNITS")
  USING INDEX  ENABLE
   ) 