
  CREATE TABLE "CTNUMERIC_AGE_UNITS" 
   (	"NUMERIC_AGE_UNITS" VARCHAR2(6 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTNUMERIC_AGE_UNITS" ON "CTNUMERIC_AGE_UNITS" ("NUMERIC_AGE_UNITS") 
  
ALTER TABLE "CTNUMERIC_AGE_UNITS" ADD CONSTRAINT "PKEY_CTNUMERIC_AGE_UNITS" PRIMARY KEY ("NUMERIC_AGE_UNITS")
  USING INDEX "PKEY_CTNUMERIC_AGE_UNITS"  ENABLE