
  CREATE TABLE "CTORIG_ELEV_UNITS" 
   (	"ORIG_ELEV_UNITS" VARCHAR2(2 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTORIG_ELEV_UNITS" ON "CTORIG_ELEV_UNITS" ("ORIG_ELEV_UNITS") 
  
ALTER TABLE "CTORIG_ELEV_UNITS" ADD CONSTRAINT "PKEY_CTORIG_ELEV_UNITS" PRIMARY KEY ("ORIG_ELEV_UNITS")
  USING INDEX "PKEY_CTORIG_ELEV_UNITS"  ENABLE