
  CREATE TABLE "CTPERMIT_TYPE" 
   (	"PERMIT_TYPE" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTPERMIT_TYPE" ON "CTPERMIT_TYPE" ("PERMIT_TYPE") 
  
ALTER TABLE "CTPERMIT_TYPE" ADD CONSTRAINT "PKEY_CTPERMIT_TYPE" PRIMARY KEY ("PERMIT_TYPE")
  USING INDEX "PKEY_CTPERMIT_TYPE"  ENABLE;
