
  CREATE TABLE "CTPROJECT_AGENT_ROLE" 
   (	"PROJECT_AGENT_ROLE" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTPROJECT_AGENT_ROLE" PRIMARY KEY ("PROJECT_AGENT_ROLE")
  USING INDEX  ENABLE
   ) 