
  CREATE TABLE "CTPREFIX" 
   (	"PREFIX" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTPREFIX" ON "CTPREFIX" ("PREFIX") 
  
ALTER TABLE "CTPREFIX" ADD CONSTRAINT "PKEY_CTPREFIX" PRIMARY KEY ("PREFIX")
  USING INDEX "PKEY_CTPREFIX"  ENABLE;
