
  CREATE TABLE "CTPROJECT_AGENT_ROLE" 
   (	"PROJECT_AGENT_ROLE" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTPROJECT_AGENT_ROLE" ON "CTPROJECT_AGENT_ROLE" ("PROJECT_AGENT_ROLE") 
  
ALTER TABLE "CTPROJECT_AGENT_ROLE" ADD CONSTRAINT "PKEY_CTPROJECT_AGENT_ROLE" PRIMARY KEY ("PROJECT_AGENT_ROLE")
  USING INDEX "PKEY_CTPROJECT_AGENT_ROLE"  ENABLE;
