
  CREATE TABLE "CTPUBLICATION_ATTRIBUTE" 
   (	"PUBLICATION_ATTRIBUTE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"CONTROL" VARCHAR2(40 CHAR), 
	 CONSTRAINT "PK_PUBLICATION_ATTRIBUTE" PRIMARY KEY ("PUBLICATION_ATTRIBUTE")
  USING INDEX  ENABLE
   ) 