
  CREATE TABLE "CTPUBLICATION_TYPE" 
   (	"PUBLICATION_TYPE" VARCHAR2(21 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTPUBLICATION_TYPE" ON "CTPUBLICATION_TYPE" ("PUBLICATION_TYPE") 
  
ALTER TABLE "CTPUBLICATION_TYPE" ADD CONSTRAINT "PKEY_CTPUBLICATION_TYPE" PRIMARY KEY ("PUBLICATION_TYPE")
  USING INDEX "PKEY_CTPUBLICATION_TYPE"  ENABLE