
  CREATE TABLE "CTPUBLICATION_ATTRIBUTE" 
   (	"PUBLICATION_ATTRIBUTE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"CONTROL" VARCHAR2(40 CHAR), 
	"MCZ_PUBLICATION_FG" NUMBER DEFAULT 0 NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_PUBLICATION_ATTRIBUTE" ON "CTPUBLICATION_ATTRIBUTE" ("PUBLICATION_ATTRIBUTE") 
  
ALTER TABLE "CTPUBLICATION_ATTRIBUTE" ADD CONSTRAINT "PK_PUBLICATION_ATTRIBUTE" PRIMARY KEY ("PUBLICATION_ATTRIBUTE")
  USING INDEX "PK_PUBLICATION_ATTRIBUTE"  ENABLE