
  CREATE TABLE "CTREFERENCERELATION" 
   (	"RELATIONSHIP" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTREFERENCERELATION" ON "CTREFERENCERELATION" ("RELATIONSHIP") 
  
ALTER TABLE "CTREFERENCERELATION" ADD CONSTRAINT "PKEY_CTREFERENCERELATION" PRIMARY KEY ("RELATIONSHIP")
  USING INDEX "PKEY_CTREFERENCERELATION"  ENABLE;
