
  CREATE TABLE "CTSECTION_TYPE" 
   (	"FIELD_NOTE_SECT_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTSECTION_TYPE" ON "CTSECTION_TYPE" ("FIELD_NOTE_SECT_TYPE") 
  
ALTER TABLE "CTSECTION_TYPE" ADD CONSTRAINT "PKEY_CTSECTION_TYPE" PRIMARY KEY ("FIELD_NOTE_SECT_TYPE")
  USING INDEX "PKEY_CTSECTION_TYPE"  ENABLE