
  CREATE TABLE "CTSHIPMENT_STATUS" 
   (	"SHIPMENT_STATUS" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTSHIPMENT_STATUS" ON "CTSHIPMENT_STATUS" ("SHIPMENT_STATUS") 
  
ALTER TABLE "CTSHIPMENT_STATUS" ADD CONSTRAINT "PKEY_CTSHIPMENT_STATUS" PRIMARY KEY ("SHIPMENT_STATUS")
  USING INDEX "PKEY_CTSHIPMENT_STATUS"  ENABLE;
