
  CREATE TABLE "CTSHIPPED_CARRIER_METHOD" 
   (	"SHIPPED_CARRIER_METHOD" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTSHIPPED_CARRIER_METHOD" PRIMARY KEY ("SHIPPED_CARRIER_METHOD")
  USING INDEX  ENABLE
   ) 