
  CREATE TABLE "CTSHIPPED_CARRIER_METHOD" 
   (	"SHIPPED_CARRIER_METHOD" VARCHAR2(30 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTSHIPPED_CARRIER_METHOD" ON "CTSHIPPED_CARRIER_METHOD" ("SHIPPED_CARRIER_METHOD") 
  
ALTER TABLE "CTSHIPPED_CARRIER_METHOD" ADD CONSTRAINT "PKEY_CTSHIPPED_CARRIER_METHOD" PRIMARY KEY ("SHIPPED_CARRIER_METHOD")
  USING INDEX "PKEY_CTSHIPPED_CARRIER_METHOD"  ENABLE;
