
  CREATE TABLE "CTSHIPMENT_CARRIER" 
   (	"SHIPMENT_CARRIER_CDE" VARCHAR2(25 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTSHIPMENT_CARRIER" ON "CTSHIPMENT_CARRIER" ("SHIPMENT_CARRIER_CDE") 
  
ALTER TABLE "CTSHIPMENT_CARRIER" ADD CONSTRAINT "PKEY_CTSHIPMENT_CARRIER" PRIMARY KEY ("SHIPMENT_CARRIER_CDE")
  USING INDEX "PKEY_CTSHIPMENT_CARRIER"  ENABLE