
  CREATE TABLE "CTSHIPMENT_CARRIER" 
   (	"SHIPMENT_CARRIER_CDE" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTSHIPMENT_CARRIER" PRIMARY KEY ("SHIPMENT_CARRIER_CDE")
  USING INDEX  ENABLE
   ) 