
  CREATE TABLE "CTSPECIFIC_PERMIT_TYPE" 
   (	"SPECIFIC_TYPE" VARCHAR2(255) NOT NULL ENABLE, 
	"PERMIT_TYPE" VARCHAR2(100), 
	"ACCN_SHOW_ON_SHIPMENT" NUMBER DEFAULT 1, 
	 CONSTRAINT "CTSPECIFIC_PERMIT_TYPE_PK" PRIMARY KEY ("SPECIFIC_TYPE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CTSPECIFIC_PERMIT_TYPE_FK1" FOREIGN KEY ("PERMIT_TYPE")
	  REFERENCES "CTPERMIT_TYPE" ("PERMIT_TYPE") ENABLE
   ) ;
COMMENT ON TABLE "CTSPECIFIC_PERMIT_TYPE" IS 'Controlled vocabulary for specific types of permissions and rights documents.';
COMMENT ON COLUMN "CTSPECIFIC_PERMIT_TYPE"."SPECIFIC_TYPE" IS 'Controlled Vocabulary';
COMMENT ON COLUMN "CTSPECIFIC_PERMIT_TYPE"."PERMIT_TYPE" IS 'More General Type';
COMMENT ON COLUMN "CTSPECIFIC_PERMIT_TYPE"."ACCN_SHOW_ON_SHIPMENT" IS 'If permit is on an accession it should be printable on all loan shippments of the material.';
