
  CREATE TABLE "CTSPECIMEN_PART_NAME" 
   (	"PART_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	"IS_TISSUE" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"CTSPNID" NUMBER NOT NULL ENABLE, 
	 PRIMARY KEY ("PART_NAME", "COLLECTION_CDE")
  USING INDEX  ENABLE
   ) ;
