
  CREATE TABLE "CTSPECPART_ATTRIBUTE_TYPE" 
   (	"ATTRIBUTE_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CTPECPART_ATTRIBUTE_TYPE" ON "CTSPECPART_ATTRIBUTE_TYPE" ("ATTRIBUTE_TYPE") 
  
ALTER TABLE "CTSPECPART_ATTRIBUTE_TYPE" ADD CONSTRAINT "PK_CTPECPART_ATTRIBUTE_TYPE" PRIMARY KEY ("ATTRIBUTE_TYPE")
  USING INDEX "PK_CTPECPART_ATTRIBUTE_TYPE"  ENABLE