
  CREATE TABLE "CTSPECIMEN_PRESERV_METHOD" 
   (	"PRESERVE_METHOD" VARCHAR2(50) NOT NULL ENABLE, 
	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 PRIMARY KEY ("PRESERVE_METHOD", "COLLECTION_CDE")
  USING INDEX  ENABLE
   ) ;
