
  CREATE TABLE "CTSUFFIX" 
   (	"SUFFIX" VARCHAR2(20 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTSUFFIX" ON "CTSUFFIX" ("SUFFIX") 
  
ALTER TABLE "CTSUFFIX" ADD CONSTRAINT "PKEY_CTSUFFIX" PRIMARY KEY ("SUFFIX")
  USING INDEX "PKEY_CTSUFFIX"  ENABLE;
