
  CREATE TABLE "CTTAXON_ATTRIBUTE_TYPE" 
   (	"TAXON_ATTRIBUTE_TYPE" VARCHAR2(60) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"HIDDEN_FG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	 CONSTRAINT "CTTAXON_ATTRIBUTE_TYPE_PK" PRIMARY KEY ("TAXON_ATTRIBUTE_TYPE")
  USING INDEX  ENABLE
   ) ;
COMMENT ON COLUMN "CTTAXON_ATTRIBUTE_TYPE"."HIDDEN_FG" IS 'Visibilith of the taxon attribute to the public, 0 for visible, 1 for internal users only.';
COMMENT ON COLUMN "CTTAXON_ATTRIBUTE_TYPE"."TAXON_ATTRIBUTE_TYPE" IS 'The type of taxon attribute';
COMMENT ON COLUMN "CTTAXON_ATTRIBUTE_TYPE"."DESCRIPTION" IS 'Text describing the nature of the taxon attribute.';
