
  CREATE TABLE "CTTAXONOMIC_AUTHORITY" 
   (	"SOURCE_AUTHORITY" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "PKEY_CTTAXONOMIC_AUTHORITY" PRIMARY KEY ("SOURCE_AUTHORITY")
  USING INDEX  ENABLE
   ) 