
  CREATE TABLE "CTTAXONOMIC_AUTHORITY" 
   (	"SOURCE_AUTHORITY" VARCHAR2(100) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000)
   ) 
  CREATE UNIQUE INDEX "PKEY_CTTAXONOMIC_AUTHORITY" ON "CTTAXONOMIC_AUTHORITY" ("SOURCE_AUTHORITY") 
  
ALTER TABLE "CTTAXONOMIC_AUTHORITY" ADD CONSTRAINT "PKEY_CTTAXONOMIC_AUTHORITY" PRIMARY KEY ("SOURCE_AUTHORITY")
  USING INDEX "PKEY_CTTAXONOMIC_AUTHORITY"  ENABLE;
