
  CREATE TABLE "CTTAXON_STATUS" 
   (	"TAXON_STATUS" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_CTTAXON_STATUS" ON "CTTAXON_STATUS" ("TAXON_STATUS") 
  
ALTER TABLE "CTTAXON_STATUS" ADD CONSTRAINT "PK_CTTAXON_STATUS" PRIMARY KEY ("TAXON_STATUS")
  USING INDEX "PK_CTTAXON_STATUS"  ENABLE