
  CREATE TABLE "CTTAXON_RELATION" 
   (	"TAXON_RELATIONSHIP" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"INVERSE_RELATION" VARCHAR2(40), 
	 CONSTRAINT "CTTAXON_RELATION_PK" PRIMARY KEY ("TAXON_RELATIONSHIP")
  USING INDEX  ENABLE
   ) 