
  CREATE TABLE "CTTAXA_FORMULA" 
   (	"TAXA_FORMULA" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "CTTAXA_FORMULA_PK" PRIMARY KEY ("TAXA_FORMULA")
  USING INDEX  ENABLE
   ) 