
  CREATE TABLE "CTTAXON_STATUS" 
   (	"TAXON_STATUS" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PK_CTTAXON_STATUS" PRIMARY KEY ("TAXON_STATUS")
  USING INDEX  ENABLE
   ) 