
  CREATE TABLE "CTTAXON_HABITAT" 
   (	"TAXON_HABITAT" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "U_TAXONHAB" UNIQUE ("TAXON_HABITAT")
  USING INDEX  ENABLE
   ) ;
