
  CREATE TABLE "CTTHICKNESS_UNITS" 
   (	"THICKNESS_UNITS" VARCHAR2(15 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PKEY_CTTHICKNESS_UNITS" PRIMARY KEY ("THICKNESS_UNITS")
  USING INDEX  ENABLE
   ) ;
COMMENT ON TABLE "CTTHICKNESS_UNITS" IS 'Deprecated table, use CTLENGTH_UNITS for linear units.';
