
  CREATE TABLE "CTTRANSACTION_TYPE" 
   (	"TRANSACTION_TYPE" VARCHAR2(18 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTTRANSACTION_TYPE" ON "CTTRANSACTION_TYPE" ("TRANSACTION_TYPE") 
  
ALTER TABLE "CTTRANSACTION_TYPE" ADD CONSTRAINT "PKEY_CTTRANSACTION_TYPE" PRIMARY KEY ("TRANSACTION_TYPE")
  USING INDEX "PKEY_CTTRANSACTION_TYPE"  ENABLE;
