
  CREATE TABLE "CTTRANS_AGENT_ROLE" 
   (	"TRANS_AGENT_ROLE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "CTTRANS_AGENT_ROLE_PK" PRIMARY KEY ("TRANS_AGENT_ROLE")
  USING INDEX  ENABLE
   ) 