
  CREATE TABLE "CTUNDERSCORE_COLL_CIT_TYPE" 
   (	"TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "CTUNDERSCORE_COLL_CIT_TYPE_PK" PRIMARY KEY ("TYPE")
  USING INDEX  ENABLE
   ) 