
  CREATE TABLE "CTUNDERSCORE_COLL_AGENT_ROLE" 
   (	"ROLE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"ORDINAL" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"LABEL" VARCHAR2(50), 
	"INVERSE_LABEL" VARCHAR2(50), 
	 CONSTRAINT "CT_UNDERSCORE_COLL_AGENT_R_PK" PRIMARY KEY ("ROLE")
  USING INDEX  ENABLE
   ) ;
COMMENT ON COLUMN "CTUNDERSCORE_COLL_AGENT_ROLE"."ROLE" IS 'Role an agent can have in a relationship to an underscore_collection, e.g PI for grants.';
COMMENT ON COLUMN "CTUNDERSCORE_COLL_AGENT_ROLE"."DESCRIPTION" IS 'Definition of role';
COMMENT ON COLUMN "CTUNDERSCORE_COLL_AGENT_ROLE"."ORDINAL" IS 'Sort order for display of relationships.';
COMMENT ON COLUMN "CTUNDERSCORE_COLL_AGENT_ROLE"."LABEL" IS 'Label to display in form: named group-label-agent.';
COMMENT ON COLUMN "CTUNDERSCORE_COLL_AGENT_ROLE"."INVERSE_LABEL" IS 'Label to display in form: agent-label-named group.';
