
  CREATE TABLE "CTUNDERSCORE_COLLECTION_TYPE" 
   (	"UNDERSCORE_COLLECTION_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000), 
	"ALLOWED_AGENT_ROLES" VARCHAR2(4000), 
	 CONSTRAINT "CTUNDERSCORE_COLLECTION_TY_PK" PRIMARY KEY ("UNDERSCORE_COLLECTION_TYPE")
  USING INDEX  ENABLE
   ) 