
  CREATE TABLE "CTUNDERSCORE_COLL_AGENT_ROLE" 
   (	"ROLE" VARCHAR2(50) NOT NULL ENABLE, 
	"DISALLOWED_TYPES" VARCHAR2(900), 
	 CONSTRAINT "CT_UNDERSCORE_COLL_AGENT_R_PK" PRIMARY KEY ("ROLE")
  USING INDEX  ENABLE
   ) 