
  CREATE TABLE "CTUNDERSCORE_COLLECTION_TYPE" 
   (	"UNDERSCORE_COLLECTION_TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000), 
	"ALLOWED_AGENT_ROLES" VARCHAR2(4000), 
	 CONSTRAINT "CTUNDERSCORE_COLLECTION_TY_PK" PRIMARY KEY ("UNDERSCORE_COLLECTION_TYPE")
  USING INDEX  ENABLE
   ) ;
COMMENT ON COLUMN "CTUNDERSCORE_COLLECTION_TYPE"."UNDERSCORE_COLLECTION_TYPE" IS 'Type of named group';
COMMENT ON COLUMN "CTUNDERSCORE_COLLECTION_TYPE"."DESCRIPTION" IS 'Brief descriptive title for this type of named group. ';
COMMENT ON COLUMN "CTUNDERSCORE_COLLECTION_TYPE"."ALLOWED_AGENT_ROLES" IS 'Agent roles that can be used with this type of underscore collection, e.g. PI For for grants.';
