
  CREATE TABLE "CTUNDERSCORE_COLL_CIT_TYPE" 
   (	"TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	 CONSTRAINT "CTUNDERSCORE_COLL_CIT_TYPE_PK" PRIMARY KEY ("TYPE")
  USING INDEX  ENABLE
   ) ;
COMMENT ON COLUMN "CTUNDERSCORE_COLL_CIT_TYPE"."TYPE" IS 'controlled vocabulary for underscore_collection_citation.type';
COMMENT ON COLUMN "CTUNDERSCORE_COLL_CIT_TYPE"."DESCRIPTION" IS 'text defining the type';
