
  CREATE TABLE "CTURL_TYPE" 
   (	"URL_TYPE" VARCHAR2(10 CHAR)
   ) 
  CREATE UNIQUE INDEX "PKEY_CTURL_TYPE" ON "CTURL_TYPE" ("URL_TYPE") 
  
ALTER TABLE "CTURL_TYPE" ADD CONSTRAINT "PKEY_CTURL_TYPE" PRIMARY KEY ("URL_TYPE")
  USING INDEX "PKEY_CTURL_TYPE"  ENABLE