
  CREATE TABLE "CTWATER_FEATURE" 
   (	"WATER_FEATURE" VARCHAR2(50) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "CTWATER_FEATURE_INDEX1" ON "CTWATER_FEATURE" ("WATER_FEATURE") 
  
ALTER TABLE "CTWATER_FEATURE" ADD CONSTRAINT "CTWATER_FEATURE_PK" PRIMARY KEY ("WATER_FEATURE")
  USING INDEX "CTWATER_FEATURE_INDEX1"  ENABLE;
