
  CREATE TABLE "CTWEIGHT_UNITS" 
   (	"WEIGHT_UNITS" VARCHAR2(15 CHAR) NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_CTWEIGHT_UNITS" ON "CTWEIGHT_UNITS" ("WEIGHT_UNITS") 
  
ALTER TABLE "CTWEIGHT_UNITS" ADD CONSTRAINT "PKEY_CTWEIGHT_UNITS" PRIMARY KEY ("WEIGHT_UNITS")
  USING INDEX "PKEY_CTWEIGHT_UNITS"  ENABLE