
  CREATE TABLE "DGR_LOCATOR" 
   (	"LOCATOR_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"FREEZER" NUMBER NOT NULL ENABLE, 
	"RACK" NUMBER NOT NULL ENABLE, 
	"BOX" NUMBER NOT NULL ENABLE, 
	"PLACE" NUMBER NOT NULL ENABLE, 
	"NK" NUMBER, 
	"TISSUE_TYPE" VARCHAR2(255 CHAR)
   ) 