
  CREATE TABLE "DOWNLOAD_PROFILE" 
   (	"DOWNLOAD_PROFILE_ID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
	"SHARING" VARCHAR2(20) DEFAULT 'Self' NOT NULL ENABLE, 
	"TARGET_SEARCH" VARCHAR2(20) DEFAULT 'Specimens' NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) WITH TIME ZONE, 
	"COLUMN_LIST" VARCHAR2(4000) DEFAULT 'GUID,SCIENTIFIC_NAME,AUTHOR_TEXT,SPEC_LOCALITY,COUNTRY_CODE,DEC_LAT,DEC_LONG,DATUM,COORDINATEUNCERTAINTYINMETERS,BEGAN_DATE,ENDED_DATE' NOT NULL ENABLE, 
	 CONSTRAINT "DOWNLOAD_PROFILE_PK" PRIMARY KEY ("DOWNLOAD_PROFILE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "DOWNLOAD_PROFILE_CHK1" CHECK (sharing in ('Self','MCZ','Everyone')) ENABLE
   ) 