
  CREATE TABLE "DR$FLAT_TEXT_INDEX$I" 
   (	"TOKEN_TEXT" VARCHAR2(255) NOT NULL ENABLE, 
	"TOKEN_TYPE" NUMBER(10,0) NOT NULL ENABLE, 
	"TOKEN_FIRST" NUMBER(10,0) NOT NULL ENABLE, 
	"TOKEN_LAST" NUMBER(10,0) NOT NULL ENABLE, 
	"TOKEN_COUNT" NUMBER(10,0) NOT NULL ENABLE, 
	"TOKEN_INFO" BLOB
   ) 
  MONITORING ;
