
  CREATE TABLE "DUPEPARTS" 
   (	"COLLECTION_CDE" VARCHAR2(2), 
	"OTHER_ID_NUMBER" VARCHAR2(6), 
	"CONTAINER_BARCODE" VARCHAR2(13), 
	"PART_NAME" VARCHAR2(12), 
	"PRESERVE_METHOD" VARCHAR2(6), 
	"CURRENT_REMARKS" VARCHAR2(37)
   ) 