
  CREATE TABLE "ENCUMBRANCE" 
   (	"ENCUMBRANCE_ID" NUMBER NOT NULL ENABLE, 
	"ENCUMBERING_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"EXPIRATION_DATE" DATE, 
	"EXPIRATION_EVENT" VARCHAR2(60 CHAR), 
	"ENCUMBRANCE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"MADE_DATE" DATE, 
	"REMARKS" VARCHAR2(255 CHAR), 
	"ENCUMBRANCE_ACTION" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ENCUMBRANCE" PRIMARY KEY ("ENCUMBRANCE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_ENCUMB_AGENT" FOREIGN KEY ("ENCUMBERING_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 