
  CREATE TABLE "EXTERNAL_RESOURCE_RELATION" 
   (	"EXTERNAL_RESOURCE_RELATION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"RESOURCE_RELATIONSHIP_ID" VARCHAR2(255) NOT NULL ENABLE, 
	"RELATIONSHIP_OF_RESOURCE" VARCHAR2(255) DEFAULT 'Same Occurrence As' NOT NULL ENABLE, 
	"RELATED_RESOURCE_ID" VARCHAR2(900) NOT NULL ENABLE, 
	"RELATED_RESOURCE_LINK" VARCHAR2(4000), 
	"ACCORDING_TO_AGENT_ID" NUMBER, 
	"ACCORDING_TO_PUBLICATION_ID" NUMBER, 
	"ESTABLISHED_DATE" DATE, 
	"RELATIONSHIP_REMARKS" VARCHAR2(4000), 
	"TIMESTAMP_CREATED" TIMESTAMP (6) NOT NULL ENABLE, 
	"CREATED_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"DATE_LAST_MODIFIED" TIMESTAMP (6), 
	"LAST_MODIFIED_BY_AGENT_ID" NUMBER, 
	 CONSTRAINT "EXTERNAL_RESOURCE_RELATION_PK" PRIMARY KEY ("EXTERNAL_RESOURCE_RELATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "EXTERNAL_RESOURCE_RELATIO_UK1" UNIQUE ("RESOURCE_RELATIONSHIP_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK1_ACCORDING_TO_AGENT_ID" FOREIGN KEY ("ACCORDING_TO_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK2_CREATED_BY_AGENT_ID" FOREIGN KEY ("CREATED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK3_ACCORDING_TO_PUB_ID" FOREIGN KEY ("ACCORDING_TO_PUBLICATION_ID")
	  REFERENCES "PUBLICATION" ("PUBLICATION_ID") ENABLE, 
	 CONSTRAINT "FK4_MODIIFIED_BY_AGENT_ID" FOREIGN KEY ("LAST_MODIFIED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK5_SUBJECT_COLLECTION_OBJECT" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE
   ) 