
  CREATE TABLE "FED_SHAPES" 
   (	"ID" NUMBER(38,0), 
	"AGENCY" VARCHAR2(30), 
	"UNIT_NAME" VARCHAR2(100), 
	"LINK" VARCHAR2(50), 
	"GLOBALID" VARCHAR2(38), 
	"GEOM" "MDSYS"."SDO_GEOMETRY" 
   ) 
 VARRAY "GEOM"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "GEOM"."SDO_ORDINATES" STORE AS SECUREFILE LOB 