
  CREATE TABLE "FEDERAL_LAND_SHAPES" 
   (	"AGENCY" VARCHAR2(30), 
	"UNIT_NAME" VARCHAR2(100), 
	"LINK" VARCHAR2(50), 
	"GEOM" "MDSYS"."SDO_GEOMETRY" , 
	"ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FEDERAL_LAND_SHAPES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) 
 VARRAY "GEOM"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "GEOM"."SDO_ORDINATES" STORE AS SECUREFILE LOB 