
  CREATE TABLE "FLAT" 
   (	"COLLECTION_OBJECT_ID" NUMBER, 
	"CAT_NUM" VARCHAR2(40 CHAR), 
	"ACCN_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"INSTITUTION_ACRONYM" VARCHAR2(20 CHAR), 
	"COLLECTION_CDE" VARCHAR2(10), 
	"COLLECTION" VARCHAR2(30 CHAR), 
	"COLLECTING_EVENT_ID" NUMBER, 
	"DATE_BEGAN_DATE" DATE, 
	"DATE_ENDED_DATE" DATE, 
	"VERBATIM_DATE" VARCHAR2(60 CHAR), 
	"LAST_EDIT_DATE" DATE, 
	"INDIVIDUALCOUNT" NUMBER, 
	"COLL_OBJ_DISPOSITION" VARCHAR2(4000), 
	"COLLECTORS" VARCHAR2(4000 CHAR), 
	"FIELD_NUM" VARCHAR2(4000 CHAR), 
	"OTHERCATALOGNUMBERS" VARCHAR2(4000 CHAR), 
	"GENBANKNUM" VARCHAR2(4000 CHAR), 
	"RELATEDCATALOGEDITEMS" VARCHAR2(4000 CHAR), 
	"TYPESTATUS" VARCHAR2(4000 CHAR), 
	"SEX" VARCHAR2(4000 CHAR), 
	"PARTS" VARCHAR2(4000 CHAR), 
	"ENCUMBRANCES" VARCHAR2(4000 CHAR), 
	"ACCESSION" VARCHAR2(81 CHAR), 
	"GEOG_AUTH_REC_ID" NUMBER, 
	"HIGHER_GEOG" VARCHAR2(255 CHAR), 
	"CONTINENT_OCEAN" VARCHAR2(70 CHAR), 
	"COUNTRY" VARCHAR2(70 CHAR), 
	"STATE_PROV" VARCHAR2(75 CHAR), 
	"COUNTY" VARCHAR2(50 CHAR), 
	"FEATURE" VARCHAR2(50 CHAR), 
	"ISLAND" VARCHAR2(50 CHAR), 
	"ISLAND_GROUP" VARCHAR2(50 CHAR), 
	"QUAD" VARCHAR2(30 CHAR), 
	"SEA" VARCHAR2(50 CHAR), 
	"LOCALITY_ID" NUMBER, 
	"SPEC_LOCALITY" VARCHAR2(400 CHAR), 
	"MINIMUM_ELEVATION" NUMBER, 
	"MAXIMUM_ELEVATION" NUMBER, 
	"ORIG_ELEV_UNITS" VARCHAR2(2 CHAR), 
	"MIN_ELEV_IN_M" NUMBER, 
	"MAX_ELEV_IN_M" NUMBER, 
	"DEC_LAT" NUMBER(12,10), 
	"DEC_LONG" NUMBER(13,10), 
	"DATUM" VARCHAR2(55 CHAR), 
	"ORIG_LAT_LONG_UNITS" VARCHAR2(20 CHAR), 
	"VERBATIMLATITUDE" VARCHAR2(127 CHAR), 
	"VERBATIMLONGITUDE" VARCHAR2(127 CHAR), 
	"LAT_LONG_REF_SOURCE" VARCHAR2(500), 
	"COORDINATEUNCERTAINTYINMETERS" NUMBER, 
	"GEOREFMETHOD" VARCHAR2(255 CHAR), 
	"LAT_LONG_REMARKS" VARCHAR2(4000 CHAR), 
	"LAT_LONG_DETERMINER" VARCHAR2(184 CHAR), 
	"IDENTIFICATION_ID" NUMBER, 
	"SCIENTIFIC_NAME" VARCHAR2(255 CHAR), 
	"IDENTIFIEDBY" VARCHAR2(4000 CHAR), 
	"DATE_MADE_DATE" DATE, 
	"REMARKS" VARCHAR2(4000 CHAR), 
	"HABITAT" VARCHAR2(4000 CHAR), 
	"ASSOCIATED_SPECIES" VARCHAR2(4000 CHAR), 
	"TAXA_FORMULA" VARCHAR2(25 CHAR), 
	"FULL_TAXON_NAME" VARCHAR2(4000 CHAR), 
	"PHYLCLASS" VARCHAR2(4000 CHAR), 
	"KINGDOM" VARCHAR2(4000 CHAR), 
	"PHYLUM" VARCHAR2(4000 CHAR), 
	"PHYLORDER" VARCHAR2(4000 CHAR), 
	"FAMILY" VARCHAR2(4000 CHAR), 
	"GENUS" VARCHAR2(4000 CHAR), 
	"SPECIES" VARCHAR2(4000 CHAR), 
	"SUBSPECIES" VARCHAR2(4000 CHAR), 
	"AUTHOR_TEXT" VARCHAR2(4000 CHAR), 
	"NOMENCLATURAL_CODE" VARCHAR2(4000 CHAR), 
	"INFRASPECIFIC_RANK" VARCHAR2(4000 CHAR), 
	"IDENTIFICATIONMODIFIER" CHAR(1 CHAR), 
	"GUID" VARCHAR2(67 CHAR), 
	"BASISOFRECORD" VARCHAR2(17 CHAR), 
	"DEPTH_UNITS" VARCHAR2(20 CHAR), 
	"MIN_DEPTH" NUMBER, 
	"MAX_DEPTH" NUMBER, 
	"MIN_DEPTH_IN_M" NUMBER, 
	"MAX_DEPTH_IN_M" NUMBER, 
	"COLLECTING_METHOD" VARCHAR2(255 CHAR), 
	"COLLECTING_SOURCE" VARCHAR2(30), 
	"DAYOFYEAR" NUMBER, 
	"AGE_CLASS" VARCHAR2(4000 CHAR), 
	"ATTRIBUTES" VARCHAR2(4000 CHAR), 
	"VERIFICATIONSTATUS" VARCHAR2(40 CHAR), 
	"SPECIMENDETAILURL" VARCHAR2(255 CHAR), 
	"IMAGEURL" VARCHAR2(4000), 
	"FIELDNOTESURL" VARCHAR2(121 CHAR), 
	"CATALOGNUMBERTEXT" VARCHAR2(40 CHAR), 
	"COLLECTORNUMBER" VARCHAR2(4000 CHAR), 
	"VERBATIMELEVATION" VARCHAR2(84 CHAR), 
	"YEAR" NUMBER, 
	"MONTH" NUMBER, 
	"DAY" NUMBER, 
	"STALE_FLAG" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"LASTUSER" VARCHAR2(38 CHAR), 
	"LASTDATE" DATE, 
	"PARTDETAIL" VARCHAR2(4000 CHAR), 
	"BEGAN_DATE" VARCHAR2(22 CHAR), 
	"ENDED_DATE" VARCHAR2(22 CHAR), 
	"ID_SENSU" VARCHAR2(255 CHAR), 
	"PREPARATORS" VARCHAR2(4000 CHAR), 
	"ISO_BEGAN_DATE" VARCHAR2(22 CHAR), 
	"ISO_ENDED_DATE" VARCHAR2(22 CHAR), 
	"CAT_NUM_PREFIX" VARCHAR2(60 CHAR), 
	"CAT_NUM_INTEGER" NUMBER, 
	"CAT_NUM_SUFFIX" VARCHAR2(60 CHAR), 
	"TOTAL_PARTS" NUMBER(10,0), 
	"CITED_AS" VARCHAR2(4000 CHAR), 
	"EARLIESTERAORLOWESTERATHEM" VARCHAR2(100), 
	"LATESTERAORHIGHESTERATHEM" VARCHAR2(100), 
	"EARLIESTPERIODORLOWESTSYSTEM" VARCHAR2(100), 
	"LATESTPERIODORHIGHESTSYSTEM" VARCHAR2(100), 
	"EARLIESTEPOCHORLOWESTSERIES" VARCHAR2(100), 
	"LATESTEPOCHORHIGHESTSERIES" VARCHAR2(100), 
	"EARLIESTAGEORLOWESTSTAGE" VARCHAR2(100), 
	"LATESTAGEORHIGHESTSTAGE" VARCHAR2(100), 
	"LITHOSTRATIGRAPHICTERMS" VARCHAR2(900), 
	"GEOL_GROUP" VARCHAR2(100), 
	"FORMATION" VARCHAR2(100), 
	"MEMBER" VARCHAR2(100), 
	"BED" VARCHAR2(100), 
	"ASSOCIATED_COLLECTION" NUMBER(10,0), 
	"COLLECTING_TIME" VARCHAR2(50 CHAR), 
	"ATTRIBUTES_JSON" VARCHAR2(4000 CHAR) DEFAULT '', 
	"TYPESTATUSWORDS" VARCHAR2(255), 
	"TYPESTATUSPLAIN" VARCHAR2(500), 
	"VERBATIMLOCALITY" VARCHAR2(4000), 
	"MASK_RECORD" NUMBER(1,0), 
	"ASSOCIATEDSEQUENCES" VARCHAR2(4000 CHAR), 
	"TOPTYPESTATUSKIND" VARCHAR2(60 CHAR), 
	"COUNTRYCODE" VARCHAR2(3), 
	"WATER_FEATURE" VARCHAR2(50), 
	"CONTINENT" VARCHAR2(70), 
	"WATERBODY" VARCHAR2(70), 
	"RECATALOGED_FG" NUMBER(1,0), 
	"INDEXCOL" CHAR(1), 
	"LOCALITY_REMARKS" VARCHAR2(4000 CHAR), 
	"MADE_DATE" VARCHAR2(22 CHAR), 
	"TAXONID" VARCHAR2(900), 
	"SCIENTIFICNAMEID" VARCHAR2(900), 
	"HIGHERGEOGRAPHYID" VARCHAR2(900), 
	"RECORDEDBYID" VARCHAR2(900), 
	"IDENTIFIEDBYID" VARCHAR2(900), 
	"GEOREFERENCEDBYID" VARCHAR2(900), 
	"IMAGEURLFILTERED" VARCHAR2(4000), 
	"STORED_AS" VARCHAR2(255 CHAR), 
	"TOPTYPESTATUS" VARCHAR2(60), 
	"SOVEREIGN_NATION" VARCHAR2(255), 
	"ROOMS" VARCHAR2(4000), 
	"CABINETS" VARCHAR2(4000), 
	"DRAWERS" VARCHAR2(4000), 
	"SUBFAMILY" VARCHAR2(4000), 
	"TRIBE" VARCHAR2(4000), 
	"SUBPHYLUM" VARCHAR2(4000), 
	"SUBCLASS" VARCHAR2(4000), 
	"SUPERORDER" VARCHAR2(4000), 
	"INFRACLASS" VARCHAR2(4000), 
	"SUBORDER" VARCHAR2(4000), 
	"INFRAORDER" VARCHAR2(4000), 
	"SUPERFAMILY" VARCHAR2(4000), 
	"COORDINATE_PRECISION" NUMBER, 
	"POINTRADIUSSPATIALFIT" NUMBER, 
	"VERBATIMSRS" VARCHAR2(4000), 
	"EARLIESTEONORLOWESTEONOTHEM" VARCHAR2(100), 
	"LATESTEONORHIGHESTEONOTHEM" VARCHAR2(100), 
	"RECEIVED_FROM" VARCHAR2(4000), 
	"ACCESSION_DATE" DATE, 
	"RECEIVED_DATE" DATE
   ) 
  PARTITION BY LIST ("COLLECTION_ID") 
 (PARTITION "MCZ_HERP"  VALUES (1) , 
 PARTITION "MCZ_MAMM"  VALUES (2) , 
 PARTITION "MCZ_MALA"  VALUES (3) , 
 PARTITION "MCZ_FISH"  VALUES (4) , 
 PARTITION "MCZ_BIRD"  VALUES (5) , 
 PARTITION "MCZ_VP"  VALUES (6) , 
 PARTITION "MCZ_IP"  VALUES (7) , 
 PARTITION "MCZ_IZ"  VALUES (8) , 
 PARTITION "MCZ_ENT"  VALUES (9) , 
 PARTITION "MCZ_SC"  VALUES (10) , 
 PARTITION "MCZ_CRYO"  VALUES (11) , 
 PARTITION "MCZ_MCZ"  VALUES (12) , 
 PARTITION "MCZ_HERPOBS"  VALUES (13) )  ENABLE ROW MOVEMENT 
  CREATE UNIQUE INDEX "PK_FLAT" ON "FLAT" ("COLLECTION_OBJECT_ID") 
  
ALTER TABLE "FLAT" ADD CONSTRAINT "PK_FLAT" PRIMARY KEY ("COLLECTION_OBJECT_ID")
  USING INDEX "PK_FLAT"  ENABLE;
COMMENT ON COLUMN "FLAT"."LOCALITY_ID" IS 'Numeric key for the locality table for the locality where this material was collected.  Convenience term for joins to the locality table.';
COMMENT ON COLUMN "FLAT"."SCIENTIFIC_NAME" IS 'The scientific name for the current identification of this material.  The identification history is not available in FLAT.';
COMMENT ON COLUMN "FLAT"."DATE_MADE_DATE" IS 'Date on which the current identification was made.';
COMMENT ON COLUMN "FLAT"."COLLECTION_OBJECT_ID" IS 'Key for the collection object represented in a row in FLAT. ';
COMMENT ON COLUMN "FLAT"."CAT_NUM" IS 'Catalog Number.';
COMMENT ON COLUMN "FLAT"."ACCN_ID" IS 'Key to the trans table for the accession for this cataloged item.  This is not the accession number, for that see ACCESSION.';
COMMENT ON COLUMN "FLAT"."COLLECTION_ID" IS 'Key for the collection table, for text, see: collection_cde.';
COMMENT ON COLUMN "FLAT"."INSTITUTION_ACRONYM" IS 'The acronym for the instutution: MCZ';
COMMENT ON COLUMN "FLAT"."COLLECTION_CDE" IS 'Abbreviated name for the collection that this cataloged item is in.';
COMMENT ON COLUMN "FLAT"."COLLECTION" IS 'Fully spelled out name for the collection for the cataloged item.';
COMMENT ON COLUMN "FLAT"."COLLECTING_EVENT_ID" IS 'Key for the collecting_event table for this record.';
COMMENT ON COLUMN "FLAT"."DATE_BEGAN_DATE" IS 'Deprecated.';
COMMENT ON COLUMN "FLAT"."DATE_ENDED_DATE" IS 'Deprecated.';
COMMENT ON COLUMN "FLAT"."VERBATIM_DATE" IS 'Verbatim collecting event date.';
COMMENT ON COLUMN "FLAT"."LAST_EDIT_DATE" IS 'Timestame of the most recent edit of this record.';
COMMENT ON COLUMN "FLAT"."COLLECTORS" IS 'Comma delimited list of names of collectors of this cataloged item.  Note, collector names may contain commas, so this list is human readable, but not machine parsable.';
COMMENT ON COLUMN "FLAT"."SEX" IS 'Value of the sex attribute for this cataloged item.';
COMMENT ON COLUMN "FLAT"."PARTS" IS 'List of parts and preparation types in this cataloged item.';
COMMENT ON COLUMN "FLAT"."ENCUMBRANCES" IS 'Text identifiers for encumbrances that are applied to this cataloged item.   Semicolon delimited list, e.g. "mask record; mask locality"';
COMMENT ON COLUMN "FLAT"."ACCESSION" IS 'The accession number for the accession in which this material was accessioned.';
COMMENT ON COLUMN "FLAT"."HIGHER_GEOG" IS 'The higher geography string for the place where this material was collected.  Colon delimited list of higher geography terms.';
COMMENT ON COLUMN "FLAT"."CONTINENT_OCEAN" IS 'The Continent or Ocean term from the higher geography of the place where this material was collected.';
COMMENT ON COLUMN "FLAT"."COUNTRY" IS 'The country from the higher geography of the place where this material was collected.   See also SOVEREOGN_NATION. ';
COMMENT ON COLUMN "FLAT"."SCIENTIFICNAMEID" IS 'dwc:scientificNameID';
COMMENT ON COLUMN "FLAT"."HIGHERGEOGRAPHYID" IS 'dwc:higherGeographyID';
COMMENT ON COLUMN "FLAT"."RECORDEDBYID" IS 'dwciri:recordedBy';
COMMENT ON COLUMN "FLAT"."IDENTIFIEDBYID" IS 'dwciri:identifiedBy';
COMMENT ON COLUMN "FLAT"."GEOREFERENCEDBYID" IS 'dwciri:georeferencedBy';
COMMENT ON COLUMN "FLAT"."IMAGEURLFILTERED" IS 'dwc:associatedMedia';
COMMENT ON COLUMN "FLAT"."TOPTYPESTATUS" IS 'The specific sort of most important type status.';
COMMENT ON COLUMN "FLAT"."ROOMS" IS 'Rooms in which parts of the cataloged item are stored';
COMMENT ON COLUMN "FLAT"."CABINETS" IS 'Cabinent level (fixture, cryovat, tank) containers in which parts of the cataloged item are stored';
COMMENT ON COLUMN "FLAT"."DRAWERS" IS 'Drawer level (compartment, freezer rack) containers in which parts of the cataloged item are stored';
COMMENT ON COLUMN "FLAT"."SUBFAMILY" IS 'subfamily placement of current identification';
COMMENT ON COLUMN "FLAT"."TRIBE" IS 'tribe placement of taxon in current identification';
COMMENT ON COLUMN "FLAT"."SUBPHYLUM" IS 'subphylum placement of taxon for current identification';
COMMENT ON COLUMN "FLAT"."SUBCLASS" IS 'subclass placement of taxon for current identification';
COMMENT ON COLUMN "FLAT"."SUPERORDER" IS 'superordinal placement of taxon for current identification';
COMMENT ON COLUMN "FLAT"."INFRACLASS" IS 'infraclass placement of taxon for current identification';
COMMENT ON COLUMN "FLAT"."SUBORDER" IS 'suboridinal placement of taxon for current identification';
COMMENT ON COLUMN "FLAT"."INFRAORDER" IS 'infraordinal placement of taxon for current identification';
COMMENT ON COLUMN "FLAT"."SUPERFAMILY" IS 'superfamilial placement of taxon for current identification';
COMMENT ON COLUMN "FLAT"."COORDINATE_PRECISION" IS 'number of significant digits below decimal point for dec_lat and dec_long.';
COMMENT ON COLUMN "FLAT"."POINTRADIUSSPATIALFIT" IS 'spatial fit to go with coordinate uncertainty in meters.';
COMMENT ON COLUMN "FLAT"."VERBATIMSRS" IS 'The EPSG code that applies to the verbatim coordinates.';
COMMENT ON COLUMN "FLAT"."EARLIESTEONORLOWESTEONOTHEM" IS 'Full name of the eariest geochronological eon, or informal ame Precambrian.';
COMMENT ON COLUMN "FLAT"."LATESTEONORHIGHESTEONOTHEM" IS 'Fulll name of the latest geochronological eon or the informal name Precambrian.';
COMMENT ON COLUMN "FLAT"."RECEIVED_FROM" IS 'List of recieved from agents for the accession for this specimen.';
COMMENT ON COLUMN "FLAT"."ACCESSION_DATE" IS 'Date the MCZ took title on the material, value from trans.trans_date.';
COMMENT ON COLUMN "FLAT"."RECEIVED_DATE" IS 'Date at which the material in the accession including this specimen was received at the MCZ.  See accession date for date of ownership/stewardship.';
COMMENT ON COLUMN "FLAT"."PHYLCLASS" IS 'Taxonomic class placement for the scientific name used in the current identification of this material.';
COMMENT ON COLUMN "FLAT"."AUTHOR_TEXT" IS 'Authorship string for the current identification.';
COMMENT ON COLUMN "FLAT"."IMAGEURL" IS 'Unfiltered by media.mask_media_fg';
COMMENT ON COLUMN "FLAT"."CONTINENT" IS 'dwc:continent';
COMMENT ON COLUMN "FLAT"."WATERBODY" IS 'dwc:waterbody';
COMMENT ON COLUMN "FLAT"."RECATALOGED_FG" IS 'flag for has recataloged as relationship (thus exclude).';
COMMENT ON COLUMN "FLAT"."TAXONID" IS 'dwc:taxonID';
