
  CREATE TABLE "FLUID_CONTAINER_HISTORY" 
   (	"CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	"CHECKED_DATE" DATE NOT NULL ENABLE, 
	"FLUID_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CONCENTRATION" NUMBER(2,2) NOT NULL ENABLE, 
	"FLUID_REMARKS" VARCHAR2(255 CHAR), 
	 CONSTRAINT "FK_FLUIDCONTHIST_CONTAINER" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CONTAINER" ("CONTAINER_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "XPKFLUID_CONTAINER_HISTORY" ON "FLUID_CONTAINER_HISTORY" ("CONTAINER_ID", "CHECKED_DATE") 
  
ALTER TABLE "FLUID_CONTAINER_HISTORY" ADD CONSTRAINT "PK_FLUID_CONTAINER_HISTORY" PRIMARY KEY ("CONTAINER_ID", "CHECKED_DATE")
  USING INDEX "XPKFLUID_CONTAINER_HISTORY"  ENABLE;
