
  CREATE TABLE "FORMATTED_PUBLICATION" 
   (	"PUBLICATION_ID" NUMBER NOT NULL ENABLE, 
	"FORMAT_STYLE" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"FORMATTED_PUBLICATION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "FORMATTED_PUBLICATION_PK" PRIMARY KEY ("PUBLICATION_ID", "FORMAT_STYLE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FORMATTED_PUBLICATION_FK1" FOREIGN KEY ("PUBLICATION_ID")
	  REFERENCES "PUBLICATION" ("PUBLICATION_ID") ON DELETE CASCADE ENABLE
   ) ;
