
  CREATE TABLE "GEOG_AUTH_REC" 
   (	"GEOG_AUTH_REC_ID" NUMBER NOT NULL ENABLE, 
	"CONTINENT_OCEAN" VARCHAR2(70 CHAR), 
	"COUNTRY" VARCHAR2(70 CHAR), 
	"STATE_PROV" VARCHAR2(75 CHAR), 
	"COUNTY" VARCHAR2(50 CHAR), 
	"QUAD" VARCHAR2(30 CHAR), 
	"FEATURE" VARCHAR2(50 CHAR), 
	"ISLAND" VARCHAR2(50 CHAR), 
	"ISLAND_GROUP" VARCHAR2(50 CHAR), 
	"SEA" VARCHAR2(50 CHAR), 
	"VALID_CATALOG_TERM_FG" NUMBER(3,0) NOT NULL ENABLE, 
	"SOURCE_AUTHORITY" VARCHAR2(45 CHAR) NOT NULL ENABLE, 
	"HIGHER_GEOG" VARCHAR2(255 CHAR), 
	"OCEAN_REGION" VARCHAR2(50 CHAR), 
	"OCEAN_SUBREGION" VARCHAR2(50 CHAR), 
	"WATER_FEATURE" VARCHAR2(50), 
	 CONSTRAINT "PKEY_GEOG_AUTH_REC" PRIMARY KEY ("GEOG_AUTH_REC_ID")
  USING INDEX  ENABLE
   ) 