
  CREATE GLOBAL TEMPORARY TABLE "GEOGRAPHY_MERGE_SUMMARY" 
   (	"SOURCE_GEOG_ID" NUMBER, 
	"SOURCE_HIGHER_GEOG" VARCHAR2(4000), 
	"SOURCE_YEAR" NUMBER, 
	"TARGET_GEOG_ID" NUMBER, 
	"TARGET_HIGHER_GEOG" VARCHAR2(4000), 
	"TARGET_YEAR" NUMBER, 
	"CATALOGED_ITEM_COUNT" NUMBER, 
	"IS_STABLE" CHAR(1)
   ) ON COMMIT PRESERVE ROWS 