
  CREATE TABLE "GEOLOGY_ATTRIBUTE_HIERARCHY" 
   (	"GEOLOGY_ATTRIBUTE_HIERARCHY_ID" NUMBER NOT NULL ENABLE, 
	"PARENT_ID" NUMBER, 
	"ATTRIBUTE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ATTRIBUTE_VALUE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"USABLE_VALUE_FG" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "GEO_ATT_H_USABLE_CK" CHECK (usable_value_fg IN (0,1)) ENABLE, 
	 CONSTRAINT "FK_GEOLOGY_ATTRIBUTE_HIERARCHY" FOREIGN KEY ("PARENT_ID")
	  REFERENCES "GEOLOGY_ATTRIBUTE_HIERARCHY" ("GEOLOGY_ATTRIBUTE_HIERARCHY_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "U_GEOLOGY_ATTRIBUTE" ON "GEOLOGY_ATTRIBUTE_HIERARCHY" ("ATTRIBUTE", "ATTRIBUTE_VALUE") 
  
  CREATE UNIQUE INDEX "PK_GEOLOGY_ATTRIBUTE_HIERARCHY" ON "GEOLOGY_ATTRIBUTE_HIERARCHY" ("GEOLOGY_ATTRIBUTE_HIERARCHY_ID") 
  
ALTER TABLE "GEOLOGY_ATTRIBUTE_HIERARCHY" ADD CONSTRAINT "U_GEOLOGY_ATTRIBUTE" UNIQUE ("ATTRIBUTE", "ATTRIBUTE_VALUE")
  USING INDEX "U_GEOLOGY_ATTRIBUTE"  ENABLE
ALTER TABLE "GEOLOGY_ATTRIBUTE_HIERARCHY" ADD CONSTRAINT "PK_GEOLOGY_ATTRIBUTE_HIERARCHY" PRIMARY KEY ("GEOLOGY_ATTRIBUTE_HIERARCHY_ID")
  USING INDEX "PK_GEOLOGY_ATTRIBUTE_HIERARCHY"  ENABLE;
COMMENT ON TABLE "GEOLOGY_ATTRIBUTE_HIERARCHY" IS 'Heirarchical relationships of geologic attribute terms.   Contains edge representations of trees.';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTE_HIERARCHY"."GEOLOGY_ATTRIBUTE_HIERARCHY_ID" IS 'Surrogate numeric primary key.';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTE_HIERARCHY"."PARENT_ID" IS 'Foreign key for the parent node of the current node, null for the root of a tree.';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTE_HIERARCHY"."ATTRIBUTE" IS 'With attribute value, foreign key to the attribute at this node in the tree.';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTE_HIERARCHY"."ATTRIBUTE_VALUE" IS 'With attribute, foreign key to the attribute at this node in the tree.';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTE_HIERARCHY"."USABLE_VALUE_FG" IS 'Flag indicating whether or not this node can be used for data entry (1) yes, (0) no.';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTE_HIERARCHY"."DESCRIPTION" IS 'Free text assertion about this node.';
