
  CREATE TABLE "GEOLOGY_ATTRIBUTES" 
   (	"GEOLOGY_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
	"LOCALITY_ID" NUMBER NOT NULL ENABLE, 
	"GEOLOGY_ATTRIBUTE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"GEO_ATT_VALUE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"GEO_ATT_DETERMINER_ID" NUMBER, 
	"GEO_ATT_DETERMINED_DATE" DATE, 
	"GEO_ATT_DETERMINED_METHOD" VARCHAR2(255 CHAR), 
	"GEO_ATT_REMARK" VARCHAR2(4000 CHAR), 
	"PREVIOUS_VALUES" VARCHAR2(4000), 
	 CONSTRAINT "FK_GEOLATTRIBUTES_LOCALITY" FOREIGN KEY ("LOCALITY_ID")
	  REFERENCES "LOCALITY" ("LOCALITY_ID") ENABLE, 
	 CONSTRAINT "FK_DETERMINER_AGENT" FOREIGN KEY ("GEO_ATT_DETERMINER_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_GEOLOGY_ATTRIBUTE" FOREIGN KEY ("GEOLOGY_ATTRIBUTE")
	  REFERENCES "CTGEOLOGY_ATTRIBUTES" ("GEOLOGY_ATTRIBUTE") ENABLE, 
	 CONSTRAINT "FK_GEO_ATT_ATT_VALUE" FOREIGN KEY ("GEOLOGY_ATTRIBUTE", "GEO_ATT_VALUE")
	  REFERENCES "GEOLOGY_ATTRIBUTE_HIERARCHY" ("ATTRIBUTE", "ATTRIBUTE_VALUE") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_GEOLOGY_ATTRIBUTES" ON "GEOLOGY_ATTRIBUTES" ("GEOLOGY_ATTRIBUTE_ID") 
  
ALTER TABLE "GEOLOGY_ATTRIBUTES" ADD CONSTRAINT "PK_GEOLOGY_ATTRIBUTES" PRIMARY KEY ("GEOLOGY_ATTRIBUTE_ID")
  USING INDEX "PK_GEOLOGY_ATTRIBUTES"  ENABLE;
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."GEOLOGY_ATTRIBUTE_ID" IS 'surrogage numeric primary key';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."LOCALITY_ID" IS 'locality to which this attribute applies';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."GEOLOGY_ATTRIBUTE" IS 'type of attribute';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."GEO_ATT_VALUE" IS 'value of attribute';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."GEO_ATT_DETERMINER_ID" IS 'agent id for the person who applied this attribute to this locality';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."GEO_ATT_DETERMINED_DATE" IS 'date on which the attribute value was determined for this locality';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."GEO_ATT_DETERMINED_METHOD" IS 'method by which the attribute value was determined for this locality';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."GEO_ATT_REMARK" IS 'remarks concerning this geological attribute.';
COMMENT ON COLUMN "GEOLOGY_ATTRIBUTES"."PREVIOUS_VALUES" IS 'previous values for geo_attr_value pipe separated list';
