
  CREATE TABLE "GIS_ALASKA_RIVERS" 
   (	"TYPE" VARCHAR2(254), 
	"NUM" NUMBER, 
	"MAJ" NUMBER, 
	"RFRSHDT" NUMBER(38,0), 
	"MAJ2" NUMBER, 
	"MIN2" NUMBER, 
	"HEIRARCHY" NUMBER, 
	"MIN" NUMBER, 
	"SHAPE" "MDSYS"."SDO_GEOMETRY" 
   ) 
 VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "SHAPE"."SDO_ORDINATES" STORE AS SECUREFILE LOB 