
  CREATE TABLE "GIS_US_STATES" 
   (	"REGION" VARCHAR2(2), 
	"DIVISION" VARCHAR2(2), 
	"STATEFP" VARCHAR2(2), 
	"STATENS" VARCHAR2(8), 
	"GEOID" VARCHAR2(2), 
	"STUSPS" VARCHAR2(2), 
	"NAME" VARCHAR2(100), 
	"LSAD" VARCHAR2(2), 
	"MTFCC" VARCHAR2(5), 
	"FUNCSTAT" VARCHAR2(1), 
	"ALAND" NUMBER(38,0), 
	"AWATER" NUMBER(38,0), 
	"INTPTLAT" VARCHAR2(11), 
	"INTPTLON" VARCHAR2(12), 
	"SHAPE" "MDSYS"."SDO_GEOMETRY" 
   ) 