
  CREATE TABLE "GIS_CANADA_1" 
   (	"GID_0" VARCHAR2(80), 
	"NAME_0" VARCHAR2(80), 
	"GID_1" VARCHAR2(80), 
	"NAME_1" VARCHAR2(80), 
	"VARNAME_1" VARCHAR2(80), 
	"NL_NAME_1" VARCHAR2(80), 
	"TYPE_1" VARCHAR2(80), 
	"ENGTYPE_1" VARCHAR2(80), 
	"CC_1" VARCHAR2(80), 
	"HASC_1" VARCHAR2(80), 
	"SHAPE" "MDSYS"."SDO_GEOMETRY" 
   ) 
 VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "SHAPE"."SDO_ORDINATES" STORE AS SECUREFILE LOB 