
  CREATE TABLE "GIS_COUNTRY_SHAPES" 
   (	"OBJECTID" NUMBER(38,0), 
	"CNTRY_NAME" VARCHAR2(80), 
	"SHAPE" "MDSYS"."SDO_GEOMETRY" 
   ) 
 VARRAY "SHAPE"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "SHAPE"."SDO_ORDINATES" STORE AS SECUREFILE LOB ;
