
  CREATE TABLE "GROUP_MEMBER" 
   (	"GROUP_AGENT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MEMBER_AGENT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"MEMBER_ORDER" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "FK_GROUP_MEMBER_AGENT" FOREIGN KEY ("MEMBER_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 