
  CREATE TABLE "GUID_OUR_THING" 
   (	"GUID_OUR_THING_ID" NUMBER NOT NULL ENABLE, 
	"TIMESTAMP_CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"TARGET_TABLE" VARCHAR2(20), 
	"CO_COLLECTION_OBJECT_ID" NUMBER, 
	"SP_COLLECTION_OBJECT_ID" NUMBER, 
	"TAXON_NAME_ID" NUMBER, 
	"RESOLVER_PREFIX" VARCHAR2(500), 
	"SCHEME" VARCHAR2(20), 
	"TYPE" VARCHAR2(20), 
	"AUTHORITY" VARCHAR2(50), 
	"LOCAL_IDENTIFIER" VARCHAR2(3000), 
	"ASSEMBLED_IDENTIFIER" VARCHAR2(3500), 
	"ASSEMBLED_RESOLVABLE" VARCHAR2(4000), 
	"ASSIGNED_BY_AGENT_ID" NUMBER, 
	"CREATED_BY_AGENT_ID" VARCHAR2(30), 
	"LAST_MODIFIED" TIMESTAMP (6), 
	"DISPOSITION" VARCHAR2(20) DEFAULT 'exists' NOT NULL ENABLE, 
	"GUID_IS_A" VARCHAR2(50), 
	"METADATA" CLOB, 
	"INTERNAL_FG" NUMBER(1,0) DEFAULT 1, 
	 CONSTRAINT "GUID_OUR_THING_PK" PRIMARY KEY ("GUID_OUR_THING_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNIQUE_GUID" UNIQUE ("ASSEMBLED_IDENTIFIER")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CO_COLL_OBJECT_ID" FOREIGN KEY ("CO_COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_SP_COLL_OBJECT_ID" FOREIGN KEY ("SP_COLLECTION_OBJECT_ID")
	  REFERENCES "SPECIMEN_PART" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_TAXON_NAME_ID" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE
   ) 