
  CREATE TABLE "IDENTIFICATION_AGENT" 
   (	"IDENTIFICATION_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"IDENTIFIER_ORDER" NUMBER NOT NULL ENABLE, 
	"IDENTIFICATION_AGENT_ID" NUMBER, 
	 CONSTRAINT "FK_IDAGENT_AGENT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_IDAGENT_IDENTIFICATION" FOREIGN KEY ("IDENTIFICATION_ID")
	  REFERENCES "IDENTIFICATION" ("IDENTIFICATION_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_IDENTIFICATION_AGENT" ON "IDENTIFICATION_AGENT" ("IDENTIFICATION_AGENT_ID") 
  
ALTER TABLE "IDENTIFICATION_AGENT" ADD CONSTRAINT "PK_IDENTIFICATION_AGENT" PRIMARY KEY ("IDENTIFICATION_AGENT_ID")
  USING INDEX "PK_IDENTIFICATION_AGENT"  ENABLE;
COMMENT ON TABLE "IDENTIFICATION_AGENT" IS 'An agent who made an identification.  Assocaitive entiy relating agents to identifications.';
COMMENT ON COLUMN "IDENTIFICATION_AGENT"."IDENTIFICATION_ID" IS 'Identification made by the agent.';
COMMENT ON COLUMN "IDENTIFICATION_AGENT"."AGENT_ID" IS 'Agent who made the identification.';
COMMENT ON COLUMN "IDENTIFICATION_AGENT"."IDENTIFIER_ORDER" IS 'Order of the agent in a list of identifiers for a particular identification.';
COMMENT ON COLUMN "IDENTIFICATION_AGENT"."IDENTIFICATION_AGENT_ID" IS 'Surrogate numeric primary key.';
