
  CREATE TABLE "IDENTIFICATION_TAXONOMY" 
   (	"IDENTIFICATION_ID" NUMBER NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"VARIABLE" CHAR(1 CHAR), 
	 CONSTRAINT "FK_IDTAXONOMY_TAXONOMY" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE, 
	 CONSTRAINT "FK_IDTAXONOMY_IDENTIFICATION" FOREIGN KEY ("IDENTIFICATION_ID")
	  REFERENCES "IDENTIFICATION" ("IDENTIFICATION_ID") ENABLE
   ) 