
  CREATE TABLE "IDENTIFICATION_AGENT" 
   (	"IDENTIFICATION_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"IDENTIFIER_ORDER" NUMBER NOT NULL ENABLE, 
	"IDENTIFICATION_AGENT_ID" NUMBER, 
	 CONSTRAINT "PK_IDENTIFICATION_AGENT" PRIMARY KEY ("IDENTIFICATION_AGENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_IDAGENT_AGENT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_IDAGENT_IDENTIFICATION" FOREIGN KEY ("IDENTIFICATION_ID")
	  REFERENCES "IDENTIFICATION" ("IDENTIFICATION_ID") ENABLE
   ) 