
  CREATE TABLE "LAT_LONG_GEOM" 
   (	"LOCALITY_ID" NUMBER NOT NULL ENABLE, 
	"LAT_LONG_ID" NUMBER NOT NULL ENABLE, 
	"LATLONGGEOM" "MDSYS"."SDO_GEOMETRY" 
   ) 
 VARRAY "LATLONGGEOM"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "LATLONGGEOM"."SDO_ORDINATES" STORE AS SECUREFILE LOB 