
  CREATE TABLE "LEDGER_NOTFOUND_MASTER" 
   (	"COLLECTION_CDE" VARCHAR2(10), 
	"CATALOG_NUMBER_PREFIX" VARCHAR2(20), 
	"CATALOG_NUMBER" NUMBER, 
	"MEDIA_ID" NUMBER, 
	"CAT_NUM_SUFFIX" VARCHAR2(20), 
	"COLLECTION_OBJECT_ID" NUMBER
   ) 