
  CREATE TABLE "LOAN" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"LOAN_TYPE" VARCHAR2(25 CHAR), 
	"LOAN_NUM_PREFIX" VARCHAR2(10 CHAR), 
	"LOAN_NUM" NUMBER, 
	"LOAN_NUM_SUFFIX" VARCHAR2(10 CHAR), 
	"LOAN_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"LOAN_INSTRUCTIONS" VARCHAR2(4000 CHAR), 
	"RETURN_DUE_DATE" DATE, 
	"LOAN_DESCRIPTION" VARCHAR2(4000 CHAR), 
	"LOAN_NUMBER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"INSURANCE_VALUE" VARCHAR2(4000 CHAR), 
	"INSURANCE_MAINTAINED_BY" VARCHAR2(4000 CHAR), 
	"CLOSED_DATE" DATE, 
	"CLOSED_BY" VARCHAR2(50), 
	 CONSTRAINT "PK_LOAN" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CT_LOAN_STATUS" FOREIGN KEY ("LOAN_STATUS")
	  REFERENCES "CTLOAN_STATUS" ("LOAN_STATUS") ENABLE, 
	 CONSTRAINT "FK_LOAN_TRANS" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE
   ) 