
  CREATE TABLE "LOAN_RELATIONS" 
   (	"TRANSACTION_ID" NUMBER, 
	"RELATED_TRANSACTION_ID" NUMBER, 
	"RELATION_TYPE" VARCHAR2(50 CHAR) DEFAULT 'Subloan' NOT NULL ENABLE, 
	 CONSTRAINT "LOAN_RELATIONS_UK1" UNIQUE ("TRANSACTION_ID", "RELATED_TRANSACTION_ID", "RELATION_TYPE")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_LOANRELAT_PARENTLOAN" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "LOAN" ("TRANSACTION_ID") ENABLE, 
	 CONSTRAINT "FK_LOANRELAT_CHILDLOAN" FOREIGN KEY ("RELATED_TRANSACTION_ID")
	  REFERENCES "LOAN" ("TRANSACTION_ID") ENABLE
   ) 