
  CREATE TABLE "LOAN_ITEM" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"RECONCILED_BY_PERSON_ID" NUMBER NOT NULL ENABLE, 
	"RECONCILED_DATE" DATE, 
	"ITEM_DESCR" VARCHAR2(127 CHAR) NOT NULL ENABLE, 
	"ITEM_INSTRUCTIONS" VARCHAR2(255 CHAR), 
	"LOAN_ITEM_REMARKS" VARCHAR2(255 CHAR), 
	 CONSTRAINT "FK_LOANITEM_LOAN" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "LOAN" ("TRANSACTION_ID") ENABLE, 
	 CONSTRAINT "FK_LOANITEM_COLLOBJ" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE
   ) 