
  CREATE TABLE "LOAN" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"LOAN_TYPE" VARCHAR2(25 CHAR), 
	"LOAN_NUM_PREFIX" VARCHAR2(10 CHAR), 
	"LOAN_NUM" NUMBER, 
	"LOAN_NUM_SUFFIX" VARCHAR2(10 CHAR), 
	"LOAN_STATUS" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"LOAN_INSTRUCTIONS" VARCHAR2(4000 CHAR), 
	"RETURN_DUE_DATE" DATE, 
	"LOAN_DESCRIPTION" VARCHAR2(4000 CHAR), 
	"LOAN_NUMBER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"INSURANCE_VALUE" VARCHAR2(4000 CHAR), 
	"INSURANCE_MAINTAINED_BY" VARCHAR2(4000 CHAR), 
	"CLOSED_DATE" DATE, 
	"CLOSED_BY" VARCHAR2(50), 
	 CONSTRAINT "FK_CT_LOAN_STATUS" FOREIGN KEY ("LOAN_STATUS")
	  REFERENCES "CTLOAN_STATUS" ("LOAN_STATUS") ENABLE, 
	 CONSTRAINT "FK_LOAN_TRANS" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PKEY_LOAN" ON "LOAN" ("TRANSACTION_ID") 
  
ALTER TABLE "LOAN" ADD CONSTRAINT "PK_LOAN" PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX "PKEY_LOAN"  ENABLE;
COMMENT ON TABLE "LOAN" IS 'Subtype of transactions (TRANS) where material cataloged in the MCZ are temporaraly loaned to another institution.';
COMMENT ON COLUMN "LOAN"."TRANSACTION_ID" IS 'dependent key';
COMMENT ON COLUMN "LOAN"."LOAN_TYPE" IS 'Type of loan (consumable, returnable, exhibition)';
COMMENT ON COLUMN "LOAN"."LOAN_NUM_PREFIX" IS 'Deprecated.';
COMMENT ON COLUMN "LOAN"."LOAN_NUM" IS 'Deprecated';
COMMENT ON COLUMN "LOAN"."LOAN_NUM_SUFFIX" IS 'Deprecated.';
COMMENT ON COLUMN "LOAN"."LOAN_STATUS" IS 'Current state of the loan in its life cycle.';
COMMENT ON COLUMN "LOAN"."LOAN_INSTRUCTIONS" IS 'Free text instructions to the borrower about the loan and the handling of the material in the loan.';
COMMENT ON COLUMN "LOAN"."RETURN_DUE_DATE" IS 'The current date by which the loan is due to be returned.';
COMMENT ON COLUMN "LOAN"."LOAN_DESCRIPTION" IS 'Free text description of the material in the loan.';
COMMENT ON COLUMN "LOAN"."LOAN_NUMBER" IS 'Identifier for the loan.';
COMMENT ON COLUMN "LOAN"."INSURANCE_VALUE" IS 'Value for which the material in the loan is to be insured.';
COMMENT ON COLUMN "LOAN"."INSURANCE_MAINTAINED_BY" IS 'The party responsible for insurance on the loan.';
COMMENT ON COLUMN "LOAN"."CLOSED_DATE" IS 'Date on which the loan was closed.';
COMMENT ON COLUMN "LOAN"."CLOSED_BY" IS 'Operator who marked the loan as closed.';
