
  CREATE TABLE "MEDIA" 
   (	"MEDIA_ID" NUMBER NOT NULL ENABLE, 
	"MEDIA_URI" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"MIME_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MEDIA_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PREVIEW_URI" VARCHAR2(500 CHAR), 
	"MEDIA_LICENSE_ID" NUMBER(22,0), 
	"MASK_MEDIA_FG" NUMBER(1,0) DEFAULT 0, 
	"AUTO_PROTOCOL" VARCHAR2(20), 
	"AUTO_HOST" VARCHAR2(500), 
	"AUTO_PATH" VARCHAR2(500), 
	"AUTO_FILENAME" VARCHAR2(500), 
	"AUTO_EXTENSION" VARCHAR2(5), 
	 CONSTRAINT "PK_MEDIA" PRIMARY KEY ("MEDIA_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTMEDIA_TYPE" FOREIGN KEY ("MEDIA_TYPE")
	  REFERENCES "CTMEDIA_TYPE" ("MEDIA_TYPE") ENABLE, 
	 CONSTRAINT "FK_MEDIA_CTMIMETYPE" FOREIGN KEY ("MIME_TYPE")
	  REFERENCES "CTMIME_TYPE" ("MIME_TYPE") ENABLE, 
	 CONSTRAINT "FK_MEDIA_LICENSE" FOREIGN KEY ("MEDIA_LICENSE_ID")
	  REFERENCES "CTMEDIA_LICENSE" ("MEDIA_LICENSE_ID") ENABLE
   ) 