
  CREATE TABLE "MEDIA" 
   (	"MEDIA_ID" NUMBER NOT NULL ENABLE, 
	"MEDIA_URI" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MIME_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MEDIA_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PREVIEW_URI" VARCHAR2(255 CHAR), 
	"MEDIA_LICENSE_ID" NUMBER(22,0), 
	"MASK_MEDIA_FG" NUMBER(1,0), 
	 CONSTRAINT "PK_MEDIA" PRIMARY KEY ("MEDIA_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTMEDIA_TYPE" FOREIGN KEY ("MEDIA_TYPE")
	  REFERENCES "CTMEDIA_TYPE" ("MEDIA_TYPE") ENABLE, 
	 CONSTRAINT "FK_MEDIA_CTMIMETYPE" FOREIGN KEY ("MIME_TYPE")
	  REFERENCES "CTMIME_TYPE" ("MIME_TYPE") ENABLE
   ) 