
  CREATE TABLE "MEDIA_KEYWORDS" 
   (	"MEDIA_ID" NUMBER NOT NULL ENABLE, 
	"KEYWORDS" VARCHAR2(4000 CHAR), 
	"LASTDATE" DATE, 
	"MEDIA_KEYWORDS_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MEDIA_KEYWORDS_PK" PRIMARY KEY ("MEDIA_KEYWORDS_ID")
  USING INDEX  ENABLE
   ) 