
  CREATE TABLE "MEDIA" 
   (	"MEDIA_ID" NUMBER NOT NULL ENABLE, 
	"MEDIA_URI" VARCHAR2(500 CHAR) NOT NULL ENABLE, 
	"MIME_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MEDIA_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PREVIEW_URI" VARCHAR2(500 CHAR), 
	"MEDIA_LICENSE_ID" NUMBER(22,0), 
	"MASK_MEDIA_FG" NUMBER(1,0) DEFAULT 0, 
	"AUTO_PROTOCOL" VARCHAR2(20), 
	"AUTO_HOST" VARCHAR2(500), 
	"AUTO_PATH" VARCHAR2(500), 
	"AUTO_FILENAME" VARCHAR2(500), 
	"AUTO_EXTENSION" VARCHAR2(5), 
	 CONSTRAINT "FK_CTMEDIA_TYPE" FOREIGN KEY ("MEDIA_TYPE")
	  REFERENCES "CTMEDIA_TYPE" ("MEDIA_TYPE") ENABLE, 
	 CONSTRAINT "FK_MEDIA_CTMIMETYPE" FOREIGN KEY ("MIME_TYPE")
	  REFERENCES "CTMIME_TYPE" ("MIME_TYPE") ENABLE, 
	 CONSTRAINT "FK_MEDIA_LICENSE" FOREIGN KEY ("MEDIA_LICENSE_ID")
	  REFERENCES "CTMEDIA_LICENSE" ("MEDIA_LICENSE_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_MEDIA" ON "MEDIA" ("MEDIA_ID") 
  
ALTER TABLE "MEDIA" ADD CONSTRAINT "PK_MEDIA" PRIMARY KEY ("MEDIA_ID")
  USING INDEX "PK_MEDIA"  ENABLE;
COMMENT ON TABLE "MEDIA" IS 'A metadata record for a media object.';
COMMENT ON COLUMN "MEDIA"."MEDIA_ID" IS 'surrogate numeric primary key, also used as resolvalbe identifier for media record with /media/{media_id} in web API.';
COMMENT ON COLUMN "MEDIA"."MEDIA_URI" IS 'IRI for the referenced media object';
COMMENT ON COLUMN "MEDIA"."MIME_TYPE" IS 'Mime type of the resource at the IRI provided by the media_uri.';
COMMENT ON COLUMN "MEDIA"."MEDIA_TYPE" IS 'Human descriptor of the media';
COMMENT ON COLUMN "MEDIA"."PREVIEW_URI" IS 'IRI for a thumbnail for the media object.';
COMMENT ON COLUMN "MEDIA"."MEDIA_LICENSE_ID" IS 'The license under which the institution is enabled to distribute a copy of the media object.   ';
COMMENT ON COLUMN "MEDIA"."MASK_MEDIA_FG" IS 'Flag indicating that this media record should be hidden from the public.  1=mask, 0=public.';
COMMENT ON COLUMN "MEDIA"."AUTO_PROTOCOL" IS 'Autogenerated protocol portion of the media_uri';
COMMENT ON COLUMN "MEDIA"."AUTO_HOST" IS 'Autogenerated host portion of the media_uri';
COMMENT ON COLUMN "MEDIA"."AUTO_PATH" IS 'Autogenerated path portion of the media_uri';
COMMENT ON COLUMN "MEDIA"."AUTO_FILENAME" IS 'Autogenerated filename portion of the media_uri';
COMMENT ON COLUMN "MEDIA"."AUTO_EXTENSION" IS 'Autogenerated filename extension portion of the media_uri';
