
  CREATE TABLE "MOLLUSK_NAME_VALIDITY20240426" 
   (	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"VALID_CATALOG_TERM_FG" NUMBER NOT NULL ENABLE, 
	"SCIENTIFIC_NAME" VARCHAR2(110 CHAR) NOT NULL ENABLE
   ) 