
  CREATE TABLE "NPS_SHAPES" 
   (	"OBJECTID" NUMBER(38,0), 
	"CREATIONDA" NUMBER(38,0), 
	"CREATOR" VARCHAR2(14), 
	"EDITDATE" NUMBER(38,0), 
	"EDITOR" VARCHAR2(14), 
	"GLOBALID" VARCHAR2(36), 
	"AREAID" NUMBER(38,0), 
	"UNIT_CODE" VARCHAR2(4), 
	"GIS_NOTES" VARCHAR2(84), 
	"UNIT_NAME" VARCHAR2(83), 
	"DATE_EDIT" NUMBER(38,0), 
	"STATE" VARCHAR2(2), 
	"REGION" VARCHAR2(2), 
	"GNIS_ID" VARCHAR2(12), 
	"UNIT_TYPE" VARCHAR2(28), 
	"CREATED_BY" VARCHAR2(6), 
	"METADATA" VARCHAR2(80), 
	"PARKNAME" VARCHAR2(51), 
	"SHAPE__ARE" NUMBER, 
	"SHAPE__LEN" NUMBER, 
	"GEOM" "MDSYS"."SDO_GEOMETRY" 
   ) 