
  CREATE TABLE "OBJECT_CONDITION" 
   (	"OBJECT_CONDITION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"DETERMINED_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"CONDITION" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"DETERMINED_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_OBJECT_CONDITION" PRIMARY KEY ("OBJECT_CONDITION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_OBJECTCONDITION_COLLOBJECT" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ON DELETE CASCADE ENABLE
   ) 