
  CREATE TABLE "ORPHAN_PERSON" 
   (	"PERSON_ID" NUMBER NOT NULL ENABLE, 
	"PREFIX" VARCHAR2(20 CHAR), 
	"LAST_NAME" VARCHAR2(80 CHAR) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(40 CHAR), 
	"MIDDLE_NAME" VARCHAR2(40 CHAR), 
	"SUFFIX" VARCHAR2(20 CHAR), 
	"BIRTH_DATE_DATE" DATE, 
	"DEATH_DATE_DATE" DATE, 
	"OLDEDITED" CHAR(1 CHAR), 
	"BIRTH_DATE" VARCHAR2(22 CHAR), 
	"DEATH_DATE" VARCHAR2(22 CHAR), 
	"AGENT_ID" NUMBER(15,0), 
	"AGENT_TYPE" VARCHAR2(30), 
	"AGENT_REMARKS" VARCHAR2(4000), 
	"PREFERRED_AGENT_NAME_ID" NUMBER, 
	"EDITED" CHAR(1 CHAR), 
	"AGENTGUID_GUID_TYPE" VARCHAR2(255), 
	"AGENTGUID" VARCHAR2(900), 
	"BIOGRAPHY" VARCHAR2(4000)
   ) 