
  CREATE TABLE "PERMIT_SHIPMENT" 
   (	"PERMIT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	"SHIPMENT_ID" NUMBER(38,0) NOT NULL ENABLE, 
	 CONSTRAINT "PERMIT_SHIPMENT_PK" PRIMARY KEY ("PERMIT_ID", "SHIPMENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_SHIPMENT_ID" FOREIGN KEY ("SHIPMENT_ID")
	  REFERENCES "SHIPMENT" ("SHIPMENT_ID") ENABLE, 
	 CONSTRAINT "FK_PERMIT_SHIPMENT_PERMIT_ID" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PERMIT" ("PERMIT_ID") ENABLE
   ) ;
