
  CREATE TABLE "PERMIT_TRANS" 
   (	"PERMIT_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_PERMIT_TRANS_TRANS_ID" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE, 
	 CONSTRAINT "FK_PERMITTRANS_PERMIT" FOREIGN KEY ("PERMIT_ID")
	  REFERENCES "PERMIT" ("PERMIT_ID") ENABLE
   ) 