
  CREATE TABLE "PROJECT_TAXONOMY" 
   (	"PROJECT_TAXON_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_PROJECT_TAXON_ID" PRIMARY KEY ("PROJECT_TAXON_ID")
  USING INDEX  ENABLE
   ) 