
  CREATE TABLE "PROJECT" 
   (	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PROJECT_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PROJECT_DESCRIPTION" VARCHAR2(4000 CHAR), 
	"PROJECT_REMARKS" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PK_PROJECT" PRIMARY KEY ("PROJECT_ID")
  USING INDEX  ENABLE
   ) 