
  CREATE TABLE "PROJECT_TRANS" 
   (	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_TRANS_REMARKS" VARCHAR2(255 CHAR), 
	 CONSTRAINT "PK_PROJECT_TRANS" PRIMARY KEY ("PROJECT_ID", "TRANSACTION_ID")
  USING INDEX  ENABLE
   ) 