
  CREATE TABLE "PROJECT_AGENT" 
   (	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_NAME_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_AGENT_ROLE" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"PROJECT_AGENT_REMARKS" VARCHAR2(255 CHAR), 
	"AGENT_POSITION" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_CTPROJECT_AGENT_ROLE" FOREIGN KEY ("PROJECT_AGENT_ROLE")
	  REFERENCES "CTPROJECT_AGENT_ROLE" ("PROJECT_AGENT_ROLE") ENABLE
   ) 