
  CREATE TABLE "PROJECT_TRANS" 
   (	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_TRANS_REMARKS" VARCHAR2(255 CHAR)
   ) 
  CREATE UNIQUE INDEX "XPKPROJECT_TRANS" ON "PROJECT_TRANS" ("PROJECT_ID", "TRANSACTION_ID") 
  
ALTER TABLE "PROJECT_TRANS" ADD CONSTRAINT "PK_PROJECT_TRANS" PRIMARY KEY ("PROJECT_ID", "TRANSACTION_ID")
  USING INDEX "XPKPROJECT_TRANS"  ENABLE