
  CREATE TABLE "PROJECT_SPONSOR" 
   (	"PROJECT_SPONSOR_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_NAME_ID" NUMBER NOT NULL ENABLE, 
	"ACKNOWLEDGEMENT" VARCHAR2(255 CHAR), 
	 CONSTRAINT "PK_PROJECT_SPONSOR" PRIMARY KEY ("PROJECT_SPONSOR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_PROJECTSPONSOR_PROJECT" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "PROJECT" ("PROJECT_ID") ENABLE, 
	 CONSTRAINT "FK_PROJECTSPONSOR_AGENTNAME" FOREIGN KEY ("AGENT_NAME_ID")
	  REFERENCES "AGENT_NAME" ("AGENT_NAME_ID") ENABLE
   ) 