
  CREATE TABLE "PROJECT_TAXONOMY" 
   (	"PROJECT_TAXON_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_PROJECT_TAXON_ID" ON "PROJECT_TAXONOMY" ("PROJECT_TAXON_ID") 
  
ALTER TABLE "PROJECT_TAXONOMY" ADD CONSTRAINT "PK_PROJECT_TAXON_ID" PRIMARY KEY ("PROJECT_TAXON_ID")
  USING INDEX "PK_PROJECT_TAXON_ID"  ENABLE;
