
  CREATE TABLE "PROJECT" 
   (	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PROJECT_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PROJECT_DESCRIPTION" VARCHAR2(4000 CHAR), 
	"PROJECT_REMARKS" VARCHAR2(4000 CHAR)
   ) 
  CREATE UNIQUE INDEX "PK_PROJECT" ON "PROJECT" ("PROJECT_ID") 
  
ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY ("PROJECT_ID")
  USING INDEX "PK_PROJECT"  ENABLE;
