
  CREATE TABLE "PROJECT" 
   (	"PROJECT_ID" NUMBER NOT NULL ENABLE, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PROJECT_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PROJECT_DESCRIPTION" VARCHAR2(4000 CHAR), 
	"PROJECT_REMARKS" VARCHAR2(4000 CHAR), 
	"MASK_PROJECT_FG" NUMBER(1,0) DEFAULT 0
   ) 
  CREATE UNIQUE INDEX "PK_PROJECT" ON "PROJECT" ("PROJECT_ID") 
  
ALTER TABLE "PROJECT" ADD CONSTRAINT "PK_PROJECT" PRIMARY KEY ("PROJECT_ID")
  USING INDEX "PK_PROJECT"  ENABLE;
COMMENT ON COLUMN "PROJECT"."MASK_PROJECT_FG" IS 'Flag indicating that this project should be hidden from the public.  1=mask, 0=public.';
COMMENT ON COLUMN "PROJECT"."PROJECT_NAME" IS 'A free text name for the project.';
COMMENT ON COLUMN "PROJECT"."PROJECT_DESCRIPTION" IS 'A free text description of the project.';
COMMENT ON COLUMN "PROJECT"."PROJECT_REMARKS" IS 'Free text internal remarks concerning the project.';
COMMENT ON COLUMN "PROJECT"."PROJECT_ID" IS 'Surrogate numeric primary key.';
COMMENT ON COLUMN "PROJECT"."START_DATE" IS 'Date on which the project started.';
COMMENT ON COLUMN "PROJECT"."END_DATE" IS 'Date on which the project ended.';
