
  CREATE TABLE "PUBLICATION_URL" 
   (	"PUBLICATION_ID" NUMBER NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PUBLICATION_URL_ID" NUMBER NOT NULL ENABLE, 
	"LINK" VARCHAR2(4000 CHAR) NOT NULL ENABLE
   ) 