
  CREATE TABLE "REZ_SHAPES" 
   (	"AIANNHCE" VARCHAR2(4), 
	"AIANNHNS" VARCHAR2(8), 
	"GEOID" VARCHAR2(5), 
	"NAME" VARCHAR2(100), 
	"NAMELSAD" VARCHAR2(100), 
	"LSAD" VARCHAR2(2), 
	"CLASSFP" VARCHAR2(2), 
	"COMPTYP" VARCHAR2(1), 
	"AIANNHR" VARCHAR2(1), 
	"MTFCC" VARCHAR2(5), 
	"FUNCSTAT" VARCHAR2(1), 
	"ALAND" NUMBER(38,0), 
	"AWATER" NUMBER(38,0), 
	"INTPTLAT" VARCHAR2(11), 
	"INTPTLON" VARCHAR2(12), 
	"GEOM" "MDSYS"."SDO_GEOMETRY" 
   ) 
 VARRAY "GEOM"."SDO_ELEM_INFO" STORE AS SECUREFILE LOB 
 VARRAY "GEOM"."SDO_ORDINATES" STORE AS SECUREFILE LOB 