
  CREATE TABLE "SHIPMENT" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"PACKED_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"SHIPPED_CARRIER_METHOD" VARCHAR2(25 CHAR) NOT NULL ENABLE, 
	"CARRIERS_TRACKING_NUMBER" VARCHAR2(255 CHAR), 
	"SHIPPED_DATE" DATE, 
	"PACKAGE_WEIGHT" VARCHAR2(255 CHAR), 
	"HAZMAT_FG" NUMBER(1,0) NOT NULL ENABLE, 
	"INSURED_FOR_INSURED_VALUE" NUMBER, 
	"SHIPMENT_REMARKS" VARCHAR2(900 CHAR), 
	"CONTENTS" VARCHAR2(900 CHAR), 
	"FOREIGN_SHIPMENT_FG" NUMBER(1,0) NOT NULL ENABLE, 
	"SHIPPED_TO_ADDR_ID" NUMBER NOT NULL ENABLE, 
	"SHIPPED_FROM_ADDR_ID" NUMBER NOT NULL ENABLE, 
	"SHIPMENT_ID" NUMBER(22,0), 
	"NO_OF_PACKAGES" NUMBER, 
	"PRINT_FLAG" CHAR(1 CHAR), 
	"COSTS" NUMBER(12,2), 
	 CONSTRAINT "PK_SHIPMENT_ID" PRIMARY KEY ("SHIPMENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_CTSHIPPED_CARRIER_METHOD" FOREIGN KEY ("SHIPPED_CARRIER_METHOD")
	  REFERENCES "CTSHIPPED_CARRIER_METHOD" ("SHIPPED_CARRIER_METHOD") ENABLE, 
	 CONSTRAINT "FK_SHIPMENT_ADDR_SHIPPEDTO" FOREIGN KEY ("SHIPPED_TO_ADDR_ID")
	  REFERENCES "ADDR" ("ADDR_ID") ENABLE, 
	 CONSTRAINT "FK_SHIPMENT_PACKED_BY" FOREIGN KEY ("PACKED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) ;
COMMENT ON COLUMN "SHIPMENT"."COSTS" IS 'Costs to the MCZ for the shipment.';
COMMENT ON COLUMN "SHIPMENT"."TRANSACTION_ID" IS 'Transaction this is a shipment for.';
COMMENT ON COLUMN "SHIPMENT"."SHIPMENT_ID" IS 'Surrogate Numeric Primary Key';
