
  CREATE TABLE "SPCGIFTS" 
   (	"SPC_NUMBER" VARCHAR2(50), 
	"DATE_OF_GIFT" VARCHAR2(100), 
	"SPECIMENS" VARCHAR2(500), 
	"RECIPIENT" VARCHAR2(500), 
	"DISCARDED_OR_LOST_OR_MCZBASE" VARCHAR2(500), 
	"SPC_INT" NUMBER
   ) 