
  CREATE TABLE "SPECIMEN_ANNOTATIONS" 
   (	"ANNOTATION_ID" NUMBER NOT NULL ENABLE, 
	"ANNOTATE_DATE" DATE, 
	"CF_USERNAME" VARCHAR2(255 CHAR), 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"SCIENTIFIC_NAME" VARCHAR2(255 CHAR), 
	"HIGHER_GEOGRAPHY" VARCHAR2(255 CHAR), 
	"SPECIFIC_LOCALITY" VARCHAR2(255 CHAR), 
	"ANNOTATION_REMARKS" VARCHAR2(255 CHAR), 
	"REVIEWER_AGENT_ID" NUMBER, 
	"REVIEWED_FG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"REVIEWER_COMMENT" VARCHAR2(255 CHAR), 
	 CONSTRAINT "FK_SPECIMENANNO_CATITEM" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_SPECIMEN_ANNOTATIONS_AGENT" FOREIGN KEY ("REVIEWER_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 