
  CREATE TABLE "SPECIMEN_PART" 
   (	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"PART_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PART_MODIFIER" VARCHAR2(60 CHAR), 
	"SAMPLED_FROM_OBJ_ID" NUMBER, 
	"PRESERVE_METHOD" VARCHAR2(50 CHAR), 
	"DERIVED_FROM_CAT_ITEM" NUMBER NOT NULL ENABLE, 
	"IS_TISSUE" NUMBER, 
	 CONSTRAINT "PK_SPECIMEN_PART" PRIMARY KEY ("COLLECTION_OBJECT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CK_SPECIMENPART_NOTSAMPFRSELF" CHECK (SAMPLED_FROM_OBJ_ID != COLLECTION_OBJECT_ID) ENABLE, 
	 CONSTRAINT "FK_SPECIMENPART_COLLOBJECT" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_SPECIMENPART_CATITEM" FOREIGN KEY ("DERIVED_FROM_CAT_ITEM")
	  REFERENCES "CATALOGED_ITEM" ("COLLECTION_OBJECT_ID") ENABLE
   ) 