
  CREATE TABLE "SPECIMEN_PART_PRES_HIST" 
   (	"SPECIMEN_PART_PRES_HIST_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"PART_NAME" VARCHAR2(255 CHAR), 
	"SAMPLED_FROM_OBJ_ID" NUMBER, 
	"PRESERVE_METHOD" VARCHAR2(50), 
	"DERIVED_FROM_CAT_ITEM" NUMBER, 
	"CHANGED_AGENT_ID" NUMBER, 
	"CHANGED_DATE" DATE, 
	"COLL_OBJECT_REMARKS" VARCHAR2(4000), 
	"IS_CURRENT_FG" NUMBER(1,0), 
	"LOT_COUNT_MODIFIER" VARCHAR2(5 CHAR), 
	"LOT_COUNT" NUMBER, 
	 CONSTRAINT "SPECIMEN_PART_PRES_HIST_PK" PRIMARY KEY ("SPECIMEN_PART_PRES_HIST_ID")
  USING INDEX  ENABLE
   ) 