
  CREATE TABLE "SPECIMEN_PART_ATTRIBUTE" 
   (	"PART_ATTRIBUTE_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"ATTRIBUTE_TYPE" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"ATTRIBUTE_VALUE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ATTRIBUTE_UNITS" VARCHAR2(30 CHAR), 
	"DETERMINED_DATE" DATE, 
	"DETERMINED_BY_AGENT_ID" NUMBER, 
	"ATTRIBUTE_REMARK" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "FK_SPECPARTATTR_SPECPART" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "SPECIMEN_PART" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "FK_SPECPARTATTR_AGENT" FOREIGN KEY ("DETERMINED_BY_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_SPECPARTATTR_CTSPATTRTYPE" FOREIGN KEY ("ATTRIBUTE_TYPE")
	  REFERENCES "CTSPECPART_ATTRIBUTE_TYPE" ("ATTRIBUTE_TYPE") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_SPECIMEN_PART_ATTRIBUTE" ON "SPECIMEN_PART_ATTRIBUTE" ("PART_ATTRIBUTE_ID") 
  
ALTER TABLE "SPECIMEN_PART_ATTRIBUTE" ADD CONSTRAINT "PK_SPECIMEN_PART_ATTRIBUTE" PRIMARY KEY ("PART_ATTRIBUTE_ID")
  USING INDEX "PK_SPECIMEN_PART_ATTRIBUTE"  ENABLE;
