
  CREATE TABLE "TACC" 
   (	"FULLPATH" VARCHAR2(4000 CHAR), 
	"FILENAME" VARCHAR2(255 CHAR), 
	"FILETYPE" VARCHAR2(255 CHAR), 
	"LASTDATE" DATE DEFAULT sysdate, 
	"CRAWLED_PATH_DATE" DATE, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"STATUS" VARCHAR2(255 CHAR)
   ) ;
