
  CREATE TABLE "TACC_CHECK" 
   (	"COLLECTION_OBJECT_ID" NUMBER, 
	"BARCODE" VARCHAR2(255 CHAR), 
	"FOLDER" VARCHAR2(255 CHAR), 
	"CHKDATE" DATE DEFAULT sysdate, 
	"STATUS" VARCHAR2(255 CHAR), 
	"JPG_STATUS" VARCHAR2(255 CHAR)
   ) ;
