
  CREATE TABLE "TAG" 
   (	"TAG_ID" NUMBER NOT NULL ENABLE, 
	"MEDIA_ID" NUMBER NOT NULL ENABLE, 
	"REMARK" VARCHAR2(4000 CHAR), 
	"REFTOP" NUMBER, 
	"REFLEFT" NUMBER, 
	"REFH" NUMBER, 
	"REFW" NUMBER, 
	"IMGH" NUMBER, 
	"IMGW" NUMBER, 
	"COLLECTION_OBJECT_ID" NUMBER, 
	"COLLECTING_EVENT_ID" NUMBER, 
	"LOCALITY_ID" NUMBER, 
	"AGENT_ID" NUMBER, 
	 CONSTRAINT "TAG_PK" PRIMARY KEY ("TAG_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_TAG_COLLEVENT" FOREIGN KEY ("COLLECTING_EVENT_ID")
	  REFERENCES "COLLECTING_EVENT" ("COLLECTING_EVENT_ID") ENABLE
   ) 