
  CREATE TABLE "TAXON_ATTRIBUTE" 
   (	"TAXON_ATTRIBUTE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TAXON_ATTRIBUTE_TYPE" VARCHAR2(60) NOT NULL ENABLE, 
	"ATTRIBUTE_VALUE" VARCHAR2(4000) NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"CREATED_TIMESTAMP" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"LAST_MODIFIED" TIMESTAMP (6), 
	 CONSTRAINT "TAXON_ATTRIBUTE_PK" PRIMARY KEY ("TAXON_ATTRIBUTE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TAXON_ATTRIBUTE_FK1" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE
   ) ;
COMMENT ON TABLE "TAXON_ATTRIBUTE" IS 'Attributes of taxa';
COMMENT ON COLUMN "TAXON_ATTRIBUTE"."TAXON_ATTRIBUTE_ID" IS 'surrogate numeric primary key';
COMMENT ON COLUMN "TAXON_ATTRIBUTE"."TAXON_ATTRIBUTE_TYPE" IS 'The kind of attribute';
COMMENT ON COLUMN "TAXON_ATTRIBUTE"."ATTRIBUTE_VALUE" IS 'The value of the attribue';
COMMENT ON COLUMN "TAXON_ATTRIBUTE"."TAXON_NAME_ID" IS 'Taxonomy record to which this attribute applies.';
COMMENT ON COLUMN "TAXON_ATTRIBUTE"."CREATED_AGENT_ID" IS 'The agent who created this taxon attribute record.';
COMMENT ON COLUMN "TAXON_ATTRIBUTE"."CREATED_TIMESTAMP" IS 'The date this record was created.';
COMMENT ON COLUMN "TAXON_ATTRIBUTE"."LAST_MODIFIED" IS 'The date this record was last modified.';
