
  CREATE TABLE "TAXON_AUTHOR" 
   (	"TAXON_AUTHOR_ID" NUMBER NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AUTHORSHIP_ROLE" VARCHAR2(30) DEFAULT 'zoological author' NOT NULL ENABLE, 
	"SORT_POSITION_IN_ROLE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_PK" PRIMARY KEY ("TAXON_AUTHOR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_FK1" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_FK2" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_FK3" FOREIGN KEY ("AUTHORSHIP_ROLE")
	  REFERENCES "CTAUTHORSHIP_ROLE" ("AUTHORSHIP_ROLE") ENABLE
   ) 