
  CREATE TABLE "TAXONOMY_PUBLICATION" 
   (	"TAXONOMY_PUBLICATION_ID" NUMBER NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"PUBLICATION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_TAX_PUB_TAX" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE, 
	 CONSTRAINT "FK_TAX_PUB_PUB" FOREIGN KEY ("PUBLICATION_ID")
	  REFERENCES "PUBLICATION" ("PUBLICATION_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_TAXONOMY_PUBLICATION_ID" ON "TAXONOMY_PUBLICATION" ("TAXONOMY_PUBLICATION_ID") 
  
ALTER TABLE "TAXONOMY_PUBLICATION" ADD CONSTRAINT "PK_TAXONOMY_PUBLICATION_ID" PRIMARY KEY ("TAXONOMY_PUBLICATION_ID")
  USING INDEX "PK_TAXONOMY_PUBLICATION_ID"  ENABLE;
