
  CREATE TABLE "TAXON_HABITAT" 
   (	"TAXON_HABITAT_ID" NUMBER, 
	"TAXON_NAME_ID" NUMBER, 
	"TAXON_HABITAT" VARCHAR2(15 CHAR), 
	 CONSTRAINT "U_TAXON_HABITAT" UNIQUE ("TAXON_NAME_ID", "TAXON_HABITAT")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PK_TAXON_HABITAT_ID" PRIMARY KEY ("TAXON_HABITAT_ID")
  USING INDEX  ENABLE
   ) 