
  CREATE TABLE "TAXON_AUTHOR" 
   (	"TAXON_AUTHOR_ID" NUMBER NOT NULL ENABLE, 
	"TAXON_NAME_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"AUTHORSHIP_ROLE" VARCHAR2(30) DEFAULT 'zoological author' NOT NULL ENABLE, 
	"SORT_POSITION_IN_ROLE" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_PK" PRIMARY KEY ("TAXON_AUTHOR_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_FK1" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_FK2" FOREIGN KEY ("TAXON_NAME_ID")
	  REFERENCES "TAXONOMY" ("TAXON_NAME_ID") ENABLE, 
	 CONSTRAINT "TAXON_AUTHOR_FK3" FOREIGN KEY ("AUTHORSHIP_ROLE")
	  REFERENCES "CTAUTHORSHIP_ROLE" ("AUTHORSHIP_ROLE") ENABLE
   ) ;
COMMENT ON TABLE "TAXON_AUTHOR" IS 'Table to relate taxon names to agents to construct scientific name authorship strings.';
COMMENT ON COLUMN "TAXON_AUTHOR"."TAXON_AUTHOR_ID" IS 'Surogate Numeric Primary Key';
COMMENT ON COLUMN "TAXON_AUTHOR"."TAXON_NAME_ID" IS 'The taxon for which the associated agent is an author.';
COMMENT ON COLUMN "TAXON_AUTHOR"."AGENT_ID" IS 'The agent who is an author for the associated taxon.';
COMMENT ON COLUMN "TAXON_AUTHOR"."AUTHORSHIP_ROLE" IS 'The role for the agent in the authorship of the taxon, determines functional placement in botanical authorship strings.';
COMMENT ON COLUMN "TAXON_AUTHOR"."SORT_POSITION_IN_ROLE" IS 'Sort order for the agent within the role in the authorship string.';
