
  CREATE TABLE "TEMP_MEDIA" 
   (	"MEDIA_ID" NUMBER NOT NULL ENABLE, 
	"MEDIA_URI" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MIME_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MEDIA_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PREVIEW_URI" VARCHAR2(255 CHAR), 
	"CHECKSUM" VARCHAR2(4000 CHAR), 
	"FILENAME" VARCHAR2(255 CHAR)
   ) 