
  CREATE TABLE "TRANS_AGENT" 
   (	"TRANS_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"TRANS_AGENT_ROLE" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "FK_TRANS_AGNT_TRANS" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE, 
	 CONSTRAINT "FK_TRANS_AGNT_AGNT" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "TRANS_AGENT_PKEY" ON "TRANS_AGENT" ("TRANS_AGENT_ID") 
  
ALTER TABLE "TRANS_AGENT" ADD CONSTRAINT "TRANS_AGENT_PKEY" PRIMARY KEY ("TRANS_AGENT_ID")
  USING INDEX "TRANS_AGENT_PKEY"  ENABLE