
  CREATE TABLE "TRANS_CONTAINER" 
   (	"TRANS_CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FK_TRANS_CONTAINER_CONTAINER" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CONTAINER" ("CONTAINER_ID") ENABLE, 
	 CONSTRAINT "FK_TRANS_CONTAINER_TRANS" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE
   ) 
  CREATE UNIQUE INDEX "PK_TRANS_CONTAINER" ON "TRANS_CONTAINER" ("TRANS_CONTAINER_ID") 
  
ALTER TABLE "TRANS_CONTAINER" ADD CONSTRAINT "PK_TRANS_CONTAINER" PRIMARY KEY ("TRANS_CONTAINER_ID")
  USING INDEX "PK_TRANS_CONTAINER"  ENABLE