
  CREATE TABLE "TRANS" 
   (	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"AUTH_AGENT_ID" NUMBER, 
	"TRANS_DATE" DATE, 
	"TRANS_ENTERED_AGENT_ID" NUMBER, 
	"RECEIVED_AGENT_ID" NUMBER, 
	"CORRESP_FG" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(18 CHAR) NOT NULL ENABLE, 
	"NATURE_OF_MATERIAL" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"TRANS_REMARKS" VARCHAR2(4000 CHAR), 
	"INSTITUTION_ACRONYM" VARCHAR2(20 CHAR), 
	"TRANS_AGENCY_ID" NUMBER, 
	"COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"IS_PUBLIC_FG" NUMBER(1,0), 
	"DATE_ENTERED" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "TRANS_TRANSACTION_TYPE" CHECK (TRANSACTION_TYPE IN ('accn', 'loan', 'borrow', 'deaccession')) ENABLE, 
	 CONSTRAINT "TRANS_CORRESP_FG" CHECK (CORRESP_FG IN (0,1)) ENABLE, 
	 CONSTRAINT "FK_TRANS_ENTERED_AGENT_ID" FOREIGN KEY ("TRANS_ENTERED_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_TRANS_AGENCY_ID" FOREIGN KEY ("TRANS_AGENCY_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_AUTH_AGENT_ID" FOREIGN KEY ("AUTH_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "FK_TRANS_COLLN" FOREIGN KEY ("COLLECTION_ID")
	  REFERENCES "COLLECTION" ("COLLECTION_ID") ENABLE
   ) 
  CREATE INDEX "PK_TRANS_ID" ON "TRANS" ("TRANSACTION_ID") 
  
ALTER TABLE "TRANS" ADD PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX "PK_TRANS_ID"  ENABLE;
COMMENT ON TABLE "TRANS" IS 'Supertype for all transactions.  Transactions record the movement of specimens and related material in and out of the institution.';
COMMENT ON COLUMN "TRANS"."NATURE_OF_MATERIAL" IS 'A description of the material involved in the transaction.';
COMMENT ON COLUMN "TRANS"."TRANS_REMARKS" IS 'Internal remarks concerning the transaction.';
COMMENT ON COLUMN "TRANS"."INSTITUTION_ACRONYM" IS 'Deprecated';
COMMENT ON COLUMN "TRANS"."TRANS_AGENCY_ID" IS 'Deprecated';
COMMENT ON COLUMN "TRANS"."COLLECTION_ID" IS 'Collection that this transaction is related to.';
COMMENT ON COLUMN "TRANS"."IS_PUBLIC_FG" IS 'Deprecated';
COMMENT ON COLUMN "TRANS"."DATE_ENTERED" IS 'Date on which this transaction record was entered.';
COMMENT ON COLUMN "TRANS"."TRANSACTION_ID" IS 'Surrogate Numeric Primary Key';
COMMENT ON COLUMN "TRANS"."AUTH_AGENT_ID" IS 'Deprecated';
COMMENT ON COLUMN "TRANS"."TRANS_DATE" IS 'Date on which this transaction occurred.';
COMMENT ON COLUMN "TRANS"."TRANS_ENTERED_AGENT_ID" IS 'Deprecated';
COMMENT ON COLUMN "TRANS"."RECEIVED_AGENT_ID" IS 'Deprecated.';
COMMENT ON COLUMN "TRANS"."CORRESP_FG" IS 'Deprecated';
COMMENT ON COLUMN "TRANS"."TRANSACTION_TYPE" IS 'The type of transaction.  Domain:accn, deaccession, borrow, loan.';
