
  CREATE TABLE "TRANS_CONTAINER" 
   (	"TRANS_CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_ID" NUMBER NOT NULL ENABLE, 
	"CONTAINER_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_TRANS_CONTAINER" PRIMARY KEY ("TRANS_CONTAINER_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_TRANS_CONTAINER_CONTAINER" FOREIGN KEY ("CONTAINER_ID")
	  REFERENCES "CONTAINER" ("CONTAINER_ID") ENABLE, 
	 CONSTRAINT "FK_TRANS_CONTAINER_TRANS" FOREIGN KEY ("TRANSACTION_ID")
	  REFERENCES "TRANS" ("TRANSACTION_ID") ENABLE
   ) 