
  CREATE TABLE "UNDERSCORE_COLLECTION_AGENT" 
   (	"UNDERSCORE_COLL_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"UNDERSCORE_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"ROLE" VARCHAR2(60) NOT NULL ENABLE, 
	"REMARKS" VARCHAR2(255), 
	"CREATED_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"DATE_CREATED" DATE DEFAULT CURRENT_TIMESTAMP, 
	 CONSTRAINT "UNDERSCORE_COLLECTION_AGEN_PK" PRIMARY KEY ("UNDERSCORE_COLL_AGENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNDERSCORE_COLLECTION_AGE_FK3" FOREIGN KEY ("ROLE")
	  REFERENCES "CTUNDERSCORE_COLL_AGENT_ROLE" ("ROLE") ENABLE, 
	 CONSTRAINT "UNDERSCORE_COLLECTION_AGE_FK1" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE, 
	 CONSTRAINT "UNDERSCORE_COLLECTION_AGE_FK2" FOREIGN KEY ("UNDERSCORE_COLLECTION_ID")
	  REFERENCES "UNDERSCORE_COLLECTION" ("UNDERSCORE_COLLECTION_ID") ENABLE
   ) 