
  CREATE TABLE "UNDERSCORE_COLLECTION" 
   (	"UNDERSCORE_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(900), 
	"UNDERSCORE_AGENT_ID" NUMBER, 
	"MASK_FG" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"HTML_DESCRIPTION" CLOB, 
	"TYPE" VARCHAR2(50), 
	 CONSTRAINT "UNDERSCORECOLLECTION_PK" PRIMARY KEY ("UNDERSCORE_COLLECTION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_UNDERSCORE_AGENT_ID" FOREIGN KEY ("UNDERSCORE_AGENT_ID")
	  REFERENCES "AGENT" ("AGENT_ID") ENABLE
   ) 