
  CREATE TABLE "UNDERSCORE_COLLECTION" 
   (	"UNDERSCORE_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_NAME" VARCHAR2(255) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(900), 
	"UNDERSCORE_AGENT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "UNDERSCORECOLLECTION_PK" PRIMARY KEY ("UNDERSCORE_COLLECTION_ID")
  USING INDEX  ENABLE
   ) 