
  CREATE TABLE "UNDERSCORE_RELATION" 
   (	"UNDERSCORE_RELATION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"UNDERSCORE_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"TIMESTAMPADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"CREATEDBY" VARCHAR2(255) DEFAULT sys_context('USERENV', 'CURRENT_USER'), 
	 CONSTRAINT "UNDERSCORE_RELATION_PK" PRIMARY KEY ("UNDERSCORE_RELATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNIQUE_OBJECT_COLLECTION" UNIQUE ("COLLECTION_OBJECT_ID", "UNDERSCORE_COLLECTION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNDERSCORE_RELATION_FK1" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "UNDERSCORE_RELATION_FK2" FOREIGN KEY ("UNDERSCORE_COLLECTION_ID")
	  REFERENCES "UNDERSCORE_COLLECTION" ("UNDERSCORE_COLLECTION_ID") ENABLE
   ) 