
  CREATE TABLE "UNDERSCORE_COLLECTION_CITATION" 
   (	"UNDERSCORE_COLL_CITATION_ID" NUMBER NOT NULL ENABLE, 
	"UNDERSCORE_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"PUBLICATION_ID" NUMBER NOT NULL ENABLE, 
	"TYPE" VARCHAR2(50) NOT NULL ENABLE, 
	"PAGES" VARCHAR2(255), 
	"REMARKS" VARCHAR2(4000), 
	"CITATION_PAGE_URI" VARCHAR2(4000), 
	"CREATED_BY_AGENT_ID" NUMBER NOT NULL ENABLE, 
	"DATE_CREATED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"LAST_UPDATED_BY_AGENT_ID" NUMBER, 
	"DATE_LAST_UPDATED" TIMESTAMP (6), 
	 CONSTRAINT "UNDERSCORE_COLLECTION_CITA_PK" PRIMARY KEY ("UNDERSCORE_COLL_CITATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNDERSCORE_COLLECTION_CIT_FK1" FOREIGN KEY ("PUBLICATION_ID")
	  REFERENCES "PUBLICATION" ("PUBLICATION_ID") ENABLE, 
	 CONSTRAINT "UNDERSCORE_COLLECTION_CIT_FK2" FOREIGN KEY ("UNDERSCORE_COLLECTION_ID")
	  REFERENCES "UNDERSCORE_COLLECTION" ("UNDERSCORE_COLLECTION_ID") ENABLE, 
	 CONSTRAINT "UNDERSCORE_COLLECTION_CIT_FK3" FOREIGN KEY ("TYPE")
	  REFERENCES "CTUNDERSCORE_COLL_CIT_TYPE" ("TYPE") ENABLE
   ) ;
COMMENT ON TABLE "UNDERSCORE_COLLECTION_CITATION" IS 'Citations of works that have information directly related to a named group, such as histories of expeditions, publications describing the work performed in a grant funded project, etc. ';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."UNDERSCORE_COLL_CITATION_ID" IS 'surrogate numeric primary key';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."UNDERSCORE_COLLECTION_ID" IS 'the named group to which the citation applies.';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."PUBLICATION_ID" IS 'the publication that is being cited';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."TYPE" IS 'the type of citation';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."PAGES" IS 'page range for the citation in the publication..';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."REMARKS" IS 'Free text about the citation.';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."CITATION_PAGE_URI" IS 'URI for the first page in the cited page range.';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."CREATED_BY_AGENT_ID" IS 'automatic. the agent who created the citation record.';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."DATE_CREATED" IS 'automatic. timestamp for the creation of this citation record';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."LAST_UPDATED_BY_AGENT_ID" IS 'automatic. the agent whom most recently updated this citation record.';
COMMENT ON COLUMN "UNDERSCORE_COLLECTION_CITATION"."DATE_LAST_UPDATED" IS 'automatic. timestamp for the most recent update to the citation record.';
