
  CREATE TABLE "UNDERSCORE_RELATION" 
   (	"UNDERSCORE_RELATION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"UNDERSCORE_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"TIMESTAMPADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"CREATEDBY" VARCHAR2(255) DEFAULT sys_context('USERENV', 'CURRENT_USER'), 
	 CONSTRAINT "UNIQUE_OBJECT_COLLECTION" UNIQUE ("COLLECTION_OBJECT_ID", "UNDERSCORE_COLLECTION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNDERSCORE_RELATION_PK" PRIMARY KEY ("UNDERSCORE_RELATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNDERSCORE_RELATION_FK1" FOREIGN KEY ("COLLECTION_OBJECT_ID")
	  REFERENCES "COLL_OBJECT" ("COLLECTION_OBJECT_ID") ENABLE, 
	 CONSTRAINT "UNDERSCORE_RELATION_FK2" FOREIGN KEY ("UNDERSCORE_COLLECTION_ID")
	  REFERENCES "UNDERSCORE_COLLECTION" ("UNDERSCORE_COLLECTION_ID") ENABLE
   ) ;
COMMENT ON TABLE "UNDERSCORE_RELATION" IS 'Relationships between named groups (arbitrary collections of cataloged items (underscore_collection)) and collection objects.';
COMMENT ON COLUMN "UNDERSCORE_RELATION"."UNDERSCORE_RELATION_ID" IS 'surrogate numeric primary key';
COMMENT ON COLUMN "UNDERSCORE_RELATION"."COLLECTION_OBJECT_ID" IS 'collection object participating in this relationship';
COMMENT ON COLUMN "UNDERSCORE_RELATION"."UNDERSCORE_COLLECTION_ID" IS 'arbitrary collection in which the related collection object is a member.';
COMMENT ON COLUMN "UNDERSCORE_RELATION"."TIMESTAMPADDED" IS 'timestamp indicating when the relationship between the named group and the cataloged item was created.';
COMMENT ON COLUMN "UNDERSCORE_RELATION"."CREATEDBY" IS 'user who created the record';
