
  CREATE TABLE "UNDERSCORE_RELATION" 
   (	"UNDERSCORE_RELATION_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"UNDERSCORE_COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	"TIMESTAMPADDED" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"CREATEDBY" VARCHAR2(255) DEFAULT sys_context('USERENV', 'CURRENT_USER'), 
	 CONSTRAINT "UNDERSCORE_RELATION_PK" PRIMARY KEY ("UNDERSCORE_RELATION_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNIQUE_OBJECT_COLLECTION" UNIQUE ("UNDERSCORE_COLLECTION_ID", "COLLECTION_OBJECT_ID")
  USING INDEX  ENABLE
   ) 