
  CREATE TABLE "USER_LOAN_REQUEST" 
   (	"REQUEST_DATE" DATE NOT NULL ENABLE, 
	"PROJECT_DESCRIPTION" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"LOAN_REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"PROJECT_TITLE" VARCHAR2(60 CHAR) NOT NULL ENABLE
   ) ;
