
  CREATE TABLE "USER_DATA" 
   (	"STREET_ADDR1" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"STREET_ADDR2" VARCHAR2(255 CHAR), 
	"CITY" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"STATE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"ZIP" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"COUNTRY_CDE" VARCHAR2(50 CHAR), 
	"MAIL_STOP" VARCHAR2(20 CHAR), 
	"FORMATTED_ADDR" VARCHAR2(510 CHAR), 
	"AGENT_ID" NUMBER, 
	"JOB_TITLE" VARCHAR2(25 CHAR), 
	"ADDR_REMARKS" VARCHAR2(255 CHAR), 
	"FIRST_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(60 CHAR) NOT NULL ENABLE, 
	"MIDDLE_NAME" VARCHAR2(60 CHAR), 
	"USER_ID" NUMBER NOT NULL ENABLE
   ) ;
