
  CREATE TABLE "USER_TABLE_ACCESS" 
   (	"AGENT_ID" NUMBER NOT NULL ENABLE, 
	"TABLE_NAME" VARCHAR2(40 CHAR) NOT NULL ENABLE, 
	"SELECT_FILTER" VARCHAR2(255 CHAR), 
	"INSERT_FILTER" VARCHAR2(255 CHAR), 
	"UPDATE_FILTER" VARCHAR2(255 CHAR), 
	"DELETE_FILTER" VARCHAR2(255 CHAR)
   ) ;
