
  CREATE TABLE "USER_LOAN_ITEM" 
   (	"LOAN_REQUEST_ID" NUMBER NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_REQUEST_DATE" DATE NOT NULL ENABLE, 
	"VOLUME_REQUESTED" VARCHAR2(20 CHAR), 
	"REMARKS" VARCHAR2(255 CHAR)
   ) 