
  CREATE TABLE "VIEWER" 
   (	"VIEWER_ID" NUMBER, 
	"VIEWER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PATH" VARCHAR2(255 CHAR), 
	"PARAMS" VARCHAR2(255 CHAR), 
	 CONSTRAINT "PKEY_VIEWER" PRIMARY KEY ("VIEWER_ID")
  USING INDEX  ENABLE
   ) 