
  CREATE TABLE "VIEWER" 
   (	"VIEWER_ID" NUMBER, 
	"VIEWER" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PATH" VARCHAR2(255 CHAR), 
	"PARAMS" VARCHAR2(255 CHAR)
   ) 
  CREATE UNIQUE INDEX "PKEY_VIEWER" ON "VIEWER" ("VIEWER_ID") 
  
ALTER TABLE "VIEWER" ADD CONSTRAINT "PKEY_VIEWER" PRIMARY KEY ("VIEWER_ID")
  USING INDEX "PKEY_VIEWER"  ENABLE;
