
  CREATE TABLE "VPD_COLLECTION_CDE" 
   (	"COLLECTION_CDE" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"COLLECTION_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_VPD_COLL_ID" PRIMARY KEY ("COLLECTION_ID")
  USING INDEX  ENABLE
   ) 
  PARTITION BY LIST ("COLLECTION_ID") 
 (PARTITION "MCZ_HERP"  VALUES (1) , 
 PARTITION "MCZ_MAMM"  VALUES (2) , 
 PARTITION "MCZ_MALA"  VALUES (3) , 
 PARTITION "MCZ_FISH"  VALUES (4) , 
 PARTITION "MCZ_BIRD"  VALUES (5) , 
 PARTITION "MCZ_VP"  VALUES (6) , 
 PARTITION "MCZ_IP"  VALUES (7) , 
 PARTITION "MCZ_IZ"  VALUES (8) , 
 PARTITION "MCZ_ENT"  VALUES (9) , 
 PARTITION "MCZ_SC"  VALUES (10) , 
 PARTITION "MCZ_CRYO"  VALUES (11) , 
 PARTITION "MCZ_MCZ"  VALUES (12) , 
 PARTITION "MCZ_HERPOBS"  VALUES (13) ) ;
