
  CREATE TABLE "Z_UNCHECKED_DISPOSITION" 
   (	"COLLECTION_CDE" VARCHAR2(10) NOT NULL ENABLE, 
	"COLLECTION_OBJECT_ID" NUMBER NOT NULL ENABLE, 
	"PART_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"PART_MODIFIER" VARCHAR2(60 CHAR), 
	"SAMPLED_FROM_OBJ_ID" NUMBER, 
	"PRESERVE_METHOD" VARCHAR2(50 CHAR), 
	"DERIVED_FROM_CAT_ITEM" NUMBER NOT NULL ENABLE, 
	"IS_TISSUE" NUMBER, 
	"COLL_OBJ_DISPOSITION" VARCHAR2(20 CHAR)
   ) 