
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ACCEPTED_LAT_LONG" ("LAT_LONG_ID", "LOCALITY_ID", "LAT_DEG", "DEC_LAT_MIN", "LAT_MIN", "LAT_SEC", "LAT_DIR", "LONG_DEG", "DEC_LONG_MIN", "LONG_MIN", "LONG_SEC", "LONG_DIR", "DEC_LAT", "DEC_LONG", "DATUM", "UTM_ZONE", "UTM_EW", "UTM_NS", "ORIG_LAT_LONG_UNITS", "DETERMINED_BY_AGENT_ID", "DETERMINED_DATE", "LAT_LONG_REF_SOURCE", "LAT_LONG_REMARKS", "MAX_ERROR_DISTANCE", "MAX_ERROR_UNITS", "NEAREST_NAMED_PLACE", "LAT_LONG_FOR_NNP_FG", "FIELD_VERIFIED_FG", "ACCEPTED_LAT_LONG_FG", "EXTENT", "GPSACCURACY", "GEOREFMETHOD", "VERIFICATIONSTATUS", "GEOLOCATE_SCORE", "GEOLOCATE_PRECISION", "VERIFIED_BY_AGENT_ID", "COORDINATE_PRECISION", "SPATIALFIT", "ERROR_POLYGON", "FOOTPRINT_SPATIALFIT", "EXTENT_UNITS") AS 
  select "LAT_LONG_ID","LOCALITY_ID","LAT_DEG","DEC_LAT_MIN","LAT_MIN","LAT_SEC","LAT_DIR",
"LONG_DEG","DEC_LONG_MIN","LONG_MIN","LONG_SEC","LONG_DIR","DEC_LAT","DEC_LONG","DATUM",
"UTM_ZONE","UTM_EW","UTM_NS","ORIG_LAT_LONG_UNITS","DETERMINED_BY_AGENT_ID","DETERMINED_DATE",
"LAT_LONG_REF_SOURCE","LAT_LONG_REMARKS","MAX_ERROR_DISTANCE","MAX_ERROR_UNITS","NEAREST_NAMED_PLACE",
"LAT_LONG_FOR_NNP_FG","FIELD_VERIFIED_FG","ACCEPTED_LAT_LONG_FG","EXTENT","GPSACCURACY","GEOREFMETHOD",
"VERIFICATIONSTATUS", GEOLOCATE_SCORE, GEOLOCATE_PRECISION, VERIFIED_BY_AGENT_ID, coordinate_precision, spatialfit,
error_polygon, footprint_spatialfit, extent_units
from lat_long where ACCEPTED_LAT_LONG_FG=1