
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "FP" ("PUBLICATION_ID", "FORMAT_STYLE", "FORMATTED_PUBLICATION") AS 
  select
		"PUBLICATION_ID","FORMAT_STYLE","FORMATTED_PUBLICATION" from form_pub_auth_year
	UNION
		select
		"PUBLICATION_ID","FORMAT_STYLE","FORMATTED_PUBLICATION" from form_pub_full_cit
 