
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PART_ATTRIBUTES_BY_CATITEM" ("COLLECTION_OBJECT_ID", "ATTRIBUTE_TYPE", "ATTRIBUTE_VALUE") AS 
  SELECT ci.collection_object_id,
    spa.attribute_type,
    spa.attribute_value
  FROM cataloged_item ci,
    SPECIMEN_PART sp,
    SPECIMEN_PART_ATTRIBUTE spa
  WHERE ci.COLLECTION_OBJECT_ID = sp.DERIVED_FROM_CAT_ITEM
  AND sp.COLLECTION_OBJECT_ID   = spa.COLLECTION_OBJECT_ID