
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PREPARATOR" ("COLLECTION_OBJECT_ID", "AGENT_ID", "COLLECTOR_ROLE", "COLL_NUM_PREFIX", "COLL_NUM", "COLL_NUM_SUFFIX", "COLL_ORDER", "COLLECTOR_ID") AS 
  SELECT "COLLECTION_OBJECT_ID","AGENT_ID","COLLECTOR_ROLE","COLL_NUM_PREFIX","COLL_NUM","COLL_NUM_SUFFIX","COLL_ORDER","COLLECTOR_ID"
FROM COLLECTOR
WHERE collector_role = 'p'