
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PROJECT_MEDIA_RELATION_VIEW" ("MEDIA_ID", "PROJECT_ID", "TITLE") AS 
  SELECT
MEDIA_ID, PROJECT_ID, project_name TITLE
FROM
MEDIA_RELATIONS, PROJECT
WHERE
RELATED_PRIMARY_KEY=PROJECT_ID and
lower(media_relationship) like '% project'
 